export const TextDirectory = {
    headerTitle: 'Organizations',
    headerText: 'Search for new partnership to looking their listings updates',

    headerButtonAddOrganization: 'Add an organization',

    searchInputPlaceholder: 'Enter a keyword',
    searchConditionAll: 'All organizations',

    buttonSearch: 'Search',
    buttonReset: 'Reset',

    labelYourOrganization: 'Your organization',

    buttonViewProfile: 'View profile',
    buttonEdit: 'Edit',
    buttonFollow: 'Follow',
    buttonFollowing: 'Following',

    counterOrganizations: function (value: number) {
        return value + ((value !== 1) ? ' organizations' : ' organization');
    },

    emptyResults: 'Empty',
    
    // location picker

    locationPicker: 'Location',

    locationEntryCities: 'Cities',
    locationEntryMetropolitanAreas: 'Metropolitan areas',
    locationEntryStates: 'States',
    locationEntryMultiStateRegions: 'Multi-state regions',

    locationEntries: {
        cities: [
            'New York',
            'Los Angeles',
            'Chicago',
            'Houston',
            'Phoenix',
            'Philadelphia',
            'San Antonio',
            'San Diego',
            'Dallas',
            'San Jose',
            'Austin',
            'Jacksonville',
            'Fort Worth',
            'San Francisco',
            'Columbus',
            'Charlotte',
            'Indianapolis',
            'Seattle',
            'Denver',
            'Washington Dc Dc',
            'El Paso',
            'Boston',
            'Nashville',
            'Detroit',
            'Portland',
            'Oklahoma City',
            'Las Vegas',
            'Memphis',
            'Louisville',
            'Baltimore',
            'Milwaukee',
            'Albuquerque',
            'Tucson',
            'Fresno',
            'Sacramento',
            'Mesa',
            'Kansas City',
            'Atlanta',
            'Colorado Springs',
            'Miami',
            'Raleigh',
            'Long Beach',
            'Virginia Beach',
            'Omaha',
            'Oakland',
            'Minneapolis',
            'Tulsa',
            'Arlington',
            'New Orleans',
            'Tampa',
            'Wichita',
            'Bakersfield',
            'Cleveland',
            'Aurora',
            'Anaheim',
            'Honolulu',
            'Santa Ana',
            'Riverside',
            'Corpus Christi',
            'Lexington Fayette',
            'Stockton',
            'Henderson',
            'St. Paul',
            'St. Louis',
            'Pittsburgh',
            'Cincinnati',
            'Anchorage',
            'Plano',
            'Orlando',
            'Greensboro',
            'Lincoln',
            'Irvine',
            'Newark',
            'Toledo',
            'Durham',
            'Chula Vista',
            'St. Petersburg',
            'Fort Wayne',
            'Jersey City',
            'Laredo',
            'Madison',
            'Scottsdale',
            'Lubbock',
            'Chandler',
            'Reno',
            'Buffalo',
            'Glendale',
            'North Las Vegas',
            'Gilbert',
            'Winston Salem',
            'Norfolk',
            'Chesapeake',
            'Irving',
            'Fremont',
            'Hialeah',
            'Garland',
            'Richmond',
            'Boise City',
            'Baton Rouge',
            'Spokane',
        ],
        metopolitanAreas: [
            'New York Metro Area',
            'Greater Los Angeles',
            'Chicagoland',
            'Dallas–Fort Worth',
            'Greater Houston',
            'Washington Metro Area',
            'Miami Metro Area',
            'Delaware Valley',
            'Atlanta Metro',
            'Greater Boston',
            'Phoenix Metro Area',
            'San Francisco Bay Area',
            'Inland Empire',
            'Metro Detroit',
            'Seattle Metro Area',
            'Twin Cities',
            'San Diego County',
            'Tampa Bay Area',
            'Denver Metro Area',
            'Baltimore Metro area',
            'Greater St. Louis',
            'Charlotte Metro',
            'Greater Orlando',
            'Greater San Antonio',
            'Greater Portland',
        ],
        states: [
            'California',
            'Texas',
            'Florida',
            'New York',
            'Pennsylvania',
            'Illinois',
            'Ohio',
            'Georgia',
            'North Carolina',
            'Michigan',
            'New Jersey',
            'Virginia',
            'Washington',
            'Arizona',
            'Massachusetts',
            'Tennessee',
            'Indiana',
            'Missouri',
            'Maryland',
            'Wisconsin',
            'Colorado',
            'Minnesota',
            'South Carolina',
            'Alabama',
            'Louisiana',
            'Kentucky',
            'Oregon',
            'Oklahoma',
            'Connecticut',
            'Iowa',
            'Utah',
            'Nevada',
            'Arkansas',
            'Mississippi',
            'Kansas',
            'New Mexico',
            'Nebraska',
            'West Virginia',
            'Idaho',
            'Hawaii',
            'New Hampshire',
            'Maine',
            'Montana',
            'Rhode Island',
            'Delaware',
            'South Dakota',
            'North Dakota',
            'Alaska',
            'District of Columbia',
            'Vermont',
        ],
        multiStateRegions: [
            'West Coast',
            'East Coast',
            'Northeast',
            'Southeast',
            'Southwest',
            'Mideast',
            'Midwest',
            'New England',
            'Great Lakes',
            'Plains',
            'Rocky Mountains'
        ],
    },
    
    // interest picker

    interestPicker: 'Interests',

    interestEntryTop: 'Top interests',

    interestEntries: {
        top: [
            { label: 'Selling', value: 'Selling' },
            { label: 'Buying', value: 'Buying' },
            { label: 'Joint ventures', value: 'Joint ventures' },
            { label: 'Leasing', value: 'Leasing' },
            { label: 'Option-to-buy', value: 'Option-to-buy' },
        ]
    },
};