export const TextDirectory = {
    headerTitle: 'Organizations',
    headerText: 'Search for new partnership to looking their listings updates',

    headerButtonAddOrganization: 'Add an organization',

    searchInputPlaceholder: 'Enter a keyword',
    searchConditionAll: 'All organizations',

    buttonSearch: 'Search',
    buttonReset: 'Reset',

    labelYourOrganization: 'Your organization',

    buttonViewProfile: 'View profile',
    buttonEdit: 'Edit',
    buttonFollow: 'Follow',
    buttonFollowing: 'Following',

    counterOrganizations: function (value: number) {
        return value + ((value !== 1) ? ' organizations' : ' organization');
    },

    emptyResults: 'Empty',

    locationPicker: 'Location',
    locationSearchPlaceholder: 'Enter a location',
    locationCities: 'Cities',
    locationMetropolitanAreas: 'Metropolitan areas',
    locationStates: 'States',
    locationMultiStateRegions: 'Multi-state regions',

    categoryPicker: 'Organization category',

    interestPicker: 'Interests',
    interestSearchPlaceholder: 'Enter an interest',
    interestTop: 'Top interests',
};

export const TextDirectoryData = {
    locationPicker: {
        MultiStateRegions: [
            'West Coast',
            'East Coast',
            'Northeast',
            'Southeast',
            'Southwest',
            'Mideast',
            'Midwest',
            'New England',
            'Great Lakes',
            'Plains',
            'Rocky Mountains'
        ],
        
        States: [
            'California',
            'Texas',
            'Florida',
            'New York',
            'Pennsylvania',
            'Illinois',
            'Ohio',
            'Georgia',
            'North Carolina',
            'Michigan',
            'New Jersey',
            'Virginia',
            'Washington',
            'Arizona',
            'Massachusetts',
            'Tennessee',
            'Indiana',
            'Missouri',
            'Maryland',
            'Wisconsin',
            'Colorado',
            'Minnesota',
            'South Carolina',
            'Alabama',
            'Louisiana',
            'Kentucky',
            'Oregon',
            'Oklahoma',
            'Connecticut',
            'Iowa',
            'Utah',
            'Nevada',
            'Arkansas',
            'Mississippi',
            'Kansas',
            'New Mexico',
            'Nebraska',
            'West Virginia',
            'Idaho',
            'Hawaii',
            'New Hampshire',
            'Maine',
            'Montana',
            'Rhode Island',
            'Delaware',
            'South Dakota',
            'North Dakota',
            'Alaska',
            'District of Columbia',
            'Vermont',
        ],
        
        MetropolitanAreas: [
            'New York Metro Area',
            'Greater Los Angeles',
            'Chicagoland',
            'Dallas–Fort Worth',
            'Greater Houston',
            'Washington Metro Area',
            'Miami Metro Area',
            'Delaware Valley',
            'Atlanta Metro',
            'Greater Boston',
            'Phoenix Metro Area',
            'San Francisco Bay Area',
            'Inland Empire',
            'Metro Detroit',
            'Seattle Metro Area',
            'Twin Cities',
            'San Diego County',
            'Tampa Bay Area',
            'Denver Metro Area',
            'Baltimore Metro area',
            'Greater St. Louis',
            'Charlotte Metro',
            'Greater Orlando',
            'Greater San Antonio',
            'Greater Portland',
        ],

        Cities: [
            'New York',
            'Los Angeles',
            'Chicago',
            'Houston',
            'Phoenix',
            'Philadelphia',
            'San Antonio',
            'San Diego',
            'Dallas',
            'San Jose',
            'Austin',
            'Jacksonville',
            'Fort Worth',
            'San Francisco',
            'Columbus',
            'Charlotte',
            'Indianapolis',
            'Seattle',
            'Denver',
            'Washington Dc Dc',
            'El Paso',
            'Boston',
            'Nashville',
            'Detroit',
            'Portland',
            'Oklahoma City',
            'Las Vegas',
            'Memphis',
            'Louisville',
            'Baltimore',
            'Milwaukee',
            'Albuquerque',
            'Tucson',
            'Fresno',
            'Sacramento',
            'Mesa',
            'Kansas City',
            'Atlanta',
            'Colorado Springs',
            'Miami',
            'Raleigh',
            'Long Beach',
            'Virginia Beach',
            'Omaha',
            'Oakland',
            'Minneapolis',
            'Tulsa',
            'Arlington',
            'New Orleans',
            'Tampa',
            'Wichita',
            'Bakersfield',
            'Cleveland',
            'Aurora',
            'Anaheim',
            'Honolulu',
            'Santa Ana',
            'Riverside',
            'Corpus Christi',
            'Lexington Fayette',
            'Stockton',
            'Henderson',
            'St. Paul',
            'St. Louis',
            'Pittsburgh',
            'Cincinnati',
            'Anchorage',
            'Plano',
            'Orlando',
            'Greensboro',
            'Lincoln',
            'Irvine',
            'Newark',
            'Toledo',
            'Durham',
            'Chula Vista',
            'St. Petersburg',
            'Fort Wayne',
            'Jersey City',
            'Laredo',
            'Madison',
            'Scottsdale',
            'Lubbock',
            'Chandler',
            'Reno',
            'Buffalo',
            'Glendale',
            'North Las Vegas',
            'Gilbert',
            'Winston Salem',
            'Norfolk',
            'Chesapeake',
            'Irving',
            'Fremont',
            'Hialeah',
            'Garland',
            'Richmond',
            'Boise City',
            'Baton Rouge',
            'Spokane',
        ],
    },

    categoryPicker: {
        categories: [
            { label: 'Gas station', value: 'Gas station' },
            { label: 'Parking', value: 'Parking' },
            { label: 'Car wash', value: 'Car wash' },
            { label: 'Big box retail', value: 'Big box retail' },
            { label: 'Medium retail', value: ' Medium retail' },
            { label: 'Mall', value: 'Mall' },
            { label: 'Strip mall', value: 'Strip mall' },
            { label: 'Self storage', value: 'Self storage' },
            { label: 'Convenience store', value: 'Convenience store' },
            { label: 'Railway', value: 'Railway' },
            { label: 'Subway', value: 'Subway' },
            { label: 'Highway system', value: 'Highway system' },
            { label: 'Airport', value: 'Airport' },
            { label: 'Port authorities', value: 'Port authorities' },
            { label: 'Logistics company', value: 'Logistics company' },
            { label: 'Real estate developer', value: 'Real estate developer' },
            { label: 'Health system', value: 'Health system' },
            { label: 'Hospital', value: 'Hospital' },
            { label: 'School', value: 'School' },
            { label: 'College', value: 'College' },
            { label: 'Coal plant', value: 'Coal plant' },
            { label: 'Utility', value: 'Utility' },
            { label: 'REIT', value: 'REIT' },
            { label: 'Bank', value: 'Bank' },
            { label: 'Family offices', value: 'Family offices' },
            { label: 'State government', value: 'State government' },
            { label: 'County governmen', value: 'County governmen' },
            { label: 'City government', value: 'City government' },
            { label: 'Regional government', value: 'Regional government' },
            { label: 'Housing authority', value: 'Housing authority' },
            { label: 'Port authority', value: 'Port authority' },
            { label: 'Stadium authority', value: 'Stadium authority' },
            { label: 'Army', value: 'Army' },
            { label: 'Navy', value: 'Navy' },
            { label: 'Airforce', value: 'Airforce' },
            { label: 'Warehouse', value: 'Warehouse' },
            { label: 'Individuals', value: 'Individuals' },
        ],

        catalog: [
            {
                label: 'Automotive',
                options: [
                    { label: 'Gas station', value: 'Gas station' },
                    { label: 'Parking', value: 'Parking' },
                    { label: 'Car wash', value: 'Car wash' },
                ]
            },
            {
                label: 'Retail',
                options: [
                    { label: 'Big box retail', value: 'Big box retail' },
                    { label: 'Medium retail', value: ' Medium retail' },
                    { label: 'Mall', value: 'Mall' },
                    { label: 'Strip mall', value: 'Strip mall' },
                    { label: 'Self storage', value: 'Self storage' },
                    { label: 'Convenience store', value: 'Convenience store' },
                ]
            },
            {
                label: 'Transportation',
                options: [
                    { label: 'Railway', value: 'Railway' },
                    { label: 'Subway', value: 'Subway' },
                    { label: 'Highway system', value: 'Highway system' },
                    { label: 'Airport', value: 'Airport' },
                    { label: 'Port authorities', value: 'Port authorities' },
                    { label: 'Logistics company', value: 'Logistics company' },
                ]
            },
            {
                label: 'Real estate developer',
                options: [
                    { label: 'Real estate developer', value: 'Real estate developer' },
                ]
            },
            {
                label: 'Healthcare',
                options: [
                    { label: 'Health system', value: 'Health system' },
                    { label: 'Hospital', value: 'Hospital' },
                ]
            },
            {
                label: 'Education',
                options: [
                    { label: 'School', value: 'School' },
                    { label: 'College', value: 'College' },
                ]
            },
            {
                label: 'Energy and utilities',
                options: [
                    { label: 'Coal plant', value: 'Coal plant' },
                    { label: 'Utility', value: 'Utility' },
                ]
            },
            {
                label: 'Finance',
                options: [
                    { label: 'REIT', value: 'REIT' },
                    { label: 'Bank', value: 'Bank' },
                    { label: 'Family offices', value: 'Family offices' },
                ]
            },
            {
                label: 'Government',
                options: [
                    { label: 'State government', value: 'State government' },
                    { label: 'County governmen', value: 'County governmen' },
                    { label: 'City government', value: 'City government' },
                    { label: 'Regional government', value: 'Regional government' },
                    { label: 'Housing authority', value: 'Housing authority' },
                    { label: 'Port authority', value: 'Port authority' },
                    { label: 'Stadium authority', value: 'Stadium authority' },
                ]
            },
            {
                label: 'Military',
                options: [
                    { label: 'Army', value: 'Army' },
                    { label: 'Navy', value: 'Navy' },
                    { label: 'Airforce', value: 'Airforce' },
                ]
            },
            {
                label: 'Other',
                options: [
                    { label: 'Warehouse', value: 'Warehouse' },
                    { label: 'Individuals', value: 'Individuals' },
                ]
            },
        ],
    },

    interestPicker: [
        { label: 'Selling', value: 'Selling' },
        { label: 'Buying', value: 'Buying' },
        { label: 'Joint ventures', value: 'Joint ventures' },
        { label: 'Leasing', value: 'Leasing' },
        { label: 'Option-to-buy', value: 'Option-to-buy' },
    ],
};