import * as React from 'react';
export const TextOrganizationProfile = {

    headerTabOverview: 'Overview',
    headerTabListings: 'Listings',

    headerButtonEdit: 'Edit',
    headerButtonFollowFollow: 'Follow',
    headerButtonFollowUnFollow: 'Following',
    headerButtonAddListing: 'Add a listing',
    headerButtonAddListingDO: 'Development opportunity',
    headerButtonAddListingAR: 'Acquisition request',

    additionalInfoAbout: 'About',
    additionalInfoContacts: 'Contacts',
    additionalInfoWebsite: 'Website',

    overviewOrganizationTypeTitle: 'Organization type',
    overviewOrganizationLookingForTitle: 'Looking for',
    overviewOrganizationGeographiesTitle: 'Geographies',
    overviewOrganizationLocationsTitle: 'Locations',
    overviewOrganizationInterestsTitle: 'Interests',

    overviewDOTitle: 'Development opportunities',
    overviewDOTagRowShapeAndFormTitle: 'Shape and form',
    overviewDOTagRowCurrentUseTitle: 'Current use',
    overviewDOTagRowGoodFitForTitle: 'Good fit for',
    overviewDOTagRowSpecialAttributesTitle: 'Special attributes',
    overviewDOTagRowAvailabilityTitle: 'Availability',

    overviewArTitle: 'Acquisition requests',
    overviewArTagRowGeographiesTitle: 'Geographies',
    overviewArTagRowAreaRangeTitle: 'Area range',
    overviewArTagRowHeightLimitTitle: 'Height limit',
    overviewArTagRowActivityStatusTitle: 'Activity status',
    overviewArTagRowAquisitionBudgetTitle: '3-year acquisition budget',
    overviewArTagRowAquisitionRateTitle: 'Acquisition rate',
    overviewArTagRowClosingTimeTitle: 'Closing time',
    overviewArTagRowSpecialAttributesTitle: 'Special attributes',
    overviewArTagRowLandUseTitle: 'Land use',

    listingsDoTabTitle: 'Development opportunities',
    listingsArTabTitle: 'Acquisition requests',

    listingCreateDoTitle: 'Create development opportunity',
    listingCreateArTitle: 'Create acquisition request',

    overviewListingsDoFooterNonEmpty: 'View all',
    overviewListingsDoFooterAddListing: 'Add a listing',
    overviewListingsArFooterNonEmpty: 'View all',
    overviewListingsArFooterAddListing: 'Add a listing',

    listingCreateDoPhotoPlaceholderAdd: 'Add listing photo',
    listingCreateDoPhotoPlaceholderChange: 'Change listing photo',
    listingCreateDoNameTitle: 'Name',
    listingCreateDoNamePlaceholder: 'Name',
    listingCreateDoLocationTitle: 'Full adress',
    listingCreateDoLocationPlaceholder: 'Full adress',
    listingCreateDoAreaTitle: 'Area',
    listingCreateDoAreaPlaceholder: 'Area',
    listingCreateDoPriceTitle: 'Price',
    listingCreateDoPricePlaceholder: 'Price',
    listingCreateDoAvailabilityTitle: 'Availability',
    listingCreateDoAvailabilityPlaceholder: 'Availability',
    listingCreateDoSummaryTitle: 'Summary',
    listingCreateDoSummaryPlaceholder: 'Summary',

    listingCreateArShortDescriptionTitle: 'Short description',
    listingCreateArShortDescriptionPlaceholder: 'Short description',
    listingCreateArSummaryTitle: 'Summary',
    listingCreateArSummaryPlaceholder: 'Summary',

    listingCreateArareaRangeTitle: 'Area range',
    listingCreateArareaRangePlaceholder: 'Area range',
    listingCreateArgeographiesTitle: 'Geographies',
    listingCreateArgeographiesPlaceholder: 'Geographies',
    listingCreateArlandUseTitle: 'Land Use',
    listingCreateArlandUsePlaceholder: 'Land Use',
    listingCreateArspecialAttributesTitle: 'Special attributes',
    listingCreateArspecialAttributesPlaceholder: 'Special attributes',
    listingCreateArunitCapacityTitle: 'Unit Capacity',
    listingCreateArunitCapacityPlaceholder: 'Unit Capacity',

    listingCreateDoDealTypeTitle: 'Deal Type',
    listingCreateDoDealTypePlaceholder: 'Deal Type',
    listingCreateDoShapeAndFormTitle: 'Shape And Form',
    listingCreateDoShapeAndFormPlaceholder: 'Shape And Form',
    listingCreateDoCurrentUseTitle: 'Current Use',
    listingCreateDoCurrentUsePlaceholder: 'Current Use',
    listingCreateDoGoodFitForTitle: 'Good Fit For',
    listingCreateDoGoodFitForPlaceholder: 'Good Fit For',
    listingCreateDoSpecialAttributesTitle: 'Special attributes',
    listingCreateDoSpecialAttributesPlaceholder: 'Special attributes',

    listingDoTagRowTitileArea: 'Area',
    listingDoTagRowTitilePrice: 'Price',
    listingDoTagRowTitileSummary: 'Summary',
    listingDoTagRowTitileAvailability: 'Availability',
    listingDoTagRowTitileDealType: 'Deal type',
    listingDoTagRowTitileShapeAndForm: 'Shape and form',
    listingDoTagRowTitileCurrentUse: 'Current use',
    listingDoTagRowTitileGoodFitFor: 'Good fit for',
    listingDoTagRowTitileSpecialAttributes: 'Special attributes',

    listingDoOwerflowEdit: 'Edit',
    listingDoOwerflowDelete: 'Delete',
    listingDoOwerflowStreetView: 'Street view',
    listingDoOwerflowGoogleMaps: 'Google map',

    listingDoType: 'Development oportunity',
    listingDoLocked: 'Detailed requirements on request',

    listingArTagRowSummary: 'Summary',
    listingArTagRowAreaRange: 'Area range',
    listingArTagRowGeographies: 'Geographies',
    listingArTagRowLandUse: 'Land use',
    listingArTagRowSpecialAttributes: 'Special attributes',
    listingArTagRowUnitCapacity: 'Unit capacity',

    listingArOwerflowEdit: 'Edit',
    listingArOwerflowDelete: 'Delete',

    listingArType: 'Acquizition request',
    listingArLocked: 'Detailed requirements on request',

    listingEditDoLinkTextTitle: 'Link text',
    listingEditDoLinkTextPlaceholder: 'Link text',
    listingEditDoLinkUrlTitle: 'Link URL',
    listingEditDoLinkUrlPlaceholder: 'Link URL',
    listingEditDoLinkDelete: 'Delete',
    listingEditDoLinkAddFirst: 'Add link',
    listingEditDoLinkAdd: 'Add another link',

    placeholderOverviewGeneralMainText: (<><p>Share your organization type, geographies of operation,</p><p>and what are you looking for</p></>),
    placeholderOverviewGeneralButton: 'Add organization overview',
    placeholderOverviewGeneralModalTitle: 'Organization Profile',
    placeholderOverviewGeneralModalOrganizationTypeTitle: 'What\'s type of your entity?',
    placeholderOverviewGeneralModalOrganizationTypeDescription: 'Are you corporation, non profit or public entity?',
    placeholderOverviewGeneralModalLookingForTitle: 'What are you looking for?',
    placeholderOverviewGeneralModalLocations: 'Locations',
    placeholderOverviewGeneralModalLookingForDescription: 'Tell us more about your goals. What you are struggling to find?',
    placeholderOverviewGeneralModalGeographiesTitle: 'Where are you looking for deals?',
    placeholderOverviewGeneralModalInterests: 'Interests',
    placeholderOverviewGeneralModalGeographiesDescription: 'Whole US? Specific state or city?',

    placeholderOverviewDoMainText: 'Do you own development sites?',
    placeholderOverviewDOButton: 'Describe your portfolio',
    placeholderOverviewDOModalShapeAndFormTitle: 'Shape And Form',
    placeholderOverviewDOModalCurrentUseTitle: 'Current Use',
    placeholderOverviewDOModalGoodFitForTitle: 'Good Fit For',
    placeholderOverviewDOModalSpecialAttributesTitle: 'Special attributes',
    placeholderOverviewDOModalAvailabilityTitle: 'Availability',

    placeholderOverviewArMainText: 'Are you intrested in land acquisition?',
    placeholderOverviewArButton: 'Share your criteria',
    placegolderOverviewArModalTagRowGeographiesTitle: 'Geographies',
    placegolderOverviewArModalTagRowAreaRangeTitle: 'Area range',
    placegolderOverviewArModalTagRowHeightLimitTitle: 'Height limit',
    placegolderOverviewArModalTagRowActivityStatusTitle: 'Activity status',
    placegolderOverviewArModalTagRowAquisitionBudgetTitle: '3-year acquisition budget',
    placegolderOverviewArModalTagRowAquisitionRateTitle: 'Acquisition rate',
    placegolderOverviewArModalTagRowClosingTimeTitle: 'Closing time',
    placegolderOverviewArModalTagRowSpecialAttributesTitle: 'Special attributes',
    placegolderOverviewArModalTagRowLandUseTitle: 'Land use',

    placeholderListongsDoMainText: 'Do you own development sites?',
    placeholderListingsDoButton: 'Add an development opportunity',

    placeholderListongsArMainText: 'Are you intrested in land acquisition?',
    placeholderListingsArButton: 'Add an acquisition request',

    placeholderAbout: 'Add an intro paragraph',
    placeholderAboutModalAboutTitle: 'About',

    placeholderSocial: 'Add social links',
    placeholderSocialModalTitle: 'Add social links',
    placeholderSocialModal: 'Add social links',
    placeholderSocialModalWeb: 'Website',
    placeholderSocialModalTwitter: 'Twitter',
    placeholderSocialModalFacebook: 'Facebook',
    placeholderSocialModalLinkedIn: 'LinkedIn',

    placeholderContacts: 'Add contacts',
    placeholderContactsModalTitle: 'Add contact',
    placeholderContactsModalNameTitle: 'Name',
    placeholderContactsModalPhonelTitle: 'Phone',
    placeholderContactsModalEmailTitle: 'Email',
    placeholderContactsModalLinkedinTitle: 'Link',
    placeholderContactsModalPositionTitle: 'Position',
    placeholderContactsModalPhotoTitle: 'Photo',

    placeholderLocation: '+ Add locations',
    placeholderLocationModalLocationTitle: 'Location',
    placeholderCategory: '+ Add categories',
    placeholderCategoryModalTitle: 'Category',

    placeholderLogo: (<><p>Add your</p><p>profile logo</p></>),
    placeholderLogoModalLocationTitle: 'Logo',

};

// title=|>|text=|placeholder=