export const TextGlobal = {
    switch: 'Switch organization',
    settings: 'Settings',
    profileAndAccount: 'Profile & Account',
    notifications: 'Notifications',
    editProfile: 'Edit profile',
    manage: 'Manage',
    invite: 'Invite colleagues',
    inviteGlobal: 'Invite other organization',
    addOrganization: 'Create organization',
    addChannel: 'Create channel',
    signOut: 'Sign out',
    viewProfile: 'View profile',
    postUpdate: 'Post update',
    sendInvites: 'Send invites',
    invitePeopleTo: 'Invite people to',
    joinYourOrganization: 'Invite people to your organization',
    joinOpenland: 'Invite other organizations',
    startChat: 'Start chat',
};