export const TextOrganizationProfile = {

    headerTabOverview: 'Overview',
    headerTabListings: 'Listings',

    headerButtonEdit: 'Edit',
    headerButtonFollowFollow: 'Follow',
    headerButtonFollowUnFollow: 'Following',
    headerButtonAddListing: 'Add a listing',
    headerButtonAddListingDO: 'Development opportunity',
    headerButtonAddListingAR: 'Aquisition request',

    additionalInfoAbout: 'About',
    additionalInfoContacts: 'Contacts',
    additionalInfoWebsite: 'Website',

    overviewOrganizationTypeTitle: 'Organization type',
    overviewOrganizationLookingForTitle: 'Looking for',
    overviewOrganizationGeographiesTitle: 'Geographies',
    
    overviewDOTitle: 'Development opportunities',
    overviewDOTagRowShapeAndFormTitle: 'Shape and form',
    overviewDOTagRowCurrentUseTitle: 'Current use',
    overviewDOTagRowGoodFitForTitle: 'Good fit for',
    overviewDOTagRowSpecialAttributesTitle: 'Special attributes',
    overviewDOTagRowAvailabilityTitle: 'Availability',

    overviewArTitle: 'Acquisition requests',
    overviewArTagRowGeographiesTitle: 'Geographies',
    overviewArTagRowAreaRangeTitle: 'Area range',
    overviewArTagRowHeightLimitTitle: 'Height limit',
    overviewArTagRowLandUseTitle: 'Land use',
    overviewArTagRowSpecialAttributesTitle: 'Special attributes',
    overviewArTagRowActivityStatusTitle: 'Activity status',
    overviewArTagRowAquisitionBudgetTitle: '3-year aquisition budget',
    overviewArTagRowAquisitionRateTitle: 'Aquisition rate',
    overviewArTagRowClosingTimeTitle: 'Closing time',

    listingsDoTabTitle: 'Development opportunities',
    listingsArTabTitle: 'Acquisition requests',

    listingCreateDoTitle: 'Create development opportunity',
    listingCreateArTitle: 'Create acquisition requests',

    overviewListingsDoFooterNonEmpty: 'View all',
    overviewListingsDoFooterAddListing: 'Add a listing',
    overviewListingsArFooterNonEmpty: 'View all',
    overviewListingsArFooterAddListing: 'Add a listing',

    listingCreateDoPhotoPlaceholderAdd: 'Add listing photo',
    listingCreateDoPhotoPlaceholderChange: 'Change listing photo',
    listingCreateDoNameTitle: 'Name',
    listingCreateDoNamePlaceholder: 'Name',
    listingCreateDoLocationTitle: 'Full adress',
    listingCreateDoLocationPlaceholder: 'Full adress',
    listingCreateDoAreaTitle: 'Area',
    listingCreateDoAreaPlaceholder: 'Area',
    listingCreateDoPriceTitle: 'Price',
    listingCreateDoPricePlaceholder: 'Price',
    listingCreateDoAvailabilityTitle: 'Availability',
    listingCreateDoAvailabilityPlaceholder: 'Availability',
    listingCreateDoSummaryTitle: 'Summary',
    listingCreateDoSummaryPlaceholder: 'Summary',

    listingCreateArShortDescriptionTitle: 'Short description',
    listingCreateArShortDescriptionPlaceholder: 'Short description',
    listingCreateArSummaryTitle: 'Summary',
    listingCreateArSummaryPlaceholder: 'Summary',

    listingCreateArareaRangeTitle: 'Area range',
    listingCreateArareaRangePlaceholder: 'Area range',
    listingCreateArgeographiesTitle: 'Geographies',
    listingCreateArgeographiesPlaceholder: 'Geographies',
    listingCreateArlandUseTitle: 'Land Use',
    listingCreateArlandUsePlaceholder: 'Land Use',
    listingCreateArspecialAttributesTitle: 'Special attributes',
    listingCreateArspecialAttributesPlaceholder: 'Special attributes',
    listingCreateArunitCapacityTitle: 'Unit Capacity',
    listingCreateArunitCapacityPlaceholder: 'Unit Capacity',

    listingCreateDoDealTypeTitle: 'Deal Type',
    listingCreateDoDealTypePlaceholder: 'Deal Type',
    listingCreateDoShapeAndFormTitle: 'Shape And Form',
    listingCreateDoShapeAndFormPlaceholder: 'Shape And Form',
    listingCreateDoCurrentUseTitle: 'Current Use',
    listingCreateDoCurrentUsePlaceholder: 'Current Use',
    listingCreateDoGoodFitForTitle: 'Good Fit For',
    listingCreateDoGoodFitForPlaceholder: 'Good Fit For',
    listingCreateDoSpecialAttributesTitle: 'Special attributes',
    listingCreateDoSpecialAttributesPlaceholder: 'Special attributes',

    listingDoTagRowTitileArea : 'Area',
    listingDoTagRowTitilePrice : 'Price',
    listingDoTagRowTitileSummary : 'Summary',
    listingDoTagRowTitileAvailability : 'Availability',
    listingDoTagRowTitileDealType: 'Deal type',
    listingDoTagRowTitileShapeAndForm : 'Shape and form',
    listingDoTagRowTitileCurrentUse: 'Current use',
    listingDoTagRowTitileGoodFitFor : 'Good fit for',
    listingDoTagRowTitileSpecialAttributes: 'Special attributes',

    listingDoOwerflowEdit: 'Edit',
    listingDoOwerflowDelete: 'Delete',
    listingDoOwerflowStreetView: 'Street view',
    listingDoOwerflowGoogleMaps: 'Google map',
    
    listingDoType: 'Development oportunity',
    listingDoLocked: 'Detailed requirements on request',

    listingArTagRowSummary : 'Summary',
    listingArTagRowAreaRange : 'Area range',
    listingArTagRowGeographies : 'Geographies',
    listingArTagRowLandUse : 'Land use',
    listingArTagRowSpecialAttributes : 'Special attributes',
    listingArTagRowUnitCapacity : 'Unit capacity',
    
    listingArOwerflowEdit: 'Edit',
    listingArOwerflowDelete: 'Delete',
    
    listingArType: 'Acquizition request',
    listingArLocked: 'Detailed requirements on request',
    
    listingEditDoLinkTextTitle: 'Link text',
    listingEditDoLinkTextPlaceholder: 'Link text',
    listingEditDoLinkUrlTitle: 'Link URL',
    listingEditDoLinkUrlPlaceholder: 'Link URL',
    listingEditDoLinkDelete: 'Delete',
    listingEditDoLinkAddFirst: 'Add link',
    listingEditDoLinkAdd: 'Add another link',

    placeholderOverviewGeneralMainText: (<><p>Your account has been created - now it will be easier to connect with real estate companies.</p><p>To make most of it we recommend to share more information about your company.</p></>),
    placeholderOverviewGeneralButton: 'Improve Profile',
    placeholderOverviewGeneralModalTitle: 'Organization Profile',
    placeholderOverviewGeneralModalOrganizationTypeTitle: 'What\'s type of your entity?',
    placeholderOverviewGeneralModalOrganizationTypeDescription: 'Are you corporation, non profit or public entity?',
};

// title=|>|text=|placeholder=