export const AnaliticsNavigationMap: { [path: string]: string } = {
    "Discover": "chat_nav_start",
    "HomeDialogs": "chats",
    "NotificationCenter": "notifications",
    "CreateGroupAttrs": "new_group",
    "NewOrganization": "new_org",
    "SettingsProfile": "user_profile_edit",
    "SettingsNotifications": "account_notifications",
    "SettingsAppearance": "account_appearance",
    "SettingsEmail": "account_email",
    "ProfileUser": "user_profile",
    "ProfileGroup": "group_profile",
    "ProfileOrganization": "org_profile",
    "EditGroup": "group_profile_edit",
    "EditOrganization": "org_profile_edit",
    "EditCommunity": "community_profile_edit",
};