image: node:8.9.4

pipelines:
  default:
    - step:
        name: Test & Build
        caches:
          - node
        script:
          - yarn install
          - yarn test
          - yarn build
          - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
          - docker build -t openland/web:v${BITBUCKET_BUILD_NUMBER} .
          - docker push openland/web:v${BITBUCKET_BUILD_NUMBER}
    - step:
        name: Deploy to Staging
        deployment: staging
        script:
          - curl -o /tmp/google-cloud-sdk.tar.gz https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-200.0.0-linux-x86_64.tar.gz
          - tar -xvf /tmp/google-cloud-sdk.tar.gz -C /tmp/
          - /tmp/google-cloud-sdk/install.sh -q
          - source /tmp/google-cloud-sdk/path.bash.inc
          - gcloud -v
          - curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
          - chmod +x ./kubectl
          - echo $GCLOUD_API_KEYFILE | base64 --decode --ignore-garbage > ./gcloud-api-key.json
          - gcloud auth activate-service-account --key-file gcloud-api-key.json
          - gcloud --quiet config set project statecraft-188615
          - gcloud --quiet config set compute/zone us-west1-a
          - gcloud --quiet container clusters get-credentials statekube
          - ./kubectl set image deployment/openland-web-dev openland-web-dev=index.docker.io/openland/web:v${BITBUCKET_BUILD_NUMBER}
          - ./kubectl set image deployment/openland-web-next openland-web-next=index.docker.io/openland/web:v${BITBUCKET_BUILD_NUMBER}
          - ./kubectl rollout status deployments openland-web-next || true
    - step:
        name: Deploy to Production
        deployment: production
        trigger: manual
        script:
          - curl -o /tmp/google-cloud-sdk.tar.gz https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-200.0.0-linux-x86_64.tar.gz
          - tar -xvf /tmp/google-cloud-sdk.tar.gz -C /tmp/
          - /tmp/google-cloud-sdk/install.sh -q
          - source /tmp/google-cloud-sdk/path.bash.inc
          - gcloud -v
          - curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
          - chmod +x ./kubectl
          - echo $GCLOUD_API_KEYFILE | base64 --decode --ignore-garbage > ./gcloud-api-key.json
          - gcloud auth activate-service-account --key-file gcloud-api-key.json
          - gcloud --quiet config set project statecraft-188615
          - gcloud --quiet config set compute/zone us-west1-a
          - gcloud --quiet container clusters get-credentials statekube
          - ./kubectl set image deployment/openland-web app=index.docker.io/openland/web:v${BITBUCKET_BUILD_NUMBER}
          - ./kubectl rollout status deployments openland-web || true

options:
  docker: true
