image: node:8.9.4

pipelines:
  default:
    - step:
        name: Test & Build
        caches:
          - node
        script:
          - yarn install
          - yarn test
          - yarn build
          - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
          - docker build -t openland/web:v${BITBUCKET_BUILD_NUMBER} .
          - docker push openland/web:v${BITBUCKET_BUILD_NUMBER}
    - step:
        name: Deploy to Staging
        deployment: staging
        script:
          - ./scripts/deploy_prepare.sh
          - ./scripts/deploy_staging.sh
    - step:
        name: Deploy to Production
        deployment: production
        trigger: manual
        script:
          - ./scripts/deploy_prepare.sh
          - ./scripts/deploy_production.sh

options:
  docker: true
