FROM node:10.16.3

RUN apt-get update \
    && apt-get install -y ffmpeg \
      --no-install-recommends \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app
ADD package.prod.json /app/package.json
ADD yarn.lock /app/yarn.lock
RUN yarn install
COPY build/video/ /app/
COPY utils/encoder-linux-amd64 /app/

EXPOSE 3000
ENV NODE_ENV=production
ARG release_id
ENV RELEASE_ID=$release_id

CMD [ "node", "./openland-video/server.js" ]