FROM node:8.9.4-alpine

RUN apk add --no-cache tini
ENTRYPOINT ["/sbin/tini", "--"]

ADD package.json /app/
COPY node_modules/ /app/node_modules/
COPY dist/ /app/

EXPOSE 3000
WORKDIR /app
ENV NODE_ENV=production
CMD [ "node", "server.js" ]