version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.9.4
    working_directory: ~/repo
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - restore_cache:
          keys:
            - node-modules-{{ .Branch }}
      - run: yarn install
      - run: yarn test
      - run: yarn build
      - save_cache:
          key: node-modules-{{ .Branch }}
          paths:
            - "node_modules"