// source: https://github.com/datasets/country-codes/blob/master/data/country-codes.csv
export const countriesMeta = [
    { value: "+93", shortname: "AF", label: "Afghanistan" },
    { value: "+355", shortname: "AL", label: "Albania" },
    { value: "+213", shortname: "DZ", label: "Algeria" },
    { value: "+1684", shortname: "AS", label: "American Samoa" },
    { value: "+376", shortname: "AD", label: "Andorra" },
    { value: "+244", shortname: "AO", label: "Angola" },
    { value: "+1264", shortname: "AI", label: "Anguilla" },
    { value: "+672", shortname: "AQ", label: "Antarctica" },
    { value: "+1268", shortname: "AG", label: "Antigua & Barbuda" },
    { value: "+54", shortname: "AR", label: "Argentina" },
    { value: "+374", shortname: "AM", label: "Armenia" },
    { value: "+297", shortname: "AW", label: "Aruba" },
    { value: "+61", shortname: "AU", label: "Australia" },
    { value: "+43", shortname: "AT", label: "Austria" },
    { value: "+994", shortname: "AZ", label: "Azerbaijan" },
    { value: "+1242", shortname: "BS", label: "Bahamas" },
    { value: "+973", shortname: "BH", label: "Bahrain" },
    { value: "+880", shortname: "BD", label: "Bangladesh" },
    { value: "+1246", shortname: "BB", label: "Barbados" },
    { value: "+375", shortname: "BY", label: "Belarus" },
    { value: "+32", shortname: "BE", label: "Belgium" },
    { value: "+501", shortname: "BZ", label: "Belize" },
    { value: "+229", shortname: "BJ", label: "Benin" },
    { value: "+1441", shortname: "BM", label: "Bermuda" },
    { value: "+975", shortname: "BT", label: "Bhutan" },
    { value: "+591", shortname: "BO", label: "Bolivia" },
    { value: "+387", shortname: "BA", label: "Bosnia" },
    { value: "+267", shortname: "BW", label: "Botswana" },
    { value: "+47", shortname: "BV", label: "Bouvet Island" },
    { value: "+55", shortname: "BR", label: "Brazil" },
    { value: "+246", shortname: "IO", label: "British Indian Ocean Territory" },
    { value: "+1284", shortname: "VG", label: "British Virgin Islands" },
    { value: "+673", shortname: "BN", label: "Brunei" },
    { value: "+359", shortname: "BG", label: "Bulgaria" },
    { value: "+226", shortname: "BF", label: "Burkina Faso" },
    { value: "+257", shortname: "BI", label: "Burundi" },
    { value: "+855", shortname: "KH", label: "Cambodia" },
    { value: "+237", shortname: "CM", label: "Cameroon" },
    { value: "+1", shortname: "CA", label: "Canada" },
    { value: "+238", shortname: "CV", label: "Cape Verde" },
    { value: "+599", shortname: "BQ", label: "Caribbean Netherlands" },
    { value: "+1345", shortname: "KY", label: "Cayman Islands" },
    { value: "+236", shortname: "CF", label: "Central African Republic" },
    { value: "+235", shortname: "TD", label: "Chad" },
    { value: "+56", shortname: "CL", label: "Chile" },
    { value: "+86", shortname: "CN", label: "China" },
    { value: "+61", shortname: "CX", label: "Christmas Island" },
    { value: "+61", shortname: "CC", label: "Cocos (Keeling) Islands" },
    { value: "+57", shortname: "CO", label: "Colombia" },
    { value: "+269", shortname: "KM", label: "Comoros" },
    { value: "+242", shortname: "CG", label: "Congo - Brazzaville" },
    { value: "+243", shortname: "CD", label: "Congo - Kinshasa" },
    { value: "+682", shortname: "CK", label: "Cook Islands" },
    { value: "+506", shortname: "CR", label: "Costa Rica" },
    { value: "+385", shortname: "HR", label: "Croatia" },
    { value: "+53", shortname: "CU", label: "Cuba" },
    { value: "+599", shortname: "CW", label: "Curaçao" },
    { value: "+357", shortname: "CY", label: "Cyprus" },
    { value: "+420", shortname: "CZ", label: "Czechia" },
    { value: "+225", shortname: "CI", label: "Côte d’Ivoire" },
    { value: "+45", shortname: "DK", label: "Denmark" },
    { value: "+253", shortname: "DJ", label: "Djibouti" },
    { value: "+1767", shortname: "DM", label: "Dominica" },
    { value: "+1809", shortname: "DO", label: "Dominican Republic" },
    { value: "+1829", shortname: "DO", label: "Dominican Republic" },
    { value: "+1849", shortname: "DO", label: "Dominican Republic" },
    { value: "+593", shortname: "EC", label: "Ecuador" },
    { value: "+20", shortname: "EG", label: "Egypt" },
    { value: "+503", shortname: "SV", label: "El Salvador" },
    { value: "+240", shortname: "GQ", label: "Equatorial Guinea" },
    { value: "+291", shortname: "ER", label: "Eritrea" },
    { value: "+372", shortname: "EE", label: "Estonia" },
    { value: "+268", shortname: "SZ", label: "Eswatini" },
    { value: "+251", shortname: "ET", label: "Ethiopia" },
    { value: "+500", shortname: "FK", label: "Falkland Islands" },
    { value: "+298", shortname: "FO", label: "Faroe Islands" },
    { value: "+679", shortname: "FJ", label: "Fiji" },
    { value: "+358", shortname: "FI", label: "Finland" },
    { value: "+33", shortname: "FR", label: "France" },
    { value: "+594", shortname: "GF", label: "French Guiana" },
    { value: "+689", shortname: "PF", label: "French Polynesia" },
    { value: "+262", shortname: "TF", label: "French Southern Territories" },
    { value: "+241", shortname: "GA", label: "Gabon" },
    { value: "+220", shortname: "GM", label: "Gambia" },
    { value: "+995", shortname: "GE", label: "Georgia" },
    { value: "+49", shortname: "DE", label: "Germany" },
    { value: "+233", shortname: "GH", label: "Ghana" },
    { value: "+350", shortname: "GI", label: "Gibraltar" },
    { value: "+30", shortname: "GR", label: "Greece" },
    { value: "+299", shortname: "GL", label: "Greenland" },
    { value: "+1473", shortname: "GD", label: "Grenada" },
    { value: "+590", shortname: "GP", label: "Guadeloupe" },
    { value: "+1671", shortname: "GU", label: "Guam" },
    { value: "+502", shortname: "GT", label: "Guatemala" },
    { value: "+44", shortname: "GG", label: "Guernsey" },
    { value: "+224", shortname: "GN", label: "Guinea" },
    { value: "+245", shortname: "GW", label: "Guinea-Bissau" },
    { value: "+592", shortname: "GY", label: "Guyana" },
    { value: "+509", shortname: "HT", label: "Haiti" },
    { value: "+672", shortname: "HM", label: "Heard & McDonald Islands" },
    { value: "+504", shortname: "HN", label: "Honduras" },
    { value: "+852", shortname: "HK", label: "Hong Kong" },
    { value: "+36", shortname: "HU", label: "Hungary" },
    { value: "+354", shortname: "IS", label: "Iceland" },
    { value: "+91", shortname: "IN", label: "India" },
    { value: "+62", shortname: "ID", label: "Indonesia" },
    { value: "+98", shortname: "IR", label: "Iran" },
    { value: "+964", shortname: "IQ", label: "Iraq" },
    { value: "+353", shortname: "IE", label: "Ireland" },
    { value: "+44", shortname: "IM", label: "Isle of Man" },
    { value: "+972", shortname: "IL", label: "Israel" },
    { value: "+39", shortname: "IT", label: "Italy" },
    { value: "+1876", shortname: "JM", label: "Jamaica" },
    { value: "+81", shortname: "JP", label: "Japan" },
    { value: "+44", shortname: "JE", label: "Jersey" },
    { value: "+962", shortname: "JO", label: "Jordan" },
    { value: "+7", shortname: "KZ", label: "Kazakhstan" },
    { value: "+254", shortname: "KE", label: "Kenya" },
    { value: "+686", shortname: "KI", label: "Kiribati" },
    { value: "+965", shortname: "KW", label: "Kuwait" },
    { value: "+996", shortname: "KG", label: "Kyrgyzstan" },
    { value: "+856", shortname: "LA", label: "Laos" },
    { value: "+371", shortname: "LV", label: "Latvia" },
    { value: "+961", shortname: "LB", label: "Lebanon" },
    { value: "+266", shortname: "LS", label: "Lesotho" },
    { value: "+231", shortname: "LR", label: "Liberia" },
    { value: "+218", shortname: "LY", label: "Libya" },
    { value: "+423", shortname: "LI", label: "Liechtenstein" },
    { value: "+370", shortname: "LT", label: "Lithuania" },
    { value: "+352", shortname: "LU", label: "Luxembourg" },
    { value: "+853", shortname: "MO", label: "Macau" },
    { value: "+261", shortname: "MG", label: "Madagascar" },
    { value: "+265", shortname: "MW", label: "Malawi" },
    { value: "+60", shortname: "MY", label: "Malaysia" },
    { value: "+960", shortname: "MV", label: "Maldives" },
    { value: "+223", shortname: "ML", label: "Mali" },
    { value: "+356", shortname: "MT", label: "Malta" },
    { value: "+692", shortname: "MH", label: "Marshall Islands" },
    { value: "+596", shortname: "MQ", label: "Martinique" },
    { value: "+222", shortname: "MR", label: "Mauritania" },
    { value: "+230", shortname: "MU", label: "Mauritius" },
    { value: "+262", shortname: "YT", label: "Mayotte" },
    { value: "+52", shortname: "MX", label: "Mexico" },
    { value: "+691", shortname: "FM", label: "Micronesia" },
    { value: "+373", shortname: "MD", label: "Moldova" },
    { value: "+377", shortname: "MC", label: "Monaco" },
    { value: "+976", shortname: "MN", label: "Mongolia" },
    { value: "+382", shortname: "ME", label: "Montenegro" },
    { value: "+1664", shortname: "MS", label: "Montserrat" },
    { value: "+212", shortname: "MA", label: "Morocco" },
    { value: "+258", shortname: "MZ", label: "Mozambique" },
    { value: "+95", shortname: "MM", label: "Myanmar" },
    { value: "+264", shortname: "NA", label: "Namibia" },
    { value: "+674", shortname: "NR", label: "Nauru" },
    { value: "+977", shortname: "NP", label: "Nepal" },
    { value: "+31", shortname: "NL", label: "Netherlands" },
    { value: "+687", shortname: "NC", label: "New Caledonia" },
    { value: "+64", shortname: "NZ", label: "New Zealand" },
    { value: "+505", shortname: "NI", label: "Nicaragua" },
    { value: "+227", shortname: "NE", label: "Niger" },
    { value: "+234", shortname: "NG", label: "Nigeria" },
    { value: "+683", shortname: "NU", label: "Niue" },
    { value: "+672", shortname: "NF", label: "Norfolk Island" },
    { value: "+850", shortname: "KP", label: "North Korea" },
    { value: "+389", shortname: "MK", label: "North Macedonia" },
    { value: "+1670", shortname: "MP", label: "Northern Mariana Islands" },
    { value: "+47", shortname: "NO", label: "Norway" },
    { value: "+968", shortname: "OM", label: "Oman" },
    { value: "+92", shortname: "PK", label: "Pakistan" },
    { value: "+680", shortname: "PW", label: "Palau" },
    { value: "+970", shortname: "PS", label: "Palestine" },
    { value: "+507", shortname: "PA", label: "Panama" },
    { value: "+675", shortname: "PG", label: "Papua New Guinea" },
    { value: "+595", shortname: "PY", label: "Paraguay" },
    { value: "+51", shortname: "PE", label: "Peru" },
    { value: "+63", shortname: "PH", label: "Philippines" },
    { value: "+870", shortname: "PN", label: "Pitcairn Islands" },
    { value: "+48", shortname: "PL", label: "Poland" },
    { value: "+351", shortname: "PT", label: "Portugal" },
    { value: "+1", shortname: "PR", label: "Puerto Rico" },
    { value: "+974", shortname: "QA", label: "Qatar" },
    { value: "+40", shortname: "RO", label: "Romania" },
    { value: "+7", shortname: "RU", label: "Russia" },
    { value: "+250", shortname: "RW", label: "Rwanda" },
    { value: "+262", shortname: "RE", label: "Réunion" },
    { value: "+685", shortname: "WS", label: "Samoa" },
    { value: "+378", shortname: "SM", label: "San Marino" },
    { value: "+966", shortname: "SA", label: "Saudi Arabia" },
    { value: "+221", shortname: "SN", label: "Senegal" },
    { value: "+381", shortname: "RS", label: "Serbia" },
    { value: "+248", shortname: "SC", label: "Seychelles" },
    { value: "+232", shortname: "SL", label: "Sierra Leone" },
    { value: "+65", shortname: "SG", label: "Singapore" },
    { value: "+1721", shortname: "SX", label: "Sint Maarten" },
    { value: "+421", shortname: "SK", label: "Slovakia" },
    { value: "+386", shortname: "SI", label: "Slovenia" },
    { value: "+677", shortname: "SB", label: "Solomon Islands" },
    { value: "+252", shortname: "SO", label: "Somalia" },
    { value: "+27", shortname: "ZA", label: "South Africa" },
    {
        value: "+500",
        shortname: "GS",
        label: "South Georgia & South Sandwich Islands",
    },
    { value: "+82", shortname: "KR", label: "South Korea" },
    { value: "+211", shortname: "SS", label: "South Sudan" },
    { value: "+34", shortname: "ES", label: "Spain" },
    { value: "+94", shortname: "LK", label: "Sri Lanka" },
    { value: "+590", shortname: "BL", label: "St. Barthélemy" },
    { value: "+290", shortname: "SH", label: "St. Helena" },
    { value: "+1869", shortname: "KN", label: "St. Kitts & Nevis" },
    { value: "+1758", shortname: "LC", label: "St. Lucia" },
    { value: "+590", shortname: "MF", label: "St. Martin" },
    { value: "+508", shortname: "PM", label: "St. Pierre & Miquelon" },
    { value: "+1784", shortname: "VC", label: "St. Vincent & Grenadines" },
    { value: "+249", shortname: "SD", label: "Sudan" },
    { value: "+597", shortname: "SR", label: "Suriname" },
    { value: "+47", shortname: "SJ", label: "Svalbard & Jan Mayen" },
    { value: "+46", shortname: "SE", label: "Sweden" },
    { value: "+41", shortname: "CH", label: "Switzerland" },
    { value: "+963", shortname: "SY", label: "Syria" },
    { value: "+239", shortname: "ST", label: "São Tomé & Príncipe" },
    { value: "+886", shortname: "TW", label: "Taiwan" },
    { value: "+992", shortname: "TJ", label: "Tajikistan" },
    { value: "+255", shortname: "TZ", label: "Tanzania" },
    { value: "+66", shortname: "TH", label: "Thailand" },
    { value: "+670", shortname: "TL", label: "Timor-Leste" },
    { value: "+228", shortname: "TG", label: "Togo" },
    { value: "+690", shortname: "TK", label: "Tokelau" },
    { value: "+676", shortname: "TO", label: "Tonga" },
    { value: "+1868", shortname: "TT", label: "Trinidad & Tobago" },
    { value: "+216", shortname: "TN", label: "Tunisia" },
    { value: "+90", shortname: "TR", label: "Turkey" },
    { value: "+993", shortname: "TM", label: "Turkmenistan" },
    { value: "+1649", shortname: "TC", label: "Turks & Caicos Islands" },
    { value: "+688", shortname: "TV", label: "Tuvalu" },
    { value: "+1340", shortname: "VI", label: "U.S. Virgin Islands" },
    { value: "+44", shortname: "GB", label: "United Kingdom" },
    { value: "+1", shortname: "US", label: "United States" },
    { value: "+256", shortname: "UG", label: "Uganda" },
    { value: "+380", shortname: "UA", label: "Ukraine" },
    { value: "+971", shortname: "AE", label: "United Arab Emirates" },
    { value: "+598", shortname: "UY", label: "Uruguay" },
    { value: "+998", shortname: "UZ", label: "Uzbekistan" },
    { value: "+678", shortname: "VU", label: "Vanuatu" },
    { value: "+3906", shortname: "VA", label: "Vatican City" },
    { value: "+58", shortname: "VE", label: "Venezuela" },
    { value: "+84", shortname: "VN", label: "Vietnam" },
    { value: "+681", shortname: "WF", label: "Wallis & Futuna" },
    { value: "+212", shortname: "EH", label: "Western Sahara" },
    { value: "+967", shortname: "YE", label: "Yemen" },
    { value: "+260", shortname: "ZM", label: "Zambia" },
    { value: "+263", shortname: "ZW", label: "Zimbabwe" },
    { value: "+358", shortname: "AX", label: "Åland Islands" },
];
