// WARNING! THIS IS AUTOGENERATED FILE. DO NOT EDIT!
import * as Account from './queries/Account';
import * as Types from './Types';
import { typedQuery } from 'openland-x-graphql/typed';

export const AccountInvitesQuery = typedQuery<Types.AccountInvitesQuery, {}>(Account.AccountInvitesQuery);