// WARNING! THIS IS AUTOGENERATED FILE. DO NOT EDIT!
import * as Account from './queries/Account';
import * as Types from './Types';
import { typedQuery } from 'openland-y-graphql/typed';

export const AccountInvitesHistoryQuery = typedQuery<Types.AccountInvitesHistory, {}>(Account.AccountInvitesHistoryQuery);