// WARNING! THIS IS AUTOGENERATED FILE. DO NOT EDIT!
import * as Deals from './queries/Deals';
import * as Types from './Types';
import { typedMutation } from 'openland-y-graphql/typed';

export const AddDealMutation = typedMutation<Types.AddDeal, Types.AddDealVariables>(Deals.AddDealMutation);