// WARNING! THIS IS AUTOGENERATED FILE. DO NOT EDIT!
import * as Deals from './queries/Deals';
import * as Types from './Types';
import { typedMutation } from 'openland-x-graphql/typed';

export const AddDealMutation = typedMutation<Types.AddDealMutation, Types.AddDealMutationVariables>(Deals.AddDealMutation);