// WARNING! THIS IS AUTOGENERATED FILE. DO NOT EDIT!
import * as Folder from './queries/Folder';
import * as Types from './Types';
import { typedMutation } from 'openland-x-graphql/typed';

export const AddToFolderFromSearchMutation = typedMutation<Types.AddToFolderFromSearchMutation, Types.AddToFolderFromSearchMutationVariables>(Folder.AddToFolderFromSearchMutation);