// WARNING! THIS IS AUTOGENERATED FILE. DO NOT EDIT!
import * as Chats from './queries/Chats';
import * as Types from './Types';
import { typedQuery } from 'openland-x-graphql/typed';

export const AllChatsQuery = typedQuery<Types.AllChatsQuery, {}>(Chats.AllChatsQuery);