// WARNING! THIS IS AUTOGENERATED FILE. DO NOT EDIT!
import * as Deals from './queries/Deals';
import * as Types from './Types';
import { typedMutation } from 'openland-y-graphql/typed';

export const AlterDealMutation = typedMutation<Types.AlterDeal, Types.AlterDealVariables>(Deals.AlterDealMutation);