// WARNING! THIS IS AUTOGENERATED FILE. DO NOT EDIT!
import * as Explore from './queries/Explore';
import * as Types from './Types';
import { typedQuery } from 'openland-y-graphql/typed';

export const AvailableRoomsQuery = typedQuery<Types.AvailableRooms, {}>(Explore.AvailableRoomsQuery);