// WARNING! THIS IS AUTOGENERATED FILE. DO NOT EDIT!
import * as Chats from './queries/Chats';
import * as Types from './Types';
import { typedMutation } from 'openland-y-graphql/typed';

export const BlockUserMutation = typedMutation<Types.BlockUserMutation, Types.BlockUserMutationVariables>(Chats.BlockUserMutation);