// WARNING! THIS IS AUTOGENERATED FILE. DO NOT EDIT!
import * as Chats from './queries/Chats';
import * as Types from './Types';
import { typedQuery } from 'openland-y-graphql/typed';

export const BlockedListQuery = typedQuery<Types.BlockedListQuery, Types.BlockedListQueryVariables>(Chats.BlockedListQuery);