// WARNING! THIS IS AUTOGENERATED FILE. DO NOT EDIT!
import * as Chats from './queries/Chats';
import * as Types from './Types';
import { typedMutation } from 'openland-y-graphql/typed';

export const ChatLeaveMutation = typedMutation<Types.ChatLeave, Types.ChatLeaveVariables>(Chats.ChatLeaveMutation);