// WARNING! THIS IS AUTOGENERATED FILE. DO NOT EDIT!
import * as Chats from './queries/Chats';
import * as Types from './Types';
import { typedMutation } from 'openland-y-graphql/typed';

export const ChatDeleteMessageMutation = typedMutation<Types.ChatDeleteMessageMutation, Types.ChatDeleteMessageMutationVariables>(Chats.ChatDeleteMessageMutation);