// WARNING! THIS IS AUTOGENERATED FILE. DO NOT EDIT!
import * as Conferences from './queries/Conferences';
import * as Types from './Types';
import { typedQuery } from 'openland-y-graphql/typed';

export const ConferenceQuery = typedQuery<Types.Conference, Types.ConferenceVariables>(Conferences.ConferenceQuery);