// WARNING! THIS IS AUTOGENERATED FILE. DO NOT EDIT!
import * as Conferences from './queries/Conferences';
import * as Types from './Types';
import { typedMutation } from 'openland-y-graphql/typed';

export const ConferenceCandidateMutation = typedMutation<Types.ConferenceCandidate, Types.ConferenceCandidateVariables>(Conferences.ConferenceCandidateMutation);