// WARNING! THIS IS AUTOGENERATED FILE. DO NOT EDIT!
import * as Addressing from './queries/Addressing';
import * as Types from './Types';
import { typedQuery } from 'openland-y-graphql/typed';

export const CountyQuery = typedQuery<Types.County, Types.CountyVariables>(Addressing.CountyQuery);