// WARNING! THIS IS AUTOGENERATED FILE. DO NOT EDIT!
import * as Addressing from './queries/Addressing';
import * as Types from './Types';
import { typedQuery } from 'openland-x-graphql/typed';

export const CountyQuery = typedQuery<Types.CountyQuery, Types.CountyQueryVariables>(Addressing.CountyQuery);