// WARNING! THIS IS AUTOGENERATED FILE. DO NOT EDIT!
import * as Account from './queries/Account';
import * as Types from './Types';
import { typedMutation } from 'openland-x-graphql/typed';

export const CreateUserProfileAndOrganizationMutation = typedMutation<Types.CreateUserProfileAndOrganizationMutation, Types.CreateUserProfileAndOrganizationMutationVariables>(Account.CreateUserProfileAndOrganizationMutation);