// WARNING! THIS IS AUTOGENERATED FILE. DO NOT EDIT!
import * as Folder from './queries/Folder';
import * as Types from './Types';
import { typedMutation } from 'openland-y-graphql/typed';

export const CreateFolderMutation = typedMutation<Types.CreateFolder, Types.CreateFolderVariables>(Folder.CreateFolderMutation);