// WARNING! THIS IS AUTOGENERATED FILE. DO NOT EDIT!
import * as Account from './queries/Account';
import * as Types from './Types';
import { typedMutation } from 'openland-x-graphql/typed';

export const CreateOrganizationMutation = typedMutation<Types.CreateOrganizationMutation, Types.CreateOrganizationMutationVariables>(Account.CreateOrganizationMutation);