// WARNING! THIS IS AUTOGENERATED FILE. DO NOT EDIT!
import * as Deals from './queries/Deals';
import * as Types from './Types';
import { typedQuery } from 'openland-y-graphql/typed';

export const DealQuery = typedQuery<Types.Deal, Types.DealVariables>(Deals.DealQuery);