// WARNING! THIS IS AUTOGENERATED FILE. DO NOT EDIT!
import * as Debug from './queries/Debug';
import * as Types from './Types';
import { typedQuery } from 'openland-x-graphql/typed';

export const DebugReadedStatesQuery = typedQuery<Types.DebugReadedStatesQuery, {}>(Debug.DebugReadedStatesQuery);