// WARNING! THIS IS AUTOGENERATED FILE. DO NOT EDIT!
import * as Debug from './queries/Debug';
import * as Types from './Types';
import { typedMutation } from 'openland-y-graphql/typed';

export const DebugSendWelcomeEmailMutation = typedMutation<Types.DebugSendWelcomeEmail, {}>(Debug.DebugSendWelcomeEmailMutation);