// WARNING! THIS IS AUTOGENERATED FILE. DO NOT EDIT!
import * as Folder from './queries/Folder';
import * as Types from './Types';
import { typedMutation } from 'openland-x-graphql/typed';

export const DeleteFolderMutation = typedMutation<Types.DeleteFolderMutation, Types.DeleteFolderMutationVariables>(Folder.DeleteFolderMutation);