// WARNING! THIS IS AUTOGENERATED FILE. DO NOT EDIT!
import * as Folder from './queries/Folder';
import * as Types from './Types';
import { typedMutation } from 'openland-y-graphql/typed';

export const DeleteFolderMutation = typedMutation<Types.DeleteFolder, Types.DeleteFolderVariables>(Folder.DeleteFolderMutation);