// WARNING! THIS IS AUTOGENERATED FILE. DO NOT EDIT!
import * as Organization from './queries/Organization';
import * as Types from './Types';
import { typedMutation } from 'openland-y-graphql/typed';

export const DeleteListingMutation = typedMutation<Types.DeleteListing, Types.DeleteListingVariables>(Organization.DeleteListingMutation);