// WARNING! THIS IS AUTOGENERATED FILE. DO NOT EDIT!
import * as User from './queries/User';
import * as Types from './Types';
import { typedQuery } from 'openland-y-graphql/typed';

export const ExplorePeopleQuery = typedQuery<Types.ExplorePeople, Types.ExplorePeopleVariables>(User.ExplorePeopleQuery);