// WARNING! THIS IS AUTOGENERATED FILE. DO NOT EDIT!
import * as FeatureFlag from './queries/FeatureFlag';
import * as Types from './Types';
import { typedMutation } from 'openland-y-graphql/typed';

export const FeatureFlagDisableMutation = typedMutation<Types.FeatureFlagDisable, Types.FeatureFlagDisableVariables>(FeatureFlag.FeatureFlagDisableMutation);