// WARNING! THIS IS AUTOGENERATED FILE. DO NOT EDIT!
import * as FeatureFlag from './queries/FeatureFlag';
import * as Types from './Types';
import { typedMutation } from 'openland-x-graphql/typed';

export const FeatureFlagAddMutation = typedMutation<Types.FeatureFlagAddMutation, Types.FeatureFlagAddMutationVariables>(FeatureFlag.FeatureFlagAddMutation);