// WARNING! THIS IS AUTOGENERATED FILE. DO NOT EDIT!
import * as Feed from './queries/Feed';
import * as Types from './Types';
import { typedQuery } from 'openland-y-graphql/typed';

export const FeedHomeQuery = typedQuery<Types.FeedHome, {}>(Feed.FeedHomeQuery);