// WARNING! THIS IS AUTOGENERATED FILE. DO NOT EDIT!
import * as Folder from './queries/Folder';
import * as Types from './Types';
import { typedQuery } from 'openland-x-graphql/typed';

export const FolderQuery = typedQuery<Types.FolderQuery, Types.FolderQueryVariables>(Folder.FolderQuery);