// WARNING! THIS IS AUTOGENERATED FILE. DO NOT EDIT!
import * as Folder from './queries/Folder';
import * as Types from './Types';
import { typedQuery } from 'openland-y-graphql/typed';

export const FoldersQuery = typedQuery<Types.Folders, {}>(Folder.FoldersQuery);