// WARNING! THIS IS AUTOGENERATED FILE. DO NOT EDIT!
import * as Folder from './queries/Folder';
import * as Types from './Types';
import { typedQuery } from 'openland-y-graphql/typed';

export const FolderItemsTileOverlayQuery = typedQuery<Types.FolderItemsTileOverlay, Types.FolderItemsTileOverlayVariables>(Folder.FolderItemsTileOverlayQuery);