// WARNING! THIS IS AUTOGENERATED FILE. DO NOT EDIT!
import * as GroupRoom from './queries/GroupRoom';
import * as Types from './Types';
import { typedQuery } from 'openland-y-graphql/typed';

export const GroupRoomMembersInfoQuery = typedQuery<Types.GroupRoomMembersInfo, Types.GroupRoomMembersInfoVariables>(GroupRoom.GroupRoomMembersInfoQuery);