// WARNING! THIS IS AUTOGENERATED FILE. DO NOT EDIT!
import * as Organization from './queries/Organization';
import * as Types from './Types';
import { typedQuery } from 'openland-y-graphql/typed';

export const HitsPopularQuery = typedQuery<Types.HitsPopularQuery, Types.HitsPopularQueryVariables>(Organization.HitsPopularQuery);