import * as PermitsTyped from './queries/Permits.types';
import * as AccountTyped from './queries/Account.types';
import * as ParcelsTyped from './queries/Parcels.types';
import * as SearchTyped from './queries/Search.types';
import * as PermissionsTyped from './queries/Permissions.types';
import * as AddressingTyped from './queries/Addressing.types';
import * as DealsTyped from './queries/Deals.types';
import * as UserTyped from './queries/User.types';
import * as FeatureFlagsTyped from './queries/FeatureFlag.types';
import * as SourcingTyped from './queries/Sourcing.types';
import * as DebugTyped from './queries/Debug.types';
import * as SuperCityTyped from './queries/SuperCity.types';
import * as FolderTyped from './queries/Folder.types';
import * as TasksTyped from './queries/Tasks.types';
import * as OrganizationTyped from './queries/Organization.types';
import * as SettingsTyoped from './queries/Settings.types';

export let Permits = PermitsTyped;
export let Account = AccountTyped;
export let Parcels = ParcelsTyped;
export let Search = SearchTyped;
export let Addressing = AddressingTyped;
export let Deals = DealsTyped;
export let User = UserTyped;
export let FeatureFlags = FeatureFlagsTyped;
export let Permissions = PermissionsTyped;
export let Sourcing = SourcingTyped;
export let Debug = DebugTyped;
export let SuperCity = SuperCityTyped;
export let Folder = FolderTyped;
export let Tasks = TasksTyped;
export let Organization = OrganizationTyped;
export let Settings = SettingsTyoped;