// WARNING! THIS IS AUTOGENERATED FILE. DO NOT EDIT!
import * as App from './queries/App';
import * as Types from './Types';
import { typedQuery } from 'openland-y-graphql/typed';

export const MyAppsQuery = typedQuery<Types.MyApps, {}>(App.MyAppsQuery);