// WARNING! THIS IS AUTOGENERATED FILE. DO NOT EDIT!
import * as Sourcing from './queries/Sourcing';
import * as Types from './Types';
import { typedQuery } from 'openland-y-graphql/typed';

export const OpportunityTileOverlayQuery = typedQuery<Types.OpportunityTileOverlay, Types.OpportunityTileOverlayVariables>(Sourcing.OpportunityTileOverlayQuery);