// WARNING! THIS IS AUTOGENERATED FILE. DO NOT EDIT!
import * as Sourcing from './queries/Sourcing';
import * as Types from './Types';
import { typedQuery } from 'openland-x-graphql/typed';

export const OpportunityQuery = typedQuery<Types.OpportunityQuery, Types.OpportunityQueryVariables>(Sourcing.OpportunityQuery);