// WARNING! THIS IS AUTOGENERATED FILE. DO NOT EDIT!
import * as Organization from './queries/Organization';
import * as Types from './Types';
import { typedMutation } from 'openland-x-graphql/typed';

export const OrganizationRemoveMemberMutation = typedMutation<Types.OrganizationRemoveMemberMutation, Types.OrganizationRemoveMemberMutationVariables>(Organization.OrganizationRemoveMemberMutation);