// WARNING! THIS IS AUTOGENERATED FILE. DO NOT EDIT!
import * as Organization from './queries/Organization';
import * as Types from './Types';
import { typedQuery } from 'openland-x-graphql/typed';

export const OrganizationPublicInviteQuery = typedQuery<Types.OrganizationPublicInviteQuery, {}>(Organization.OrganizationPublicInviteQuery);