// WARNING! THIS IS AUTOGENERATED FILE. DO NOT EDIT!
import * as Organization from './queries/Organization';
import * as Types from './Types';
import { typedQuery } from 'openland-x-graphql/typed';

export const OrganizationProfileQuery = typedQuery<Types.OrganizationProfileQuery, Types.OrganizationProfileQueryVariables>(Organization.OrganizationProfileQuery);