// WARNING! THIS IS AUTOGENERATED FILE. DO NOT EDIT!
import * as Parcels from './queries/Parcels';
import * as Types from './Types';
import { typedMutation } from 'openland-y-graphql/typed';

export const ParcelNotesMutation = typedMutation<Types.ParcelNotes, Types.ParcelNotesVariables>(Parcels.ParcelNotesMutation);