// WARNING! THIS IS AUTOGENERATED FILE. DO NOT EDIT!
import * as Parcels from './queries/Parcels';
import * as Types from './Types';
import { typedQuery } from 'openland-x-graphql/typed';

export const ParcelsSearchQuery = typedQuery<Types.ParcelsSearchQuery, Types.ParcelsSearchQueryVariables>(Parcels.ParcelsSearchQuery);