// WARNING! THIS IS AUTOGENERATED FILE. DO NOT EDIT!
import * as Parcels from './queries/Parcels';
import * as Types from './Types';
import { typedQuery } from 'openland-y-graphql/typed';

export const ParcelsTileOverlayQuery = typedQuery<Types.ParcelsTileOverlay, Types.ParcelsTileOverlayVariables>(Parcels.ParcelsTileOverlayQuery);