// WARNING! THIS IS AUTOGENERATED FILE. DO NOT EDIT!
import * as Permits from './queries/Permits';
import * as Types from './Types';
import { typedQuery } from 'openland-x-graphql/typed';

export const PermitQuery = typedQuery<Types.PermitQuery, Types.PermitQueryVariables>(Permits.PermitQuery);