// WARNING! THIS IS AUTOGENERATED FILE. DO NOT EDIT!
import * as Permits from './queries/Permits';
import * as Types from './Types';
import { typedQuery } from 'openland-x-graphql/typed';

export const PermitsConnectionQuery = typedQuery<Types.PermitsConnectionQuery, Types.PermitsConnectionQueryVariables>(Permits.PermitsConnectionQuery);