// WARNING! THIS IS AUTOGENERATED FILE. DO NOT EDIT!
import * as Development from './queries/Development';
import * as Types from './Types';
import { typedQuery } from 'openland-y-graphql/typed';

export const PersonalTokensQuery = typedQuery<Types.PersonalTokens, {}>(Development.PersonalTokensQuery);