// WARNING! THIS IS AUTOGENERATED FILE. DO NOT EDIT!
import * as Track from './queries/Track';
import * as Types from './Types';
import { typedMutation } from 'openland-y-graphql/typed';

export const PersistEventsMutation = typedMutation<Types.PersistEvents, Types.PersistEventsVariables>(Track.PersistEventsMutation);