// WARNING! THIS IS AUTOGENERATED FILE. DO NOT EDIT!
import * as Settings from './queries/Settings';
import * as Types from './Types';
import { typedQuery } from 'openland-x-graphql/typed';

export const ProfileQuery = typedQuery<Types.ProfileQuery, {}>(Settings.ProfileQuery);