// WARNING! THIS IS AUTOGENERATED FILE. DO NOT EDIT!
import * as App from './queries/App';
import * as Types from './Types';
import { typedMutation } from 'openland-y-graphql/typed';

export const RefreshAppTokenMutation = typedMutation<Types.RefreshAppToken, Types.RefreshAppTokenVariables>(App.RefreshAppTokenMutation);