// WARNING! THIS IS AUTOGENERATED FILE. DO NOT EDIT!
import * as Deals from './queries/Deals';
import * as Types from './Types';
import { typedMutation } from 'openland-y-graphql/typed';

export const RemoveDealMutation = typedMutation<Types.RemoveDeal, Types.RemoveDealVariables>(Deals.RemoveDealMutation);