// WARNING! THIS IS AUTOGENERATED FILE. DO NOT EDIT!
import * as Account from './queries/Account';
import * as Types from './Types';
import { typedMutation } from 'openland-y-graphql/typed';

export const ReportOnlineMutation = typedMutation<Types.ReportOnline, Types.ReportOnlineVariables>(Account.ReportOnlineMutation);