// WARNING! THIS IS AUTOGENERATED FILE. DO NOT EDIT!
import * as Sourcing from './queries/Sourcing';
import * as Types from './Types';
import { typedMutation } from 'openland-y-graphql/typed';

export const ResetOpportunityMutation = typedMutation<Types.ResetOpportunity, Types.ResetOpportunityVariables>(Sourcing.ResetOpportunityMutation);