// WARNING! THIS IS AUTOGENERATED FILE. DO NOT EDIT!
import * as Chats from './queries/Chats';
import * as Types from './Types';
import { typedMutation } from 'openland-y-graphql/typed';

export const RoomEditIntroMutation = typedMutation<Types.RoomEditIntro, Types.RoomEditIntroVariables>(Chats.RoomEditIntroMutation);