// WARNING! THIS IS AUTOGENERATED FILE. DO NOT EDIT!
import * as Search from './queries/Search';
import * as Types from './Types';
import { typedQuery } from 'openland-y-graphql/typed';

export const SearchQuery = typedQuery<Types.Search, Types.SearchVariables>(Search.SearchQuery);