// WARNING! THIS IS AUTOGENERATED FILE. DO NOT EDIT!
import * as Search from './queries/Search';
import * as Types from './Types';
import { typedQuery } from 'openland-x-graphql/typed';

export const SearchQuery = typedQuery<Types.SearchQuery, Types.SearchQueryVariables>(Search.SearchQuery);