// WARNING! THIS IS AUTOGENERATED FILE. DO NOT EDIT!
import * as Settings from './queries/Settings';
import * as Types from './Types';
import { typedMutation } from 'openland-y-graphql/typed';

export const SettingsUpdateMutation = typedMutation<Types.SettingsUpdateMutation, Types.SettingsUpdateMutationVariables>(Settings.SettingsUpdateMutation);