// WARNING! THIS IS AUTOGENERATED FILE. DO NOT EDIT!
import * as Settings from './queries/Settings';
import * as Types from './Types';
import { typedQuery } from 'openland-y-graphql/typed';

export const SettingsQuery = typedQuery<Types.SettingsQuery, {}>(Settings.SettingsQuery);