// WARNING! THIS IS AUTOGENERATED FILE. DO NOT EDIT!
import * as Sourcing from './queries/Sourcing';
import * as Types from './Types';
import { typedQuery } from 'openland-x-graphql/typed';

export const SourcingAllReportQuery = typedQuery<Types.SourcingAllReportQuery, Types.SourcingAllReportQueryVariables>(Sourcing.SourcingAllReportQuery);