// WARNING! THIS IS AUTOGENERATED FILE. DO NOT EDIT!
import * as Permissions from './queries/Permissions';
import * as Types from './Types';
import { typedMutation } from 'openland-y-graphql/typed';

export const SuperAccountRenameMutation = typedMutation<Types.SuperAccountRenameMutation, Types.SuperAccountRenameMutationVariables>(Permissions.SuperAccountRenameMutation);