// WARNING! THIS IS AUTOGENERATED FILE. DO NOT EDIT!
import * as Permissions from './queries/Permissions';
import * as Types from './Types';
import { typedMutation } from 'openland-y-graphql/typed';

export const SuperAccountMemberRemoveMutation = typedMutation<Types.SuperAccountMemberRemove, Types.SuperAccountMemberRemoveVariables>(Permissions.SuperAccountMemberRemoveMutation);