// WARNING! THIS IS AUTOGENERATED FILE. DO NOT EDIT!
import * as SuperCity from './queries/SuperCity';
import * as Types from './Types';
import { typedQuery } from 'openland-x-graphql/typed';

export const SuperCitiesQuery = typedQuery<Types.SuperCitiesQuery, {}>(SuperCity.SuperCitiesQuery);