// WARNING! THIS IS AUTOGENERATED FILE. DO NOT EDIT!
import * as Permissions from './queries/Permissions';
import * as Types from './Types';
import { typedMutation } from 'openland-x-graphql/typed';

export const SuperAccountMemberAddMutation = typedMutation<Types.SuperAccountMemberAddMutation, Types.SuperAccountMemberAddMutationVariables>(Permissions.SuperAccountMemberAddMutation);