// WARNING! THIS IS AUTOGENERATED FILE. DO NOT EDIT!
import * as Permissions from './queries/Permissions';
import * as Types from './Types';
import { typedQuery } from 'openland-y-graphql/typed';

export const SuperChatsStatsQuery = typedQuery<Types.SuperChatsStatsQuery, Types.SuperChatsStatsQueryVariables>(Permissions.SuperChatsStatsQuery);