// WARNING! THIS IS AUTOGENERATED FILE. DO NOT EDIT!
import * as Permissions from './queries/Permissions';
import * as Types from './Types';
import { typedMutation } from 'openland-x-graphql/typed';

export const SuperAccountMemberRemoveMutation = typedMutation<Types.SuperAccountMemberRemoveMutation, Types.SuperAccountMemberRemoveMutationVariables>(Permissions.SuperAccountMemberRemoveMutation);