// WARNING! THIS IS AUTOGENERATED FILE. DO NOT EDIT!
import * as Organization from './queries/Organization';
import * as Types from './Types';
import { typedMutation } from 'openland-y-graphql/typed';

export const UpdateOrganizationMutation = typedMutation<Types.UpdateOrganization, Types.UpdateOrganizationVariables>(Organization.UpdateOrganizationMutation);