// WARNING! THIS IS AUTOGENERATED FILE. DO NOT EDIT!
import * as User from './queries/User';
import * as Types from './Types';
import { typedQuery } from 'openland-x-graphql/typed';

export const UsersQuery = typedQuery<Types.UsersQuery, Types.UsersQueryVariables>(User.UsersQuery);