use_frameworks!
platform :ios, '9.0'

target 'openland' do
  pod 'AppCenter/Crashes', '~> 1.12.0'
  pod 'AppCenter/Analytics', '~> 1.12.0'
  pod 'Texture'
  pod 'SwiftyJSON', '~> 4.0'
  pod 'Auth0', '~> 1.0'

  # Pods for AppCenter
  pod 'AppCenterReactNativeShared', '~> 1.11.0'
  pod 'A0Auth0', :path => '../node_modules/react-native-auth0'

end
