platform :ios, '11.0'
# require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
use_frameworks!

target 'openland' do

  pod 'FBLazyVector', :path => "../node_modules/react-native/Libraries/FBLazyVector"
  pod 'FBReactNativeSpec', :path => "../node_modules/react-native/Libraries/FBReactNativeSpec"
  pod 'RCTRequired', :path => "../node_modules/react-native/Libraries/RCTRequired"
  pod 'RCTTypeSafety', :path => "../node_modules/react-native/Libraries/TypeSafety"
  pod 'React', :path => '../node_modules/react-native/'
  pod 'React-Core', :path => '../node_modules/react-native/'
  pod 'React-CoreModules', :path => '../node_modules/react-native/React/CoreModules'
  pod 'React-Core/DevSupport', :path => '../node_modules/react-native/'
  pod 'React-RCTActionSheet', :path => '../node_modules/react-native/Libraries/ActionSheetIOS'
  pod 'React-RCTAnimation', :path => '../node_modules/react-native/Libraries/NativeAnimation'
  pod 'React-RCTBlob', :path => '../node_modules/react-native/Libraries/Blob'
  pod 'React-RCTImage', :path => '../node_modules/react-native/Libraries/Image'
  pod 'React-RCTLinking', :path => '../node_modules/react-native/Libraries/LinkingIOS'
  pod 'React-RCTNetwork', :path => '../node_modules/react-native/Libraries/Network'
  pod 'React-RCTSettings', :path => '../node_modules/react-native/Libraries/Settings'
  pod 'React-RCTText', :path => '../node_modules/react-native/Libraries/Text'
  pod 'React-RCTVibration', :path => '../node_modules/react-native/Libraries/Vibration'
  pod 'React-RCTPushNotification', :path => '../node_modules/react-native/Libraries/PushNotificationIOS'
  pod 'React-Core/RCTWebSocket', :path => '../node_modules/react-native/'
  pod 'React-cxxreact', :path => '../node_modules/react-native/ReactCommon/cxxreact'
  pod 'React-jsi', :path => '../node_modules/react-native/ReactCommon/jsi'
  pod 'React-jsiexecutor', :path => '../node_modules/react-native/ReactCommon/jsiexecutor'
  pod 'React-jsinspector', :path => '../node_modules/react-native/ReactCommon/jsinspector'
  pod 'ReactCommon/jscallinvoker', :path => "../node_modules/react-native/ReactCommon"
  pod 'QBImagePickerController', :path => '../node_modules/react-native-image-crop-picker/ios/QBImagePicker/QBImagePickerController.podspec'
  pod 'ReactCommon/turbomodule/core', :path => "../node_modules/react-native/ReactCommon"
  pod 'Yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'
    
  pod 'Texture', :git => 'https://github.com/openland/Texture.git', :branch => '2.7-fontfix'
  pod 'SwiftyJSON', '~> 4.0'
  pod 'Starscream', '~> 3.0.2'
  pod 'ReachabilitySwift'
  pod 'Stripe'

  pod 'AppCenter', '~> 1.14.0'
  pod 'AppCenter/Crashes', '~> 1.14.0'
  pod 'AppCenter/Analytics', '~> 1.14.0'
  pod 'AppCenterReactNativeShared', '~> 1.13.0'

  pod 'react-native-webrtc', :path => '../node_modules/react-native-webrtc'

  pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info'

  pod 'RNGoogleSignin', :path => '../node_modules/@react-native-community/google-signin'
  pod 'GoogleSignIn', '~> 5.0.0'

  pod 'react-native-blur', :path => '../node_modules/react-native-blur'

  pod 'RNFastImage', :path => '../node_modules/react-native-fast-image'

  pod 'RNImageCropPicker', :path => '../node_modules/react-native-image-crop-picker'

  pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'

  pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'


  pod 'RNShare', :path => '../node_modules/react-native-share'


  pod 'rn-fetch-blob', :path => '../node_modules/rn-fetch-blob'
  
  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'

  pod 'RCTRestart', :path => '../node_modules/react-native-restart/ios'
  
  pod 'RNRate', :path => '../node_modules/react-native-rate/ios'
  pod 'react-native-document-picker', :path => '../node_modules/react-native-document-picker'

  pod 'ReactNativeIncallManager', :path => '../node_modules/react-native-incall-manager'

  pod 'ReactNativePermissions', :path => '../node_modules/react-native-permissions'

  pod 'react-native-haptic-feedback', :path => '../node_modules/react-native-haptic-feedback'

  pod 'react-native-sqlite-storage', :path => '../node_modules/react-native-sqlite-storage'

  pod 'react-native-background-timer', :path => '../node_modules/react-native-background-timer'

  pod 'react-native-pdf', :path => '../node_modules/react-native-pdf'
  pod 'ObjectiveRocks', '~> 0.9'
  pod 'react-native-video', :path => '../node_modules/react-native-video/react-native-video.podspec'
  pod 'ReactNativeDarkMode', :path => '../node_modules/react-native-dark-mode'

  pod 'react-native-cameraroll', :path => '../node_modules/@react-native-community/cameraroll'

  pod 'react-native-version-number', :path => '../node_modules/react-native-version-number'

  pod 'react-native-mapbox-gl', :path => '../node_modules/@react-native-mapbox-gl/maps'

  pod 'react-native-location', :path => '../node_modules/react-native-location'
  
  pod 'lottie-react-native', :path => '../node_modules/lottie-react-native'
  pod 'react-native-fast-animations', :path => '../node_modules/react-native-fast-animations'

end

target 'openlandTests' do
    pod 'SwiftyJSON', '~> 4.0'
    pod 'ObjectiveRocks', '~> 0.9'
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['ENABLE_BITCODE'] = 'NO'
            config.build_settings['SWIFT_VERSION'] = '4.2'
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
        end
    end
end
