/* tslint:disable */
//  This file was automatically generated and should not be edited.

export interface GeoBox {
  east: number,
  north: number,
  west: number,
  south: number,
};

export enum PermitStatus {
  FILING = "FILING",
  FILED = "FILED",
  ISSUED = "ISSUED",
  COMPLETED = "COMPLETED",
  EXPIRED = "EXPIRED",
  CANCELLED = "CANCELLED",
  DISAPPROVED = "DISAPPROVED",
  APPROVED = "APPROVED",
  ISSUING = "ISSUING",
  REVOKED = "REVOKED",
  WITHDRAWN = "WITHDRAWN",
  PLANCHECK = "PLANCHECK",
  SUSPENDED = "SUSPENDED",
  REINSTATED = "REINSTATED",
  INSPECTING = "INSPECTING",
  UPHELD = "UPHELD",
  INCOMPLETE = "INCOMPLETE",
  GRANTED = "GRANTED",
  APPEAL = "APPEAL",
}


export enum PermitType {
  NEW_CONSTRUCTION = "NEW_CONSTRUCTION",
  ADDITIONS_ALTERATIONS_REPARE = "ADDITIONS_ALTERATIONS_REPARE",
  OTC_ADDITIONS = "OTC_ADDITIONS",
  WALL_OR_PAINTED_SIGN = "WALL_OR_PAINTED_SIGN",
  SIGN_ERRECT = "SIGN_ERRECT",
  DEMOLITIONS = "DEMOLITIONS",
  GRADE_QUARRY_FILL_EXCAVATE = "GRADE_QUARRY_FILL_EXCAVATE",
}


export enum PermitSorting {
  STATUS_CHANGE_TIME = "STATUS_CHANGE_TIME",
  CREATE_TIME = "CREATE_TIME",
  COMPLETE_TIME = "COMPLETE_TIME",
  ISSUED_TIME = "ISSUED_TIME",
  APPROVAL_TIME_ASC = "APPROVAL_TIME_ASC",
  APPROVAL_TIME_DESC = "APPROVAL_TIME_DESC",
}


export interface AccountQuery {
  me:  {
    __typename: "User",
    id: string,
    name: string,
    firstName: string,
    lastName: string,
    picture: string,
  } | null,
};

export interface AreaQueryVariables {
  areaId: string,
};

export interface AreaQuery {
  area:  {
    __typename: "Area",
    id: string,
    slug: string,
    writeAccess: boolean,
  },
  me:  {
    __typename: "User",
    id: string,
    name: string,
    firstName: string,
    lastName: string,
    picture: string,
  } | null,
};

export interface AreaStatsQueryVariables {
  areaId: string,
};

export interface AreaStatsQuery {
  area:  {
    __typename: "Area",
    id: string,
    slug: string,
    stats:  {
      __typename: "AreaStats",
      totalProjects: number,
      totalProjectsVerified: number,
      totalDevelopers: number,
      totalConstructors: number,
      totalOrganizations: number,
      totalPermits: number,
      year2017NewUnits: number,
      year2017NewUnitsVerified: number,
      year2018NewUnits: number,
      year2018NewUnitsVerified: number,
      fastestApprovalProject:  {
        __typename: "BuildingProject",
        id: string,
        slug: string,
        name: string,
        approvalTime: number | null,
        preview:  {
          __typename: "Picture",
          url: string,
          retina: string,
        } | null,
      },
      slowestApprovalProject:  {
        __typename: "BuildingProject",
        id: string,
        slug: string,
        name: string,
        approvalTime: number | null,
        preview:  {
          __typename: "Picture",
          url: string,
          retina: string,
        } | null,
      },
    },
  },
  permitsUnitsFiledStats:  {
    __typename: "Chart",
    labels: Array< string >,
    datasets:  Array< {
      __typename: "ChartDataSet",
      label: string,
      values: Array< number >,
    } >,
  },
  permitsUnitsIssuedStats:  {
    __typename: "Chart",
    labels: Array< string >,
    datasets:  Array< {
      __typename: "ChartDataSet",
      label: string,
      values: Array< number >,
    } >,
  },
  permitsUnitsCompletedStats:  {
    __typename: "Chart",
    labels: Array< string >,
    datasets:  Array< {
      __typename: "ChartDataSet",
      label: string,
      values: Array< number >,
    } >,
  },
  permitsUnitsFiledStatsMonthly:  {
    __typename: "Chart",
    labels: Array< string >,
    datasets:  Array< {
      __typename: "ChartDataSet",
      label: string,
      values: Array< number >,
    } >,
  },
};

export interface InternalStatsQuery {
  permitsApprovalStats:  {
    __typename: "Chart",
    labels: Array< string >,
    datasets:  Array< {
      __typename: "ChartDataSet",
      label: string,
      values: Array< number >,
    } >,
  },
  permitsApprovalUnits:  {
    __typename: "Chart",
    labels: Array< string >,
    datasets:  Array< {
      __typename: "ChartDataSet",
      label: string,
      values: Array< number >,
    } >,
  },
  permitsUnitsFiledStats:  {
    __typename: "Chart",
    labels: Array< string >,
    datasets:  Array< {
      __typename: "ChartDataSet",
      label: string,
      values: Array< number >,
    } >,
  },
  permitsUnitsIssuedStats:  {
    __typename: "Chart",
    labels: Array< string >,
    datasets:  Array< {
      __typename: "ChartDataSet",
      label: string,
      values: Array< number >,
    } >,
  },
  permitsUnitsCompletedStats:  {
    __typename: "Chart",
    labels: Array< string >,
    datasets:  Array< {
      __typename: "ChartDataSet",
      label: string,
      values: Array< number >,
    } >,
  },
  permitsUnitsFiledStatsMonthly:  {
    __typename: "Chart",
    labels: Array< string >,
    datasets:  Array< {
      __typename: "ChartDataSet",
      label: string,
      values: Array< number >,
    } >,
  },
};

export interface OrganizationsQuery {
  organizations:  Array< {
    __typename: "Organization",
    id: string,
    slug: string,
    title: string,
    comments: string | null,
    logo: string | null,
    url: string | null,
    isDeveloper: boolean,
    isConstructor: boolean,
    developerIn:  Array< {
      __typename: "BuildingProject",
      id: string,
      slug: string,
      name: string,
      description: string | null,
      status: string | null,
      extrasYearEnd: string | null,
      extrasAddress: string | null,
      extrasAddressSecondary: string | null,
      existingUnits: number | null,
      proposedUnits: number | null,
      verified: boolean,
      extrasUrl: string | null,
      preview:  {
        __typename: "Picture",
        url: string,
        retina: string,
      } | null,
    } >,
    constructorIn:  Array< {
      __typename: "BuildingProject",
      id: string,
      slug: string,
      name: string,
      description: string | null,
      status: string | null,
      extrasYearEnd: string | null,
      extrasAddress: string | null,
      extrasAddressSecondary: string | null,
      existingUnits: number | null,
      proposedUnits: number | null,
      verified: boolean,
      extrasUrl: string | null,
      preview:  {
        __typename: "Picture",
        url: string,
        retina: string,
      } | null,
    } >,
  } >,
};

export interface OrganizationQueryVariables {
  orgId: string,
};

export interface OrganizationQuery {
  organization:  {
    __typename: "Organization",
    id: string,
    slug: string,
    title: string,
    comments: string | null,
    logo: string | null,
    cover: string | null,
    url: string | null,
    address: string | null,
    city: string | null,
    twitter: string | null,
    linkedin: string | null,
    facebook: string | null,
    isDeveloper: boolean,
    isConstructor: boolean,
    description: string | null,
    developerIn:  Array< {
      __typename: "BuildingProject",
      id: string,
      slug: string,
      name: string,
      description: string | null,
      status: string | null,
      extrasYearEnd: string | null,
      extrasAddress: string | null,
      extrasAddressSecondary: string | null,
      existingUnits: number | null,
      proposedUnits: number | null,
      verified: boolean,
      extrasUrl: string | null,
      preview:  {
        __typename: "Picture",
        url: string,
        retina: string,
      } | null,
    } >,
    constructorIn:  Array< {
      __typename: "BuildingProject",
      id: string,
      slug: string,
      name: string,
      description: string | null,
      status: string | null,
      extrasYearEnd: string | null,
      extrasAddress: string | null,
      extrasAddressSecondary: string | null,
      existingUnits: number | null,
      proposedUnits: number | null,
      verified: boolean,
      extrasUrl: string | null,
      preview:  {
        __typename: "Picture",
        url: string,
        retina: string,
      } | null,
    } >,
    partners:  Array< {
      __typename: "Organization",
      id: string,
      slug: string,
      title: string,
      comments: string | null,
      logo: string | null,
      url: string | null,
      isDeveloper: boolean,
      isConstructor: boolean,
      developerIn:  Array< {
        __typename: "BuildingProject",
        id: string,
        slug: string,
        name: string,
        description: string | null,
        status: string | null,
        extrasYearEnd: string | null,
        extrasAddress: string | null,
        extrasAddressSecondary: string | null,
        existingUnits: number | null,
        proposedUnits: number | null,
        verified: boolean,
        extrasUrl: string | null,
        preview:  {
          __typename: "Picture",
          url: string,
          retina: string,
        } | null,
      } >,
      constructorIn:  Array< {
        __typename: "BuildingProject",
        id: string,
        slug: string,
        name: string,
        description: string | null,
        status: string | null,
        extrasYearEnd: string | null,
        extrasAddress: string | null,
        extrasAddressSecondary: string | null,
        existingUnits: number | null,
        proposedUnits: number | null,
        verified: boolean,
        extrasUrl: string | null,
        preview:  {
          __typename: "Picture",
          url: string,
          retina: string,
        } | null,
      } >,
    } >,
  },
};

export interface OrganizationMutationAddMutationVariables {
  slug: string,
  title: string,
};

export interface OrganizationMutationAddMutation {
  organizationAdd:  {
    __typename: "Organization",
    id: string,
    slug: string,
    title: string,
    comments: string | null,
    logo: string | null,
    url: string | null,
    isDeveloper: boolean,
    isConstructor: boolean,
    developerIn:  Array< {
      __typename: "BuildingProject",
      id: string,
      slug: string,
      name: string,
      description: string | null,
      status: string | null,
      extrasYearEnd: string | null,
      extrasAddress: string | null,
      extrasAddressSecondary: string | null,
      existingUnits: number | null,
      proposedUnits: number | null,
      verified: boolean,
      extrasUrl: string | null,
      preview:  {
        __typename: "Picture",
        url: string,
        retina: string,
      } | null,
    } >,
    constructorIn:  Array< {
      __typename: "BuildingProject",
      id: string,
      slug: string,
      name: string,
      description: string | null,
      status: string | null,
      extrasYearEnd: string | null,
      extrasAddress: string | null,
      extrasAddressSecondary: string | null,
      existingUnits: number | null,
      proposedUnits: number | null,
      verified: boolean,
      extrasUrl: string | null,
      preview:  {
        __typename: "Picture",
        url: string,
        retina: string,
      } | null,
    } >,
  },
};

export interface OrganizationMutationRemoveMutationVariables {
  orgId: string,
};

export interface OrganizationMutationRemoveMutation {
  organizationRemove: string,
};

export interface OrganizationAlterMutationVariables {
  orgId: string,
  title?: string | null,
  comments?: string | null,
  logo?: string | null,
  cover?: string | null,
  url?: string | null,
  city?: string | null,
  address?: string | null,
  twitter?: string | null,
  linkedin?: string | null,
  facebook?: string | null,
  isDeveloper?: boolean | null,
  isConstructor?: boolean | null,
  description?: string | null,
};

export interface OrganizationAlterMutation {
  organizationAlter:  {
    __typename: "Organization",
    id: string,
    slug: string,
    title: string,
    comments: string | null,
    logo: string | null,
    cover: string | null,
    url: string | null,
    address: string | null,
    city: string | null,
    twitter: string | null,
    linkedin: string | null,
    facebook: string | null,
    isDeveloper: boolean,
    isConstructor: boolean,
    description: string | null,
    developerIn:  Array< {
      __typename: "BuildingProject",
      id: string,
      slug: string,
      name: string,
      description: string | null,
      status: string | null,
      extrasYearEnd: string | null,
      extrasAddress: string | null,
      extrasAddressSecondary: string | null,
      existingUnits: number | null,
      proposedUnits: number | null,
      verified: boolean,
      extrasUrl: string | null,
      preview:  {
        __typename: "Picture",
        url: string,
        retina: string,
      } | null,
    } >,
    constructorIn:  Array< {
      __typename: "BuildingProject",
      id: string,
      slug: string,
      name: string,
      description: string | null,
      status: string | null,
      extrasYearEnd: string | null,
      extrasAddress: string | null,
      extrasAddressSecondary: string | null,
      existingUnits: number | null,
      proposedUnits: number | null,
      verified: boolean,
      extrasUrl: string | null,
      preview:  {
        __typename: "Picture",
        url: string,
        retina: string,
      } | null,
    } >,
    partners:  Array< {
      __typename: "Organization",
      id: string,
      slug: string,
      title: string,
      comments: string | null,
      logo: string | null,
      url: string | null,
      isDeveloper: boolean,
      isConstructor: boolean,
      developerIn:  Array< {
        __typename: "BuildingProject",
        id: string,
        slug: string,
        name: string,
        description: string | null,
        status: string | null,
        extrasYearEnd: string | null,
        extrasAddress: string | null,
        extrasAddressSecondary: string | null,
        existingUnits: number | null,
        proposedUnits: number | null,
        verified: boolean,
        extrasUrl: string | null,
        preview:  {
          __typename: "Picture",
          url: string,
          retina: string,
        } | null,
      } >,
      constructorIn:  Array< {
        __typename: "BuildingProject",
        id: string,
        slug: string,
        name: string,
        description: string | null,
        status: string | null,
        extrasYearEnd: string | null,
        extrasAddress: string | null,
        extrasAddressSecondary: string | null,
        existingUnits: number | null,
        proposedUnits: number | null,
        verified: boolean,
        extrasUrl: string | null,
        preview:  {
          __typename: "Picture",
          url: string,
          retina: string,
        } | null,
      } >,
    } >,
  },
};

export interface BlocksConnectionQueryVariables {
  cursor?: string | null,
  page?: number | null,
};

export interface BlocksConnectionQuery {
  items:  {
    __typename: "BlockConnection",
    edges:  Array< {
      __typename: "BlockEdge",
      node:  {
        __typename: "Block",
        id: string,
        title: string,
        extrasArea: number | null,
        extrasSupervisorDistrict: string | null,
        extrasZoning: Array< string > | null,
      },
      cursor: string,
    } >,
    pageInfo:  {
      __typename: "PageInfo",
      hasNextPage: boolean,
      hasPreviousPage: boolean,
      itemsCount: number,
      currentPage: number,
      pagesCount: number,
      openEnded: boolean,
    },
  },
};

export interface BlockQueryVariables {
  blockId: string,
};

export interface BlockQuery {
  item:  {
    __typename: "Block",
    id: string,
    title: string,
    extrasArea: number | null,
    extrasZoning: Array< string > | null,
    extrasSupervisorDistrict: string | null,
    geometry: string | null,
    parcels:  Array< {
      __typename: "Parcel",
      id: string,
      title: string,
      geometry: string | null,
      extrasZoning: Array< string > | null,
    } >,
  },
};

export interface ParcelsConnectionQueryVariables {
  cursor?: string | null,
  page?: number | null,
};

export interface ParcelsConnectionQuery {
  items:  {
    __typename: "ParcelConnection",
    edges:  Array< {
      __typename: "ParcelEdge",
      node:  {
        __typename: "Parcel",
        id: string,
        title: string,
        geometry: string | null,
        extrasArea: number | null,
        extrasSupervisorDistrict: string | null,
        extrasZoning: Array< string > | null,
        extrasLandValue: number | null,
        extrasImprovementValue: number | null,
        extrasPropertyValue: number | null,
        extrasFixturesValue: number | null,
        extrasStories: number | null,
        extrasUnits: number | null,
        extrasRooms: number | null,
        extrasBathrooms: number | null,
        extrasBedrooms: number | null,
        extrasYear: number | null,
        extrasNeighborhood: string | null,
        addresses:  Array< {
          __typename: "StreetNumber",
          streetId: string,
          streetName: string,
          streetNameSuffix: string | null,
          streetNumber: number,
          streetNumberSuffix: string | null,
        } >,
        block:  {
          __typename: "Block",
          id: string,
          title: string,
          extrasArea: number | null,
        },
      },
      cursor: string,
    } >,
    pageInfo:  {
      __typename: "PageInfo",
      hasNextPage: boolean,
      hasPreviousPage: boolean,
      itemsCount: number,
      currentPage: number,
      pagesCount: number,
      openEnded: boolean,
    },
  },
};

export interface ParcelQueryVariables {
  parcelId: string,
};

export interface ParcelQuery {
  item:  {
    __typename: "Parcel",
    id: string,
    title: string,
    geometry: string | null,
    extrasArea: number | null,
    extrasSupervisorDistrict: string | null,
    extrasZoning: Array< string > | null,
    extrasLandValue: number | null,
    extrasImprovementValue: number | null,
    extrasPropertyValue: number | null,
    extrasFixturesValue: number | null,
    extrasStories: number | null,
    extrasUnits: number | null,
    extrasRooms: number | null,
    extrasBathrooms: number | null,
    extrasBedrooms: number | null,
    extrasYear: number | null,
    extrasNeighborhood: string | null,
    addresses:  Array< {
      __typename: "StreetNumber",
      streetId: string,
      streetName: string,
      streetNameSuffix: string | null,
      streetNumber: number,
      streetNumberSuffix: string | null,
    } >,
    block:  {
      __typename: "Block",
      id: string,
      title: string,
      extrasArea: number | null,
    },
  },
};

export interface ParcelsTileOverlayQueryVariables {
  box: GeoBox,
  query?: string | null,
};

export interface ParcelsTileOverlayQuery {
  tiles:  Array< {
    __typename: "Parcel",
    id: string,
    title: string,
    geometry: string | null,
  } > | null,
};

export interface PermitQueryVariables {
  permitId: string,
};

export interface PermitQuery {
  permit:  {
    __typename: "Permit",
    id: string,
    issuedAt: string | null,
    createdAt: string | null,
    startedAt: string | null,
    expiresAt: string | null,
    expiredAt: string | null,
    completedAt: string | null,
    filedAt: string | null,
    status: PermitStatus | null,
    statusUpdatedAt: string | null,
    type: PermitType | null,
    typeWood: boolean | null,
    existingStories: number | null,
    proposedStories: number | null,
    existingUnits: number | null,
    proposedUnits: number | null,
    existingAffordableUnits: number | null,
    proposedAffordableUnits: number | null,
    proposedUse: string | null,
    description: string | null,
    governmentalUrl: string,
    approvalTime: number | null,
    streetNumbers:  Array< {
      __typename: "StreetNumber",
      streetId: string,
      streetName: string,
      streetNameSuffix: string | null,
      streetNumber: number,
      streetNumberSuffix: string | null,
    } >,
    events:  Array<( {
        __typename: "PermitEventStatus",
        oldStatus: PermitStatus | null,
        newStatus: PermitStatus | null,
        date: string | null,
      } | {
        __typename: "PermitEventFieldChanged",
        fieldName: string,
        oldValue: string | null,
        newValue: string | null,
        date: string | null,
      }
    ) >,
    relatedPermits:  Array< {
      __typename: "Permit",
      id: string,
      createdAt: string | null,
      status: PermitStatus | null,
      statusUpdatedAt: string | null,
      type: PermitType | null,
      typeWood: boolean | null,
      description: string | null,
      approvalTime: number | null,
      proposedUnits: number | null,
      existingUnits: number | null,
      streetNumbers:  Array< {
        __typename: "StreetNumber",
        streetId: string,
        streetName: string,
        streetNameSuffix: string | null,
        streetNumber: number,
        streetNumberSuffix: string | null,
      } >,
    } >,
  } | null,
};

export interface PermitsConnectionQueryVariables {
  cursor?: string | null,
  filter?: string | null,
  page?: number | null,
  type?: PermitType | null,
  sort?: PermitSorting | null,
  minUnits?: number | null,
  issuedYear?: string | null,
  fromPipeline?: boolean | null,
};

export interface PermitsConnectionQuery {
  items:  {
    __typename: "PermitsConnection",
    edges:  Array< {
      __typename: "PermitEdge",
      node:  {
        __typename: "Permit",
        id: string,
        createdAt: string | null,
        status: PermitStatus | null,
        statusUpdatedAt: string | null,
        type: PermitType | null,
        typeWood: boolean | null,
        description: string | null,
        approvalTime: number | null,
        proposedUnits: number | null,
        existingUnits: number | null,
        streetNumbers:  Array< {
          __typename: "StreetNumber",
          streetId: string,
          streetName: string,
          streetNameSuffix: string | null,
          streetNumber: number,
          streetNumberSuffix: string | null,
        } >,
      },
      cursor: string,
    } >,
    pageInfo:  {
      __typename: "PageInfo",
      hasNextPage: boolean,
      hasPreviousPage: boolean,
      itemsCount: number,
      currentPage: number,
      pagesCount: number,
      openEnded: boolean,
    },
  },
};

export interface ProjectQueryVariables {
  areaId: string,
  projectId: string,
};

export interface ProjectQuery {
  project:  {
    __typename: "BuildingProject",
    id: string,
    slug: string,
    name: string,
    description: string | null,
    status: string | null,
    startedAt: string | null,
    completedAt: string | null,
    expectedCompletedAt: string | null,
    verified: boolean,
    existingUnits: number | null,
    proposedUnits: number | null,
    existingAffordableUnits: number | null,
    proposedAffordableUnits: number | null,
    preview:  {
      __typename: "Picture",
      url: string,
      retina: string,
    } | null,
    extrasDeveloper: string | null,
    extrasGeneralConstructor: string | null,
    extrasYearEnd: string | null,
    extrasAddress: string | null,
    extrasAddressSecondary: string | null,
    extrasPermit: string | null,
    extrasComment: string | null,
    extrasUrl: string | null,
    extrasLocation:  {
      __typename: "Geo",
      latitude: number,
      longitude: number,
    } | null,
    developers:  Array< {
      __typename: "Organization",
      id: string,
      slug: string,
      title: string,
      comments: string | null,
      logo: string | null,
      url: string | null,
      isDeveloper: boolean,
      isConstructor: boolean,
      developerIn:  Array< {
        __typename: "BuildingProject",
        id: string,
        slug: string,
        name: string,
        description: string | null,
        status: string | null,
        extrasYearEnd: string | null,
        extrasAddress: string | null,
        extrasAddressSecondary: string | null,
        existingUnits: number | null,
        proposedUnits: number | null,
        verified: boolean,
        extrasUrl: string | null,
        preview:  {
          __typename: "Picture",
          url: string,
          retina: string,
        } | null,
      } >,
      constructorIn:  Array< {
        __typename: "BuildingProject",
        id: string,
        slug: string,
        name: string,
        description: string | null,
        status: string | null,
        extrasYearEnd: string | null,
        extrasAddress: string | null,
        extrasAddressSecondary: string | null,
        existingUnits: number | null,
        proposedUnits: number | null,
        verified: boolean,
        extrasUrl: string | null,
        preview:  {
          __typename: "Picture",
          url: string,
          retina: string,
        } | null,
      } >,
    } >,
    constructors:  Array< {
      __typename: "Organization",
      id: string,
      slug: string,
      title: string,
      comments: string | null,
      logo: string | null,
      url: string | null,
      isDeveloper: boolean,
      isConstructor: boolean,
      developerIn:  Array< {
        __typename: "BuildingProject",
        id: string,
        slug: string,
        name: string,
        description: string | null,
        status: string | null,
        extrasYearEnd: string | null,
        extrasAddress: string | null,
        extrasAddressSecondary: string | null,
        existingUnits: number | null,
        proposedUnits: number | null,
        verified: boolean,
        extrasUrl: string | null,
        preview:  {
          __typename: "Picture",
          url: string,
          retina: string,
        } | null,
      } >,
      constructorIn:  Array< {
        __typename: "BuildingProject",
        id: string,
        slug: string,
        name: string,
        description: string | null,
        status: string | null,
        extrasYearEnd: string | null,
        extrasAddress: string | null,
        extrasAddressSecondary: string | null,
        existingUnits: number | null,
        proposedUnits: number | null,
        verified: boolean,
        extrasUrl: string | null,
        preview:  {
          __typename: "Picture",
          url: string,
          retina: string,
        } | null,
      } >,
    } >,
    permits:  Array< {
      __typename: "Permit",
      id: string,
      createdAt: string | null,
      status: PermitStatus | null,
      statusUpdatedAt: string | null,
      type: PermitType | null,
      typeWood: boolean | null,
      description: string | null,
      approvalTime: number | null,
      proposedUnits: number | null,
      existingUnits: number | null,
      streetNumbers:  Array< {
        __typename: "StreetNumber",
        streetId: string,
        streetName: string,
        streetNameSuffix: string | null,
        streetNumber: number,
        streetNumberSuffix: string | null,
      } >,
    } >,
  },
};

export interface ProjectsConnectionQueryVariables {
  areaId: string,
  cursor?: string | null,
  page?: number | null,
  minUnits?: number | null,
  year?: string | null,
  filter?: string | null,
};

export interface ProjectsConnectionQuery {
  items:  {
    __typename: "BuildingProjectConnection",
    edges:  Array< {
      __typename: "BuildingProjectEdge",
      node:  {
        __typename: "BuildingProject",
        id: string,
        slug: string,
        name: string,
        description: string | null,
        status: string | null,
        extrasYearEnd: string | null,
        extrasAddress: string | null,
        extrasAddressSecondary: string | null,
        existingUnits: number | null,
        proposedUnits: number | null,
        verified: boolean,
        extrasUrl: string | null,
        preview:  {
          __typename: "Picture",
          url: string,
          retina: string,
        } | null,
      },
      cursor: string,
    } >,
    pageInfo:  {
      __typename: "PageInfo",
      hasNextPage: boolean,
      hasPreviousPage: boolean,
      itemsCount: number,
      currentPage: number,
      pagesCount: number,
      openEnded: boolean,
    },
    stats:  {
      __typename: "BuildingProjectConnectionStats",
      newUnits: number,
      newUnitsVerified: number,
      totalProjects: number,
      totalProjectsVerified: number,
    },
  },
};

export interface ProjectsSFConnectionQueryVariables {
  cursor?: string | null,
  page?: number | null,
  minUnits?: number | null,
  year?: string | null,
  filter?: string | null,
};

export interface ProjectsSFConnectionQuery {
  items:  {
    __typename: "BuildingProjectConnection",
    edges:  Array< {
      __typename: "BuildingProjectEdge",
      node:  {
        __typename: "BuildingProject",
        id: string,
        slug: string,
        name: string,
        description: string | null,
        status: string | null,
        extrasYearEnd: string | null,
        extrasAddress: string | null,
        extrasAddressSecondary: string | null,
        existingUnits: number | null,
        proposedUnits: number | null,
        verified: boolean,
        extrasUrl: string | null,
        preview:  {
          __typename: "Picture",
          url: string,
          retina: string,
        } | null,
      },
      cursor: string,
    } >,
    pageInfo:  {
      __typename: "PageInfo",
      hasNextPage: boolean,
      hasPreviousPage: boolean,
      itemsCount: number,
      currentPage: number,
      pagesCount: number,
      openEnded: boolean,
    },
    stats:  {
      __typename: "BuildingProjectConnectionStats",
      newUnits: number,
      newUnitsVerified: number,
      totalProjects: number,
      totalProjectsVerified: number,
    },
  },
};

export interface ProjectSFQueryVariables {
  projectId: string,
};

export interface ProjectSFQuery {
  project:  {
    __typename: "BuildingProject",
    id: string,
    slug: string,
    name: string,
    description: string | null,
    status: string | null,
    startedAt: string | null,
    completedAt: string | null,
    expectedCompletedAt: string | null,
    verified: boolean,
    existingUnits: number | null,
    proposedUnits: number | null,
    existingAffordableUnits: number | null,
    proposedAffordableUnits: number | null,
    preview:  {
      __typename: "Picture",
      url: string,
      retina: string,
    } | null,
    extrasDeveloper: string | null,
    extrasGeneralConstructor: string | null,
    extrasYearEnd: string | null,
    extrasAddress: string | null,
    extrasAddressSecondary: string | null,
    extrasPermit: string | null,
    extrasComment: string | null,
    extrasUrl: string | null,
    extrasLocation:  {
      __typename: "Geo",
      latitude: number,
      longitude: number,
    } | null,
    developers:  Array< {
      __typename: "Organization",
      id: string,
      slug: string,
      title: string,
      comments: string | null,
      logo: string | null,
      url: string | null,
      isDeveloper: boolean,
      isConstructor: boolean,
      developerIn:  Array< {
        __typename: "BuildingProject",
        id: string,
        slug: string,
        name: string,
        description: string | null,
        status: string | null,
        extrasYearEnd: string | null,
        extrasAddress: string | null,
        extrasAddressSecondary: string | null,
        existingUnits: number | null,
        proposedUnits: number | null,
        verified: boolean,
        extrasUrl: string | null,
        preview:  {
          __typename: "Picture",
          url: string,
          retina: string,
        } | null,
      } >,
      constructorIn:  Array< {
        __typename: "BuildingProject",
        id: string,
        slug: string,
        name: string,
        description: string | null,
        status: string | null,
        extrasYearEnd: string | null,
        extrasAddress: string | null,
        extrasAddressSecondary: string | null,
        existingUnits: number | null,
        proposedUnits: number | null,
        verified: boolean,
        extrasUrl: string | null,
        preview:  {
          __typename: "Picture",
          url: string,
          retina: string,
        } | null,
      } >,
    } >,
    constructors:  Array< {
      __typename: "Organization",
      id: string,
      slug: string,
      title: string,
      comments: string | null,
      logo: string | null,
      url: string | null,
      isDeveloper: boolean,
      isConstructor: boolean,
      developerIn:  Array< {
        __typename: "BuildingProject",
        id: string,
        slug: string,
        name: string,
        description: string | null,
        status: string | null,
        extrasYearEnd: string | null,
        extrasAddress: string | null,
        extrasAddressSecondary: string | null,
        existingUnits: number | null,
        proposedUnits: number | null,
        verified: boolean,
        extrasUrl: string | null,
        preview:  {
          __typename: "Picture",
          url: string,
          retina: string,
        } | null,
      } >,
      constructorIn:  Array< {
        __typename: "BuildingProject",
        id: string,
        slug: string,
        name: string,
        description: string | null,
        status: string | null,
        extrasYearEnd: string | null,
        extrasAddress: string | null,
        extrasAddressSecondary: string | null,
        existingUnits: number | null,
        proposedUnits: number | null,
        verified: boolean,
        extrasUrl: string | null,
        preview:  {
          __typename: "Picture",
          url: string,
          retina: string,
        } | null,
      } >,
    } >,
    permits:  Array< {
      __typename: "Permit",
      id: string,
      createdAt: string | null,
      status: PermitStatus | null,
      statusUpdatedAt: string | null,
      type: PermitType | null,
      typeWood: boolean | null,
      description: string | null,
      approvalTime: number | null,
      proposedUnits: number | null,
      existingUnits: number | null,
      streetNumbers:  Array< {
        __typename: "StreetNumber",
        streetId: string,
        streetName: string,
        streetNameSuffix: string | null,
        streetNumber: number,
        streetNumberSuffix: string | null,
      } >,
    } >,
  },
};

export interface SearchQueryVariables {
  query: string,
};

export interface SearchQuery {
  search:  {
    __typename: "SearchResult",
    parcels:  {
      __typename: "ParcelSearchResult",
      edges:  Array< {
        __typename: "ParcelResult",
        node:  {
          __typename: "Parcel",
          id: string,
          title: string,
        },
      } >,
      total: number,
    },
  },
};

export interface AreaShortFragment {
  __typename: "Area",
  id: string,
  slug: string,
  writeAccess: boolean,
};

export interface ChartFullFragment {
  __typename: "Chart",
  labels: Array< string >,
  datasets:  Array< {
    __typename: string,
    label: string,
    values: Array< number >,
  } >,
};

export interface GeoShortFragment {
  __typename: "Geo",
  latitude: number,
  longitude: number,
};

export interface OrganizationShortFragment {
  __typename: "Organization",
  id: string,
  slug: string,
  title: string,
  comments: string | null,
  logo: string | null,
  url: string | null,
  isDeveloper: boolean,
  isConstructor: boolean,
  developerIn:  Array< {
    __typename: string,
    id: string,
    slug: string,
    name: string,
    description: string | null,
    status: string | null,
    extrasYearEnd: string | null,
    extrasAddress: string | null,
    extrasAddressSecondary: string | null,
    existingUnits: number | null,
    proposedUnits: number | null,
    verified: boolean,
    extrasUrl: string | null,
    preview:  {
      __typename: string,
      url: string,
      retina: string,
    } | null,
  } >,
  constructorIn:  Array< {
    __typename: string,
    id: string,
    slug: string,
    name: string,
    description: string | null,
    status: string | null,
    extrasYearEnd: string | null,
    extrasAddress: string | null,
    extrasAddressSecondary: string | null,
    existingUnits: number | null,
    proposedUnits: number | null,
    verified: boolean,
    extrasUrl: string | null,
    preview:  {
      __typename: string,
      url: string,
      retina: string,
    } | null,
  } >,
};

export interface OrganizationFullFragment {
  __typename: "Organization",
  id: string,
  slug: string,
  title: string,
  comments: string | null,
  logo: string | null,
  cover: string | null,
  url: string | null,
  address: string | null,
  city: string | null,
  twitter: string | null,
  linkedin: string | null,
  facebook: string | null,
  isDeveloper: boolean,
  isConstructor: boolean,
  description: string | null,
  developerIn:  Array< {
    __typename: string,
    id: string,
    slug: string,
    name: string,
    description: string | null,
    status: string | null,
    extrasYearEnd: string | null,
    extrasAddress: string | null,
    extrasAddressSecondary: string | null,
    existingUnits: number | null,
    proposedUnits: number | null,
    verified: boolean,
    extrasUrl: string | null,
    preview:  {
      __typename: string,
      url: string,
      retina: string,
    } | null,
  } >,
  constructorIn:  Array< {
    __typename: string,
    id: string,
    slug: string,
    name: string,
    description: string | null,
    status: string | null,
    extrasYearEnd: string | null,
    extrasAddress: string | null,
    extrasAddressSecondary: string | null,
    existingUnits: number | null,
    proposedUnits: number | null,
    verified: boolean,
    extrasUrl: string | null,
    preview:  {
      __typename: string,
      url: string,
      retina: string,
    } | null,
  } >,
  partners:  Array< {
    __typename: string,
    id: string,
    slug: string,
    title: string,
    comments: string | null,
    logo: string | null,
    url: string | null,
    isDeveloper: boolean,
    isConstructor: boolean,
    developerIn:  Array< {
      __typename: string,
      id: string,
      slug: string,
      name: string,
      description: string | null,
      status: string | null,
      extrasYearEnd: string | null,
      extrasAddress: string | null,
      extrasAddressSecondary: string | null,
      existingUnits: number | null,
      proposedUnits: number | null,
      verified: boolean,
      extrasUrl: string | null,
      preview:  {
        __typename: string,
        url: string,
        retina: string,
      } | null,
    } >,
    constructorIn:  Array< {
      __typename: string,
      id: string,
      slug: string,
      name: string,
      description: string | null,
      status: string | null,
      extrasYearEnd: string | null,
      extrasAddress: string | null,
      extrasAddressSecondary: string | null,
      existingUnits: number | null,
      proposedUnits: number | null,
      verified: boolean,
      extrasUrl: string | null,
      preview:  {
        __typename: string,
        url: string,
        retina: string,
      } | null,
    } >,
  } >,
};

export interface ParcelFullFragment {
  __typename: "Parcel",
  id: string,
  title: string,
  geometry: string | null,
  extrasArea: number | null,
  extrasSupervisorDistrict: string | null,
  extrasZoning: Array< string > | null,
  extrasLandValue: number | null,
  extrasImprovementValue: number | null,
  extrasPropertyValue: number | null,
  extrasFixturesValue: number | null,
  extrasStories: number | null,
  extrasUnits: number | null,
  extrasRooms: number | null,
  extrasBathrooms: number | null,
  extrasBedrooms: number | null,
  extrasYear: number | null,
  extrasNeighborhood: string | null,
  addresses:  Array< {
    __typename: string,
    streetId: string,
    streetName: string,
    streetNameSuffix: string | null,
    streetNumber: number,
    streetNumberSuffix: string | null,
  } >,
  block:  {
    __typename: string,
    id: string,
    title: string,
    extrasArea: number | null,
  },
};

export interface BlockShortFragment {
  __typename: "Block",
  id: string,
  title: string,
  extrasArea: number | null,
  extrasSupervisorDistrict: string | null,
  extrasZoning: Array< string > | null,
};

export interface BlockFullFragment {
  __typename: "Block",
  id: string,
  title: string,
  extrasArea: number | null,
  extrasZoning: Array< string > | null,
  extrasSupervisorDistrict: string | null,
  geometry: string | null,
  parcels:  Array< {
    __typename: string,
    id: string,
    title: string,
    geometry: string | null,
    extrasZoning: Array< string > | null,
  } >,
};

export interface PermitShortFragment {
  __typename: "Permit",
  id: string,
  createdAt: string | null,
  status: PermitStatus | null,
  statusUpdatedAt: string | null,
  type: PermitType | null,
  typeWood: boolean | null,
  description: string | null,
  approvalTime: number | null,
  proposedUnits: number | null,
  existingUnits: number | null,
  streetNumbers:  Array< {
    __typename: string,
    streetId: string,
    streetName: string,
    streetNameSuffix: string | null,
    streetNumber: number,
    streetNumberSuffix: string | null,
  } >,
};

export interface PermitFullFragment {
  __typename: "Permit",
  id: string,
  issuedAt: string | null,
  createdAt: string | null,
  startedAt: string | null,
  expiresAt: string | null,
  expiredAt: string | null,
  completedAt: string | null,
  filedAt: string | null,
  status: PermitStatus | null,
  statusUpdatedAt: string | null,
  type: PermitType | null,
  typeWood: boolean | null,
  existingStories: number | null,
  proposedStories: number | null,
  existingUnits: number | null,
  proposedUnits: number | null,
  existingAffordableUnits: number | null,
  proposedAffordableUnits: number | null,
  proposedUse: string | null,
  description: string | null,
  governmentalUrl: string,
  approvalTime: number | null,
  streetNumbers:  Array< {
    __typename: string,
    streetId: string,
    streetName: string,
    streetNameSuffix: string | null,
    streetNumber: number,
    streetNumberSuffix: string | null,
  } >,
  events:  Array<( {
      __typename: "PermitEventStatus",
      oldStatus: PermitStatus | null,
      newStatus: PermitStatus | null,
      date: string | null,
    } | {
      __typename: "PermitEventFieldChanged",
      fieldName: string,
      oldValue: string | null,
      newValue: string | null,
      date: string | null,
    }
  ) >,
  relatedPermits:  Array< {
    __typename: string,
    id: string,
    createdAt: string | null,
    status: PermitStatus | null,
    statusUpdatedAt: string | null,
    type: PermitType | null,
    typeWood: boolean | null,
    description: string | null,
    approvalTime: number | null,
    proposedUnits: number | null,
    existingUnits: number | null,
    streetNumbers:  Array< {
      __typename: string,
      streetId: string,
      streetName: string,
      streetNameSuffix: string | null,
      streetNumber: number,
      streetNumberSuffix: string | null,
    } >,
  } >,
};

export interface ProjectShortFragment {
  __typename: "BuildingProject",
  id: string,
  slug: string,
  name: string,
  description: string | null,
  status: string | null,
  extrasYearEnd: string | null,
  extrasAddress: string | null,
  extrasAddressSecondary: string | null,
  existingUnits: number | null,
  proposedUnits: number | null,
  verified: boolean,
  extrasUrl: string | null,
  preview:  {
    __typename: string,
    url: string,
    retina: string,
  } | null,
};

export interface ProjectPreviewFragment {
  __typename: "BuildingProject",
  id: string,
  slug: string,
  name: string,
  approvalTime: number | null,
  preview:  {
    __typename: string,
    url: string,
    retina: string,
  } | null,
};

export interface ProjectFullFragment {
  __typename: "BuildingProject",
  id: string,
  slug: string,
  name: string,
  description: string | null,
  status: string | null,
  startedAt: string | null,
  completedAt: string | null,
  expectedCompletedAt: string | null,
  verified: boolean,
  existingUnits: number | null,
  proposedUnits: number | null,
  existingAffordableUnits: number | null,
  proposedAffordableUnits: number | null,
  preview:  {
    __typename: string,
    url: string,
    retina: string,
  } | null,
  extrasDeveloper: string | null,
  extrasGeneralConstructor: string | null,
  extrasYearEnd: string | null,
  extrasAddress: string | null,
  extrasAddressSecondary: string | null,
  extrasPermit: string | null,
  extrasComment: string | null,
  extrasUrl: string | null,
  extrasLocation:  {
    __typename: string,
    latitude: number,
    longitude: number,
  } | null,
  developers:  Array< {
    __typename: string,
    id: string,
    slug: string,
    title: string,
    comments: string | null,
    logo: string | null,
    url: string | null,
    isDeveloper: boolean,
    isConstructor: boolean,
    developerIn:  Array< {
      __typename: string,
      id: string,
      slug: string,
      name: string,
      description: string | null,
      status: string | null,
      extrasYearEnd: string | null,
      extrasAddress: string | null,
      extrasAddressSecondary: string | null,
      existingUnits: number | null,
      proposedUnits: number | null,
      verified: boolean,
      extrasUrl: string | null,
      preview:  {
        __typename: string,
        url: string,
        retina: string,
      } | null,
    } >,
    constructorIn:  Array< {
      __typename: string,
      id: string,
      slug: string,
      name: string,
      description: string | null,
      status: string | null,
      extrasYearEnd: string | null,
      extrasAddress: string | null,
      extrasAddressSecondary: string | null,
      existingUnits: number | null,
      proposedUnits: number | null,
      verified: boolean,
      extrasUrl: string | null,
      preview:  {
        __typename: string,
        url: string,
        retina: string,
      } | null,
    } >,
  } >,
  constructors:  Array< {
    __typename: string,
    id: string,
    slug: string,
    title: string,
    comments: string | null,
    logo: string | null,
    url: string | null,
    isDeveloper: boolean,
    isConstructor: boolean,
    developerIn:  Array< {
      __typename: string,
      id: string,
      slug: string,
      name: string,
      description: string | null,
      status: string | null,
      extrasYearEnd: string | null,
      extrasAddress: string | null,
      extrasAddressSecondary: string | null,
      existingUnits: number | null,
      proposedUnits: number | null,
      verified: boolean,
      extrasUrl: string | null,
      preview:  {
        __typename: string,
        url: string,
        retina: string,
      } | null,
    } >,
    constructorIn:  Array< {
      __typename: string,
      id: string,
      slug: string,
      name: string,
      description: string | null,
      status: string | null,
      extrasYearEnd: string | null,
      extrasAddress: string | null,
      extrasAddressSecondary: string | null,
      existingUnits: number | null,
      proposedUnits: number | null,
      verified: boolean,
      extrasUrl: string | null,
      preview:  {
        __typename: string,
        url: string,
        retina: string,
      } | null,
    } >,
  } >,
  permits:  Array< {
    __typename: string,
    id: string,
    createdAt: string | null,
    status: PermitStatus | null,
    statusUpdatedAt: string | null,
    type: PermitType | null,
    typeWood: boolean | null,
    description: string | null,
    approvalTime: number | null,
    proposedUnits: number | null,
    existingUnits: number | null,
    streetNumbers:  Array< {
      __typename: string,
      streetId: string,
      streetName: string,
      streetNameSuffix: string | null,
      streetNumber: number,
      streetNumberSuffix: string | null,
    } >,
  } >,
};

export interface UserShortFragment {
  __typename: "User",
  id: string,
  name: string,
  firstName: string,
  lastName: string,
  picture: string,
};
