export const en = {
  "about": "About",
  "aboutOpenland": "About Openland",
  "aboutUs": "About us",
  "accessDenied": "Access Denied",
  "accessDeniedGroup": "Cannot view chat",
  "accessDeniedGroupDescription": "This chat doesn't exist or you don't have permission to view it",
  "accessSuspended": "Your access to “{{title}}” is suspended",
  "accessSuspendedDescription": "To keep your access to the chat by subscription you need to complete payment",
  "accountPrivacy": "Account and privacy",
  "active": "Active",
  "add": "Add",
  "addCard": "Add card",
  "addDetailsOptional": "Add details (optional)",
  "addPeople": "Add people",
  "addPeopleFree": "Add people for free",
  "addToGroups": "Add to chats",
  "admin": "Admin",
  "allow": "Allow",
  "allowContacts": "Allow Openland access to your contacts",
  "allowContactsDescription": "Find people you already know by allowing Openland to upload and store a copy of your contacts. <PrivacyLink>Privacy policy</PrivacyLink>",
  "allowed": "Allowed",
  "amount": "Amount",
  "and": "and",
  "andOthers": "and {{num}} others",
  "angry": "Angry",
  "appearance": "Appearance",
  "applyLink": "Apply link",
  "applyLinkDescription": "A link to application form or info",
  "applyLinkUse": "Use apply link",
  "applyToJoin": "Apply to join",
  "attachDocumentAndroid": "Document",
  "attachDocumentIOS": "Send document",
  "attachDonationAndroid": "Donation",
  "attachDontaionIOS": "Make donation",
  "attachPhotoAndroid": "Photo gallery",
  "attachPhotoIOS": "Choose from library",
  "attachRecordVideo": "Record video",
  "attachTakePhoto": "Take photo",
  "attachVideo": "Video gallery",
  "audio": "Audio",
  "becomeListener": "Become listener",
  "billing": "Billing",
  "billingProblem": "Billing problem",
  "billingProblemDescription": "A payment for some of your recent purchases or subscriptions has recently failed. Please update your payment method to keep your paid chat memberships.",
  "birthday": "Birthday",
  "blockPerson": "Block person",
  "blocked": "Blocked",
  "blockedByYou": "You blocked this person",
  "blockedSelf": "You are blocked",
  "bot": "Bot",
  "calendarOpen": "Open in Calendar",
  "callLink": "Call link",
  "callMembers": "$t(member) on call",
  "callMembersDefault": "On call",
  "callMembers_plural": "$t(member_plural) on call",
  "camera": "Camera",
  "cancel": "Cancel",
  "cardExpired": "Expired on {{expireDate}}",
  "cardValid": "Valid to {{validDate}}",
  "change": "Change",
  "channel": "channel",
  "chat": "Chat",
  "chatRecommendations": "Get chat recommendations",
  "chooseSender": "Choose sender",
  "chooseShortnameGroup": "Choose a shortname so other people can find and mention your chat",
  "chooseShortnameChannel": "Choose a shortname so other people can find and mention your channel",
  "chooseShortnameCommunity": "Choose a shortname so other people can find and mention your community",
  "chooseShortnameOrganization": "Choose a shortname so other people can find and mention your organization",
  "clear": "Clear",
  "close": "Close",
  "closeRoom": "Close room",
  "collections": "Collections",
  "collectionsCoversBy": "Editors’ choice and collections covers by",
  "comment": "Comment",
  "commentAction": "Comment",
  "commentDelete": "Delete comment",
  "commentDeleteDescription": "Delete this comment for everyone? This cannot be undone.",
  "comments": "Comments",
  "community": "Community",
  "communityDescription": "Publicly describe this community for all to see",
  "communityPrivateDescription": "Members can invite people",
  "communityTypeDescription": "Set by creator",
  "communityWithMember": "Community   ·  {{count}} $t(member)",
  "communityWithMember_plural": "Community   ·  {{count}} $t(member_plural)",
  "communities": "Communities",
  "confirm": "Confirm",
  "connecting": "Connecting",
  "contactUs": "Contact us",
  "contacts": "Contacts",
  "contactsAdd": "Add to contacts",
  "contactsImport": "Import contacts",
  "contactsImportDescription": "Import contacts from your device to find people you know on Openland",
  "contactsRemove": "Remove from contacts",
  "contactsSave": "Save to contacts",
  "contentMissingOrRestricted": "This content doesn’t exist or you don’t have an access",
  "contentUnavailable": "Content is unavailable",
  "continue": "Continue",
  "continueWithEmail": "Continue with email",
  "continueWithPhone": "Continue with phone",
  "conversationConnect": "Happy to connect!",
  "conversationDelete": "Delete conversation",
  "conversationDeleteBoth": "Delete for me and {{userName}}",
  "conversationDeleteDescription": "Are you sure you want to delete conversation? This cannot be undone.",
  "conversationHello": "Hello, {{name}}!",
  "conversationNoMessages": "No messages yet",
  "conversationStart": "Start a conversation with {{name}}",
  "copied": "Copied",
  "copy": "Copy",
  "copyLink": "Copy link",
  "correspondents": "Correspondents",
  "country": "Country",
  "create": "Create",
  "createAccount": "Create account",
  "createCommunity": "Create community",
  "createGroup": "Create chat",
  "createGroupFree": "Free",
  "createGroupFreeDescription": "Members join for free",
  "createGroupPaid": "One-time payment",
  "createGroupPaidDescription": "Members pay once to join",
  "createGroupSubscription": "Subscription",
  "createGroupSubscriptionDescription": "Recurrent membership fee",
  "createNew": "Create new",
  "createOrganizationDescription": "Please, provide organization name and optional logo",
  "createOrganizationPublic": "Public",
  "createOrganizationPublicDescription": "Visible in search",
  "createOrganizationSecret": "Secret",
  "createOrganizationSecretDescription": "Only people with invite link can see it",
  "custom": "Custom",
  "dateAndTime": "Date and time",
  "day": "Day",
  "defaultGroups": "Default chats",
  "defaultGroupsDescription": "Select chats that will be automatically joined by all new community members",
  "delete": "Delete",
  "deleteCard": "Delete card",
  "deleteCardDescription": "It cannot be undone",
  "deleteCardQuestion": "Delete card?",
  "deleteChannel": "Delete channel",
  "deleteChannelQuestion": "Delete channel?",
  "deleteCommunity": "Delete community",
  "deleteCommunityQuestion": "Delete community?",
  "deleteGroup": "Delete chat",
  "deleteGroupQuestion": "Delete chat?",
  "deleteMessageDescription": "The message will be deleted for everyone. This cannot be undone",
  "deleteMessageQuestion": "Delete message?",
  "deleteMessagesDescription": "Messages will be deleted for everyone. This cannot be undone",
  "deleteOrganization": "Delete organization",
  "deleteOrganizationQuestion": "Delete organization?",
  "deletePerson": "Delete person",
  "deletePinnedMessageQuestion": "Delete pinned message?",
  "deleteUser": "Delete user",
  "description": "Description",
  "dialogAllChats": "All chats",
  "dialogChats": "Chats",
  "dialogDirect": "Direct",
  "dialogGroups": "Chats",
  "dialogUnread": "Unread",
  "directMessages": "Direct messages",
  "disallowed": "Disallowed",
  "discover": "Discover",
  "discoverChannel": "Only admins write, others comment",
  "discoverChat": "Public, secret, or paid chat",
  "discoverChats": "Discover chats",
  "discoverCommunity": "A hub for your chats and channels",
  "discoverFindChats": "Find more chats",
  "discoverGetRecommendations": "Get recommendations for your interests",
  "discoverGroups": "Discover chats",
  "discoverNewCommunities": "New communities",
  "discoverNewGroups": "New chats",
  "discoverPopular": "Popular now",
  "discoverRecommendations": "Recommendations",
  "discoverTopCommunities": "Top communities",
  "discoverTopGroups": "Top chats",
  "discoverTopPremium": "Top premium",
  "dismiss": "Dismiss",
  "dismissAdmin": "Dismiss as admin",
  "dismissAdminQuestion": "Dismiss {{name}} as admin?",
  "document": "Document",
  "donate": "Donate",
  "donateToUser": "Donate to {{name}}",
  "done": "Done",
  "edit": "Edit",
  "editChannel": "Edit channel",
  "editComment": "Edit comment",
  "editCommunity": "Edit community",
  "editGroup": "Edit chat",
  "editInfo": "Edit info",
  "editMessage": "Edit message",
  "editOrganization": "Edit organization",
  "editPersonalVisibility": "Edit phone/email and their visibility \nin ",
  "editProfile": "Edit profile",
  "editRoom": "Edit room",
  "email": "Email",
  "emailPreferences": "Email preferences",
  "end": "End",
  "endRoom": "End room",
  "endRoomDescription": "Leaving as the last admin will end the room. Return and make new admins if you want to keep the room going",
  "enterCode": "Enter code",
  "enterDay": "Please enter day",
  "enterValidDate": "Please enter valid date",
  "error": "Error",
  "errorAbstract": "Something went wrong",
  "errorCardInvalid": "Invalid card number",
  "errorFileUpload": "Error while uploading file",
  "errorJoinChat": "Couldn't join {{chatType}}",
  "errorNoInvite": "Invite not found",
  "errorRepliesDisabled": "Replies are disabled for this chat",
  "errorUnknown": "Unknown error",
  "everyone": "Everyone",
  "expired": "Expired",
  "featured": "Featured",
  "files": "Files",
  "findChats": "Find the right chats for you",
  "findFriends": "Find your friends",
  "firstName": "First name",
  "flip": "Flip",
  "follow": "Follow",
  "followed": "Followed",
  "follower": "follower",
  "follower_plural": "followers",
  "followers": "Followers",
  "following": "Following",
  "followingCount": "following",
  "forward": "Forward",
  "forwardMessages": "Forward messages",
  "forwardTo": "Forward to",
  "forwardedMessage": "forwarded message",
  "forwardedMessage_plural": "forwarded messages",
  "free": "Free",
  "fromChat": "From",
  "fromChatWith": "From chat with",
  "getHelp": "Get help from Openland community",
  "goBack": "Go back",
  "gotIt": "Got it",
  "group": "chat",
  "groupCalls": "Chat calls",
  "groupCallsChoose": "Choose what calls to use",
  "groupCallsCustom": "Custom call link",
  "groupCallsExternal": "A link to external call room, e.g. on Zoom, Google Meet, or any other service",
  "groupCallsNone": "No calls",
  "groupCallsStandard": "Standard Openland rooms",
  "groupPriceDescription": "Set up monetization of your chat. All changes will affect only new members",
  "group_plural": "chats",
  "groups": "Chats",
  "groupsColon": "Chats:",
  "haha": "Haha",
  "helpAndFeedback": "Help and feedback",
  "illustrationsBy": "Product illustrations by",
  "info": "Info",
  "inputPlaceholderChannel": "Broadcast something...",
  "inputPlaceholderGroup": "Message",
  "invite": "Invite",
  "inviteAccept": "Accept invitation",
  "inviteByUser": "{{name}} invites you to join {{title}}",
  "inviteContacts": "Invite your contacts to Openland or add people manually from their profiles,and they will appear here",
  "inviteFriends": "Invite friends",
  "inviteFriendsDescription": "Didn’t find your friends at Openland? Let’s invite them to stay in touch",
  "inviteJoinChannel": "Invite people to join channel",
  "inviteJoinConversation": "Invite people to join conversation",
  "inviteLinkChannel": "Channel link",
  "inviteLinkCommunity": "Community invite link",
  "inviteLinkCommunityDescription": "People can join community by following this link. You can renew the link at any time",
  "inviteLinkDescription": "Anyone with link can join as chat member",
  "inviteLinkGroup": "Chat link",
  "inviteLinkOrganization": "Organization invite link",
  "inviteLinkOrganizationDescription": "People can join organization by following this link. You can renew the link at any time",
  "inviteRevoked": "This invitation has been revoked",
  "inviteTo": "Invite to {{title}}",
  "inviteWithLink": "Invite with link",
  "join": "Join",
  "joinAll": "Join all",
  "joinChannel": "Join channel",
  "joinChat": "Join {{chatType}}",
  "joinGroup": "Join chat",
  "joinPaidChat": "Join for {{amount}}",
  "joinPaidChatWithPeriod": "Join for {{amount}} / {{periodShort}}",
  "joinRoom": "Join room",
  "joinedDate": "Joined {{date}}",
  "kickCommunity": "Remove from community",
  "kickCommunityQuestion": "Remove {{name}} from community?",
  "kickOrganization": "Remove from organization",
  "kickOrganizationQuestion": "Remove {{name}} from organization?",
  "kickUserFromChannel": "Remove {{name}} from channel?",
  "kickUserFromGroup": "Remove {{name}} from chat?",
  "kickWarning": "They will be removed from all internal chats",
  "lastName": "Last name",
  "leave": "Leave",
  "leaveChannel": "Leave channel",
  "leaveChannelQuestion": "Leave channel?",
  "leaveChatDescription": "You may not be able to join it again",
  "leaveChatPremiumDescription": "Leaving the chat will cancel your subscription to it. Are you sure?",
  "leaveCommunity": "Leave community",
  "leaveCommunityQuestion": "Leave community?",
  "leaveGroup": "Leave chat",
  "leaveGroupQuestion": "Leave chat?",
  "leaveOrganization": "Leave organization",
  "leaveOrganizationQuestion": "Leave organization?",
  "leaveWarning": "You may not be able to join it again",
  "licenses": "Licenses",
  "like": "Like",
  "likeCount": "like",
  "like_plural": "likes",
  "liked": "Liked",
  "linkCopied": "Link copied",
  "links": "Links",
  "listeners": "Listeners",
  "loading": "Loading",
  "location": "Location",
  "loginCodeDescription": "We’ll send you a sign-in code",
  "loginEmailQuestion": "What’s your email?",
  "loginPhoneConfirm": "Is this phone number correct?",
  "loginPhoneQuestion": "What’s your phone?",
  "loginSigninCode": "Enter sign-in code",
  "loginSignupCode": "Enter sign-up code",
  "loginTitle": "Modern social network\nbuilt for you, not advertisers",
  "love": "Love",
  "make": "Make",
  "makeAdmin": "Make admin",
  "makeAdminQuestion": "Make {{name}} admin?",
  "makeDonation": "Make donation",
  "makeListener": "Make listener",
  "makePrimary": "Make primary",
  "makeSpeaker": "Make speaker",
  "maybeLater": "Maybe later",
  "media": "Media",
  "member": "member",
  "member_plural": "members",
  "members": "Members",
  "membersColon": "Members:",
  "mentionsMissing": "Not in this chat",
  "mentionsSearch": "Type to search anyone or anything",
  "message": "message",
  "messageAction": "Message",
  "messages": "Messages",
  "messageAdmin": "Message admin",
  "message_plural": "messages",
  "month": "Month",
  "more": "More",
  "mute": "Mute",
  "mutualGroups": "Mutual chats",
  "name": "Name",
  "needHelp": "Need help?",
  "new": "new",
  "newCard": "New card",
  "newChannel": "New channel",
  "newChat": "New chat",
  "newCommunity": "New community",
  "newGroup": "New chat",
  "newMessage": "new message",
  "newMessage_plural": "new messages",
  "newMessages": "New messages",
  "newOrganization": "New organization",
  "newRoom": "New room",
  "next": "Next",
  "noContacts": "No contacts yet",
  "noFollowers": "No followers yet",
  "noFollowing": "No following yet",
  "noNotifications": "No notifications yet",
  "noNotificationsDescripiton": "Comments in threads you are involved in will be right here",
  "noUndoneOperation": "This cannot be undone",
  "nobody": "Nobody",
  "nobodyFound": "Nobody found",
  "noiseDescription": "By using @All, you’re about to notify all {{chatType}} {{membersType}} even when they muted this chat. Please use it only for important messages",
  "noiseTitle": "Notify all {{membersType}}?",
  "none": "None",
  "notPaired": "Not paired",
  "nothingFound": "Nothing found",
  "notifications": "Notifications",
  "notificationsBadgeCounter": "Badge counter",
  "notificationsBadgeCounterDescription": "Push notification settings apply to all your mobile devices and don't affect desktop. Badge settings affect all your devices",
  "notificationsChannels": "Channels",
  "notificationsComments": "New comments",
  "notificationsCommunityGroups": "Community chats messages",
  "notificationsCountChats": "Count chats instead of messages",
  "notificationsDay": "Once a day",
  "notificationsEmail": "Email preferences",
  "notificationsEmailDescription": "When you’re busy or not online, Openland can send you email notifications about new messages",
  "notificationsHour": "Once an hour",
  "notificationsIncludeMuted": "Include muted chats",
  "notificationsMessages": "Messages notifications",
  "notificationsMin15": "Every 15 minutes",
  "notificationsMute": "Mute notifications",
  "notificationsNameAndText": "Show name and text",
  "notificationsNameOnly": "Show name only",
  "notificationsNever": "Never",
  "notificationsPreview": "Notifications preview",
  "notificationsSecretGroups": "Secret chats messages",
  "notificationsShow": "Show notifications",
  "notificationsUnmute": "Unmute notifications",
  "notificationsWeek": "Once a week",
  "off": "Off",
  "on": "On",
  "online": "online",
  "open": "Open",
  "openWallet": "Open wallet",
  "openland": "Openland",
  "openlandApps": "Openland apps",
  "organization": "Organization",
  "organizationDescription": "Publicly describe this organization for all to see",
  "organizationShortname": "People will be able to find your organization by this shortname",
  "organizationWithMember": "Organization   ·  {{count}} $t(member)",
  "organizationWithMember_plural": "Organization   ·  {{count}} $t(member_plural)",
  "other": "Other",
  "pairAccountPhone": "You can pair your account to any phone number and use it for login",
  "pairAccountEmail": "You can pair your account to any email address and use it for login",
  "payChoosePaymentMethod": "Choose correct payment method or add a new one to complete transaction",
  "payCompleteTransaction": "Complete transaction",
  "payment": "Payment",
  "paymentMethod": "Payment method",
  "paymentMethodUpdate": "Update payment method",
  "paymentMethodUpdateDescription": "Update payment method to complete previously failed transactions and enable new purchases",
  "paymentMethods": "Payment methods",
  "payments": "Payments",
  "paymentsFaq": "Payments FAQ",
  "paymentsHelp": "Payments help",
  "pending": "Pending",
  "period": "Period",
  "periodLongPerMonth": "per month",
  "periodLongPerWeek": "per week",
  "periodShortMonth": "mo",
  "periodShortWeek": "wk",
  "permissionCameraAndroid": "Allow Openland to take pictures and record video?",
  "permissionCameraIOS": "Allow Openland access to your camera",
  "permissionCameraInstructionsAndroid": "To upload a photo or video, allow Openland access to your camera and storage. Tap Settings > Permissions, and turn on Camera and Storage.",
  "permissionCameraInstructionsIOS": "Go to your device’s settings, tap Openland and turn on Camera",
  "permissionContactsAndroid": "Allow Openland to access your phone's contacts?",
  "permissionContactsIOS": "Allow Openland access to your contacts",
  "permissionContactsInstructionsAndroid": "To share photos, allow Openland access to your library. Tap Settings > Permissions, and turn on Contacts.",
  "permissionContactsInstructionsIOS": "Go to your device’s settings, tap Openland and turn on Contacts",
  "permissionGalleryAndroid": "Allow Openland to access your phone's storage?",
  "permissionGalleryIOS": "Allow Openland access to your photos",
  "permissionGalleryInstructionsAndroid": "To share photos, allow Openland access to your library. Tap Settings > Permissions, and turn on Storage.",
  "permissionGalleryInstructionsIOS": "Go to your device’s settings, tap Openland and turn on Photos",
  "permissionMicrophoneAndroid": "Allow Openland to access your microphone?",
  "permissionMicrophoneIOS": "Allow Openland access to your microphone",
  "permissionMicrophoneInstructionsAndroid": "To allow Openland access to your microphone, tap Settings > Permissions, and turn on Microphone.",
  "permissionMicrophoneInstructionsIOS": "Go to your device’s settings, tap Openland and turn on Microphone",
  "permissionStorageAndroid": "Allow Openland to access your phone's storage?",
  "permissionStorageInstructionsAndroid": "To share documents, allow Openland access to your storage. Tap Settings > Permissions, and turn on Storage.",
  "phone": "Phone",
  "phoneNumber": "Phone number",
  "pickMembers": "Pick members",
  "pin": "Pin",
  "pinned": "Pinned",
  "pinnedMessage": "Pinned message",
  "preferences": "Preferences",
  "premiumReactionDonate": "Donate $1",
  "premiumReactionDonated": "You’ve donated $1",
  "price": "Price",
  "primary": "primary",
  "privacy": "Privacy",
  "privacyAddToGroups": "Who can add me to chats",
  "privacyAdminsRight": "Admins can see my contacts",
  "privacyEmail": "Who can see my email",
  "privacyPhone": "Who can see my phone",
  "privacyPolicy": "Privacy policy",
  "privacyStatement": "By creating an account you are accepting our <TermsLink>Terms of service</TermsLink> and <PrivacyLink>Privacy policy</PrivacyLink>",
  "private": "Private",
  "privateCommunityDescription": "This community is invite-only",
  "privateOrganizationDescription": "This organization is invite-only",
  "profile": "profile",
  "public": "Public",
  "raiseHand": "Raise hand",
  "raiseHandQuesitonDescription": "Room admins will see that you want to speak",
  "raiseHandQuestion": "Raise hand?",
  "raisedHands": "Raised hands",
  "raisedHandsEmpty": "All quiet",
  "raisedHandsEmptyDescription": "Noone raised their hand",
  "rateApp": "Rate the app",
  "rateAppDescription": "Rate the app on {{store}}",
  "rateAppTitle": "Enjoying Openland?",
  "rateNow": "Rate now",
  "recent": "Recent",
  "remove": "Remove",
  "removeAdmin": "Remove admin",
  "removeAdminQuestion": "Dismiss {{name}} as admin?",
  "removeFromChannel": "Remove from channel",
  "removeFromGroup": "Remove from chat",
  "reply": "Reply",
  "replyMessages": "Reply messages",
  "report": "Report",
  "reportSent": "Report sent",
  "reportSpam": "Report spam",
  "reportSpamTitle": "Report spam",
  "reportsClone": "Clone of my profile",
  "reportsHarmful": "Harmful content",
  "reportsOffensive": "Offensive behaviour",
  "reportsOther": "Other",
  "reportsSpam": "Spam",
  "resend": "Resend",
  "revokeLink": "Revoke link",
  "room": "Room",
  "roomCreateDescription": "Tell everyone about the topic of conversation",
  "roomName": "Room name",
  "rooms": "Rooms",
  "roomsAdminLeft": "The last room admin left, the room will be closed now",
  "roomsFeedEmpty": "Talk about anything!",
  "roomsFeedEmptyDescription": "Create a new room and invite friends!",
  "sad": "Sad",
  "save": "Save",
  "savePhotoDefault": "Save to gallery",
  "savePhotoIOS": "Save to camera roll",
  "saved": "Saved",
  "savedMessages": "Saved messages",
  "search": "Search",
  "searchDefault": "Chats, people, and more",
  "searchDialogs": "Chats, messages, and more",
  "searchDiscover": "Chats, communities, and more",
  "searchEmpty": "Start typing message text you’re looking for",
  "searchMembers": "Search members",
  "searchMessages": "Search messages",
  "secretLabel": "It’s a secret {{entity}}",
  "seeAll": "See all",
  "select": "Select",
  "selectCountry": "Select country",
  "selectMonth": "Please select month",
  "selectedMessage": "message selected",
  "selectedMessageDefault": "Select messages",
  "selectedMessage_plural": "messages selected",
  "send": "Send",
  "sendMessage": "Send message",
  "sender": "Sender",
  "serviceMessages": "Service messages",
  "serviceMessagesDescription": "Choose what messages to get",
  "serviceMessagesJoins": "New member joins",
  "serviceMessagesLeaves": "Member leaves",
  "settings": "Settings",
  "share": "Share",
  "shareChallenges": "Choose a chat and share your challenges",
  "shareLink": "Share link",
  "shareNothing": "Nothing to share {{emoji}}",
  "sharePhoto": "Share photo",
  "shareWith": "Share with",
  "shareWithQuestion": "Share with {{title}}?",
  "shared": "Shared",
  "sharedMediaEmptyMedia": "No media yet",
  "sharedMediaEmptyFiles": "No files yet",
  "sharedMediaEmptyLinks": "No links yet",
  "sharedMediaEmptyDescription": "{{mediaType}} you’ll send and receive in this chat will appear here",
  "sharedMediaTitle": "Media, files, links",
  "shortThousand": "K",
  "shortname": "Shortname",
  "shortnameDescription": "This link opens a chat with you:\nopenland.com/{{path}}",
  "shortnameUserDescription": "You can choose a username in Openland.\nOther people will be able to find you by this username, and mention you with this username in chats.\n\nYou can use a-z, 0-9 and underscores.\nMinimum length is {{minLength}} characters.\n\n{{username}}",
  "showMore": "Show more",
  "signOut": "Sign out",
  "signOutDescription": "Are you sure you want to sign out?",
  "signOutFromApp": "Sign out from app",
  "signinMethods": "Sign-in methods",
  "signupSubtitle": "Help others recognize you",
  "signupTitle": "Introduce yourself",
  "skip": "Skip",
  "socialSharingImage": "Social sharing image",
  "socialSharingImageDescription": "Choose an image for sharing invite to the chat on social networks",
  "someone": "someone",
  "sound": "Sound",
  "speaker": "Speaker",
  "standard": "Standard",
  "start": "Start",
  "startRoom": "Start room",
  "status": "Status",
  "sticker": "sticker",
  "stickerAdd": "Add $t(sticker)",
  "stickerAdd_plural": "Add $t(sticker_plural)",
  "stickerDelete": "Delete $t(sticker)",
  "stickerDelete_plural": "Delete $t(sticker_plural)",
  "stickerPackDelete": "Delete {{title}} stickerpack?",
  "stickerPackPrivate": "This sticker pack is private",
  "stickerPackRemoved": "Sticker pack removed or temporary unavailable",
  "stickerPackUnavailable": "Sticker pack is unavailable",
  "sticker_plural": "stickers",
  "stickers": "Stickers",
  "stickersClearRecent": "Clear recent stickers?",
  "stickersDeletePack": "Delete {{title}} stickers?",
  "stickersDiscover": "Discover stickers",
  "stickersDiscoverDescription": "Your stickers will be displayed here",
  "submitCodeNotReceived": "Haven’t received?",
  "submitCodeSent": "We just sent it to {{receiver}}.",
  "submitCodeWait": "Wait for {{seconds}} sec",
  "subscriptionCancel": "Cancel subscription",
  "subscriptionCancelDescription": "If you cancel now, you can still access\nthe chat until {{expireDate}}",
  "subscriptions": "Subscriptions",
  "subscriptionsEmpty": "No subscriptions yet",
  "subscriptionsEmptyDescription": "Join any premium chats, and they will appear here",
  "subscriptionsStarted": "Next bill on {{date}}",
  "subscriptionsPaymentFailed": "Payment failed",
  "subscriptionsCanceled": "Expires on {{date}}",
  "subscriptionsExpired": "Expired on {{date}}",
  "subscriptionsPeriod": "period",
  "suggestedChats": "Here some chats we suggested for you",
  "superEdit": "Super edit",
  "superadminSettings": "Superadmin settings",
  "termsOfService": "Terms of service",
  "theme": "Theme",
  "themeAccent": "Accent",
  "themeDark": "Dark",
  "themeFeaturedMark": "Show featured mark",
  "themeLargeEmoji": "Show large emoji",
  "themeLight": "Light",
  "themePreviewAnswer": "I’m fine. Thanks!",
  "themePreviewQuestion": "Hello! How are you?",
  "themeSystem": "System",
  "themeTrueDark": "True Dark",
  "threadFollow": "Follow thread",
  "threadUnfollow": "Unfollow thread",
  "thumbsUp": "Thumbs Up",
  "totalAmount": "Total amount",
  "transacitonFailed": "Transaction failed",
  "transactions": "Transactions",
  "tryAgain": "Try again",
  "type": "Type",
  "typing": "typing",
  "typingFile": "sending a file",
  "typingPhoto": "sending a photo",
  "typingSticker": "picking a sticker",
  "typingVideo": "uploading a video",
  "unblockPerson": "Unblock person",
  "unfollow": "Unfollow",
  "unfollowed": "Unfollowed",
  "unmute": "Unmute",
  "unmuteShort": "Unmute",
  "unpin": "Unpin",
  "unpinned": "Unpinned",
  "unsupportedMessage": "Message is not supported on your version of Openland.\nPlease update the app to view it.",
  "updateAppDescription": "Upgrade your app to get great new features",
  "updateAppTitle": "Update available",
  "updateNow": "Update now",
  "upload": "Upload",
  "uploadPhoto": "Upload photo",
  "userGuide": "User guide",
  "username": "Username",
  "validationAmountMax": "${{amount}} maximum",
  "validationAmountMin": "${{amount}} minimum",
  "validationDate": "Please enter valid date",
  "validationDescriptionMaxChars": "Your description should be less than {{num}} characters",
  "validationEnterName": "Please enter a name",
  "validationEnterPrice": "Please enter a valid price",
  "validationLink": "Enter a valid link",
  "validationMaxChars": "Must have no more than {{num}} chars",
  "validationMinChars": "Must have at least {{num}} chars",
  "validationNumbersOnly": "Numbers only",
  "validationProfileName": "Please, provide your name. This information is part of your public profile.",
  "validationShortname": "Can only contain a-z, 0-9, and underscores",
  "version": "Version",
  "video": "Video",
  "viewChannel": "View channel",
  "viewGroup": "View chat",
  "viewMessages": "View messages",
  "viewProfile": "View profile",
  "visibility": "Visibility",
  "visibilityPublic": "Public",
  "visibilityPublicDescription": "Visible in chat search",
  "visibilitySecret": "Secret",
  "visibilitySecretDescription": "Only people with invite link can see it",
  "waitingForNetwork": "Waiting for network…",
  "wallet": "Wallet",
  "walletBasic": "Basic",
  "walletDeposit": "Deposit",
  "walletDonation": "Donation",
  "walletEmpty": "No earnings yet",
  "walletIncome": "Income",
  "walletPayment": "Payment",
  "walletPremiumReaction": "Premium reaction",
  "walletSubscription": "Subscription",
  "walletTopUpBalance": "Top up balance",
  "walletTransaction": "Transaction",
  "walletTransfer": "Transfer",
  "warningAddMembers": "Do you know people you are adding?",
  "warningAddMembersDescription": "Please, only add people whom you know will be interested in your chat",
  "warningPremiumReaction": "Premium reaction",
  "warningPremiumReactionDescription": "Express your support with a donation to the author",
  "website": "Website",
  "week": "Week",
  "welcomeMessage": "Welcome message",
  "welcomeMessageAllow": "Allow welcome message",
  "welcomeMessageDescription": "Send automatic tet-a-tet message to every new member of the chat",
  "whatToJoin": "What to join",
  "withdraw": "Withdraw",
  "withdrawFunds": "Withdraw funds",
  "withdrawFundsDescription": "To request funds withdrawal ($50 minimum) message Openland support for instructions",
  "wow": "Wow",
  "year": "Year",
  "yesSure": "Yes, I am sure",
  "you": "You",
  "yourBalance": "Your balance",
  "yourEmail": "Your email",
  "yourMessaage": "Your message",
  "yourPhone": "Your phone",
  "dateTime": {
    "today": "Today",
    "yesterday": "Yesterday",
    "now": "now",
    "at": "at",
    "shortMinute": "m",
    "shortHour": "h",
    "shortDay": "d",
    "justNow": "just now",
    "lastSeenYesterday": "last seen yesterday",
    "lastSeenTwoDays": "last seen two days ago",
    "lastSeenLongTime": "last seen long time ago",
    "lastSeenDefault": "last seen",
    "yearsOldShort": "y. o.",
    "yearsOldShort_plural": "y. o.",
  }
};
