// import { LocalizationSchema } from "../schema";

export const ru: any = {
  "about": "Описание",
  "aboutOpenland": "Об Openland",
  "aboutUs": "О нас",
  "accessDenied": "Доступ запрещен",
  "accessDeniedGroup": "Не удалось открыть группу",
  "accessDeniedGroupDescription": "Этой группы не существует или у вас нет разрешения на её просмотр",
  "accessSuspended": "Ваш доступ к “{{title}}” приостановлен",
  "accessSuspendedDescription": "Чтобы сохранить доступ к группе по подписке, вам необходимо завершить оплату",
  "accountPrivacy": "Аккаунт и приватность",
  "active": "Активные",
  "add": "Добавить",
  "addCard": "Добавить карту",
  "addDetailsOptional": "Добавить детали (optional)",
  "addPeople": "Добавить участников",
  "addPeopleFree": "Добавить участников бесплатно",
  "addToGroups": "Добавить в группы",
  "admin": "Администратор",
  "allow": "Разрешить",
  "allowContacts": "Разрешить приложению \"Openland\" доступ к контактам",
  "allowContactsDescription": "Найдите друзей, которые уже используют Openland. Для этого разрешите загружать и сохранять ваши контакты в Политике приватности",
  "allowed": "Разрешено",
  "amount": "Сумма",
  "andOthers": "и {{num}} других",
  "angry": "Злой",
  "appearance": "Вид",
  "applyLink": "Ссылка на форму заявки",
  "applyLinkDescription": "Ссылка на форму заявки или информацию",
  "applyLinkUse": "Использовать ссылку на форму заявки",
  "applyToJoin": "Отправить заявку на вступление",
  "attachDocumentAndroid": "Документ",
  "attachDocumentIOS": "Отправить документ",
  "attachDonationAndroid": "Донат",
  "attachDontaionIOS": "Отправить донат",
  "attachPhotoAndroid": "Галерея",
  "attachPhotoIOS": "Выбрать из галереи",
  "attachRecordVideo": "Записать видео",
  "attachTakePhoto": "Выбрать фотографию",
  "attachVideo": "Видеогалерея",
  "audio": "Аудиозапись",
  "becomeListener": "Стать слушателем",
  "billing": "Счёт",
  "billingProblem": "Проблема со счётом",
  "billingProblemDescription": "Платеж из недавних ваших покупок или подписок не удался. Пожалуйста, обновите свой способ оплаты, чтобы сохранить доступ к платным группам.",
  "birthday": "День рождения",
  "blockPerson": "Заблокировать пользователя",
  "blocked": "Заблокированные пользователи",
  "blockedByYou": "Вы заблокировали этого пользователя",
  "blockedSelf": "Вы заблокированы",
  "bot": "Бот",
  "calendarOpen": "Открыть в календаре",
  "callLink": "Ссылка на звонок",
  "callMembers": "$t(member) на звонке",
  "callMembersDefault": "На звонке",
  "callMembers_0": "$t(member_0) на звонке",
  "callMembers_1": "$t(member_1) на звонке",
  "callMembers_2": "$t(member_2) на звонке",
  "camera": "Камера",
  "cancel": "Отмена",
  "cardExpired": "Истекает {{expireDate}}",
  "cardValid": "Действителен до {{validDate}}",
  "change": "Изменить",
  "channel": "канал",
  "chat": "Чат",
  "chatRecommendations": "Получить рекомендации в чате",
  "chooseSender": "Выберите отправителя",
  "chooseShortname": "Выберите короткое имя, чтобы другие пользователи могли вас найти и упомянуть {{entityType}}",
  "clear": "Понятно",
  "close": "Закрыть",
  "closeRoom": "Закрыть комнату",
  "collections": "Коллекции",
  "collectionsCoversBy": "Выбор редактора и обложки коллекций",
  "comment": "Комментарий",
  "commentDelete": "Удалить комментарий",
  "commentDeleteDescription": "Удалить этот комментарий для всех? Это дейстсвие нельзя будет отменить.",
  "comments": "Комментарии",
  "community": "Сообщество",
  "communityDescription": "Опишите это сообщество",
  "communityPrivateDescription": "Участники могут приглашать пользователей",
  "communityTypeDescription": "Назначил создатель",
  "communityWithMember": "Сообщество   ·  {{count}} $t(member)",
  "communityWithMember_0": "Сообщество   ·  {{count}} $t(member_0)",
  "communityWithMember_1": "Сообщество   ·  {{count}} $t(member_1)",
  "communityWithMember_2": "Сообщество   ·  {{count}} $t(member_2)",
  "community_0": "Сообщество",
  "community_1": "Сообщества",
  "community_2": "Сообществ",
  "confirm": "Подтврердить",
  "connecting": "Соединение",
  "contactUs": "Связаться с нами",
  "contacts": "Контакты",
  "contactsAdd": "Добавить в контакты",
  "contactsImport": "Импортировать контакты",
  "contactsImportDescription": "Импортируйте контакты с вашего устройства, чтобы найди знакомых, которые используют Openland",
  "contactsRemove": "Удалить из контактов",
  "contactsSave": "Сохранить в контакты",
  "contentMissingOrRestricted": "Этого контента не существует или у вас нет доступа",
  "contentUnavailable": "Контент недоступен",
  "continue": "Продолжить",
  "continueWithEmail": "Продолжить с почтой",
  "continueWithPhone": "Продолжить с номером телефона",
  "conversationConnect": "Рад подключиться!",
  "conversationDelete": "Удалить диалог",
  "conversationDeleteBoth": "Удалить для меня и {{userName}}",
  "conversationDeleteDescription": "Вы уверены, что хотите удалить диалог? Это действие невозможно отменить.",
  "conversationHello": "Привет, {{name}}!",
  "conversationNoMessages": "Сообщений пока нет",
  "conversationStart": "Начать диалог с {{name}}",
  "copied": "Скопировано",
  "copy": "Скопировать",
  "copyLink": "Скопировать ссылку",
  "correspondents": "Корреспонденты",
  "country": "Страна",
  "create": "Создать",
  "createAccount": "Создать аккаунт",
  "createCommunity": "Создать сообщестсво",
  "createGroup": "Создать группу",
  "createGroupFree": "Бесплатно",
  "createGroupFreeDescription": "Участники присоединятся бесплатно",
  "createGroupPaid": "Единоразовая оплата",
  "createGroupPaidDescription": "Участники платят один раз, чтобы присоединиться",
  "createGroupSubscription": "Подписка",
  "createGroupSubscriptionDescription": "Регулярная оплата участников",
  "createNew": "Создать новую",
  "createOrganizationDescription": "Пожалуйста, укажите название органиации и логотип",
  "createOrganizationPublic": "Публичная",
  "createOrganizationPublicDescription": "Видна в поиске",
  "createOrganizationSecret": "Секретная",
  "createOrganizationSecretDescription": "Только люди, у которых есть ссылка-приглашение, могут увидеть организацию",
  "custom": "Индивиндуальная настройка",
  "dateAndTime": "Дата и время",
  "day": "День",
  "defaultGroups": "Группы по умолчанию",
  "defaultGroupsDescription": "Выберите группы, к которым автоматически присоединятся все новые участники сообщества",
  "delete": "Удалить",
  "deleteCard": "Удалить карту",
  "deleteCardDescription": "Это действие не может быть отменено",
  "deleteCardQuestion": "Удалить карту?",
  "deleteChannel": "Удалить канал",
  "deleteChannelQuestion": "Удалить канал?",
  "deleteCommunity": "Удалить сообщество",
  "deleteCommunityQuestion": "Удалить сообщество?",
  "deleteGroup": "Удалить группу",
  "deleteGroupQuestion": "Удалить группу?",
  "deleteMessageDescription": "Сообщение будет удалено от всех. Это дейcтсвие невозможно отменить",
  "deleteMessageQuestion": "Удалить сообщение?",
  "deleteMessagesDescription": "Сообщения будут удалены для всех. Это дейcтвсие невозможно отменить",
  "deleteOrganization": "Удалить организацию",
  "deleteOrganizationQuestion": "Удалить организацию?",
  "deletePerson": "Удалить человека",
  "deletePinnedMessageQuestion": "Удалить закрепленное сообщение?",
  "deleteUser": "Удалить пользователя",
  "description": "Описание",
  "dialogAllChats": "Все чаты",
  "dialogChats": "Чаты",
  "dialogDirect": "Личные сообщения",
  "dialogGroups": "Группы",
  "dialogUnread": "Непрочитанные",
  "directMessages": "Личные сообщения",
  "disallowed": "Запрещено",
  "discover": "Discover",
  // "discoverChannel": "Только администраторы могут писать сообщения, другие могут комментировать",
  "discoverChannel": "Администраторы пишут, остальные комментируют",
  "discoverChat": "Публичный, секретный или платный чат",
  "discoverChats": "Откройте для себя чаты",
  "discoverFindChats": "Найдите больше чатов",
  "discoverGetRecommendations": "Получите рекомендации по вашим интересам",
  "discoverCommunity": "Место для ваших чатов и каналов",
  "discoverGroups": "ткройте для себя группы",
  "discoverNewCommunities": "Новые сообщества",
  "discoverNewGroups": "Новые группы",
  "discoverPopular": "Популярные сейчас",
  "discoverRecommendations": "Рекомендации",
  "discoverTopCommunities": "Топ сообществ",
  "discoverTopGroups": "Топ групп",
  "discoverTopPremium": "Toп премиум",
  "dismiss": "Разжаловать",
  "dismissAdmin": "Разжаловать админимтратора",
  "dismissAdminQuestion": "Разжаловать администратора {{name}}?",
  "document": "Документ",
  "donate": "Пожертвование",
  "donateToUser": "Сделать пожертвование для {{name}}",
  "done": "Выполнено",
  "edit": "Изменить",
  "editChannel": "Изменить канал",
  "editComment": "Изменить комменарий",
  "editCommunity": "Изменить сообщество",
  "editGroup": "Изменить группу",
  "editInfo": "Изменить информацию",
  "editMessage": "Изменить сообщение",
  "editOrganization": "Изменить организацию",
  "editPersonalVisibility": "Изменить номер телефона/почту и их видимость \nв ",
  "editProfile": "Изменить профиль",
  "editRoom": "Изменить комнату",
  "email": "Почта",
  "emailPreferences": "Уведомления на почте",
  "end": "Закончить",
  "endRoom": "Завершить комнату",
  "endRoomDescription": "Комната закроется, если выйдет последний администратор. Вернитесь и назначьте новых админитстраторов, если вы хотите сохранить комнату",
  "enterCode": "Введите код",
  "enterDay": "Пожалуйста, введите день",
  "enterValidDate": "Пожалуйста, введите действительную дату",
  "error": "Ошибка",
  "errorAbstract": "Что-то пошло не так",
  "errorCardInvalid": "Неверный номер карты",
  "errorFileUpload": "Ошибка при загрузке файла",
  "errorJoinChat": "Не получилось присоединиться к {{chatType}}",
  "errorNoInvite": "Приглашение не найдено",
  "errorRepliesDisabled": "Ответы в этом чате отключены",
  "errorUnknown": "Неизвестная ошибка",
  "everyone": "Каждый",
  "expired": "Истекшие",
  "featured": "Рекомендуемые",
  "files": "Файлы",
  "findChats": "Найдите полезные для вас чаты",
  "findFriends": "Найдите друзей",
  "firstName": "Имя",
  "flip": "Перевернуть",
  "follow": "Подписаться",
  "followed": "Вы подписаны",
  "follower": "Подписчик",
  "follower_0": "Подписчик",
  "follower_1": "Подписчика",
  "follower_2": "Подписчиков",
  "following": "Подписки",
  "forward": "Переслать",
  "forwardMessages": "Пересланное сообщение",
  "forwardTo": "Переслать",
  "forwardedMessage": "Пересланное сообщение",
  "forwardedMessage_0": "Пересланных сообщений",
  "forwardedMessage_1": "Пересланных сообщений",
  "forwardedMessage_2": "Пересланных сообщений",
  "free": "Бесплатно",
  "fromChat": "От",
  "fromChatWith": "Из чата с",
  "getHelp": "Получить помощь от команды Openland",
  "goBack": "Вернуться",
  "gotIt": "Понятно!",
  "group": "группа",
  "groupCalls": "Групповые звонки",
  "groupCallsChoose": "Выбрать, какой звонок использовать",
  "groupCallsCustom": "Пользовательская ссылка на звонок",
  "groupCallsExternal": "Ссылка на внешный звонок, например, на Zoom, Google Meet или любой другой сервис",
  "groupCallsNone": "Не использовать звонки",
  "groupCallsStandard": "Стандартная комната в Openland",
  "groupPriceDescription": "Настройте монетизацию своей группы. Все изменеия коснутся только новых участников",
  "group_0": "группа",
  "group_1": "группы",
  "group_2": "груп",
  "groups": "Группы",
  "groupsColon": "Группы:",
  "haha": "Ха-ха",
  "helpAndFeedback": "Помощь и обратная связь",
  "illustrationsBy": "Продуктовые иллюстрации от",
  "info": "Информация",
  "invite": "Приглашение",
  "inviteAccept": "Принять приграшение",
  "inviteByUser": "{{name}} приглашает вас присоединиться к {{title}}",
  "inviteContacts": "Приглашайте людей из списка ваших контактов или добавляйте людей вручную из профиля, и они появятся здесь",
  "inviteFriends": "Пригласить друзей",
  "inviteFriendsDescription": "Не нашли своих друзей в Openalnd? Давайте пригласим их, чтобы оставаться на связи",
  "inviteJoinChannel": "Приглашайте людей присоединиться к каналу",
  "inviteJoinConversation": "Приглашайте людей присоединиться к разговору",
  "inviteLinkChannel": "Ссылка на канал",
  "inviteLinkCommunity": "Ссылка-приглашение для сообщества",
  "inviteLinkCommunityDescription": "Люди могут присоединиться к сообществу, перейдя по этой ссылке. Вы можете в любое время обновить ссылку",
  "inviteLinkDescription": "Любой, у кого есть ссылка, может присоединиться к группе",
  "inviteLinkGroup": "Ссылка на группу",
  "inviteLinkOrganization": "Ссылка-приглашение в организацию",
  "inviteLinkOrganizationDescription": "Люди могут присоединиться к организации, перейдя по этой ссылке. Вы можете в любое время обновить ссылку",
  "inviteRevoked": "Это приглашение было отозвано",
  "inviteTo": "Пригласить в {{title}}",
  "inviteWithLink": "Пригласить по ссылке",
  "join": "Присоединиться",
  "joinAll": "Присоединиться ко всем",
  "joinChannel": "Присоединиться к каналу",
  "joinChat": "Присоединитья к {{chatType}}",
  "joinGroup": "Присоединиться к группе",
  "joinPaidChat": "Присоединиться за {{amount}}",
  "joinPaidChatWithPeriod": "Присоединиться за {{amount}} / {{periodShort}}",
  "joinRoom": "Присоединиться к комнате",
  "kickCommunity": "Удалить из сообщества",
  "kickCommunityQuestion": "Удалить {{name}} из сообщества?",
  "kickOrganization": "Удалить из организации",
  "kickOrganizationQuestion": "Удалить {{name}} из организации?",
  "kickUserFromChannel": "Удалить {{name}} из канала?",
  "kickUserFromGroup": "Удалить {{name}} из группы?",
  "kickWarning": "Они будут удалены из всех внутренних чатов",
  "lastName": "Фамилия",
  "leave": "Выйти",
  "leaveChannel": "Покинуть канал",
  "leaveChannelQuestion": "Покинуть канал?",
  "leaveChatDescription": "Возможно, у вас не получится присоединиться снова",
  "leaveChatPremiumDescription": "Выход из группы только удаляет ее из списка чатов. Чтобы отменить подписку, перейдите в раздел Подписки на вкладке \"Настройки\" и отмените ее оттуда.",
  "leaveCommunity": "Покинуть сообщество",
  "leaveCommunityQuestion": "Покинуть сообщество?",
  "leaveGroup": "Покинуть группу",
  "leaveGroupQuestion": "Покинуть группу?",
  "leaveOrganization": "Покинуть организацию",
  "leaveOrganizationQuestion": "Покинуть организацию?",
  "leaveWarning": "Возможно, у вас не получится присоединиться снова",
  "licenses": "Лицензии",
  "like": "лайк",
  "like_0": "лайк",
  "like_1": "лайка",
  "like_2": "лайков",
  "liked": "Вы лайкнули",
  "linkCopied": "Ссылка скопирована",
  "links": "Ссылки",
  "listeners": "Слушатели",
  "loading": "Загрузка",
  "location": "Местоположение",
  "loginCodeDescription": "Мы вышлем вам код для входа",
  "loginEmailQuestion": "Какая у вас электронная почта?",
  "loginPhoneQuestion": "Какой у вас номер телефон?",
  "loginSigninCode": "Введите код входа",
  "loginSignupCode": "Введите код регистрации",
  "loginPhoneConfirm": "Этот номер телефона верный?",
  "loginTitle": "Современная социальная сеть\nсоздана для вас, а не для рекламодателей",
  "love": "Нравится",
  "make": "Сделать",
  "makeAdmin": "Назначить администратором",
  "makeAdminQuestion": "Назначить {{name}} администратором?",
  "makeDonation": "Пожертвовать",
  "makeListener": "Сделать слушателем",
  "makePrimary": "Сделать основным",
  "makeSpeaker": "Сделать спикером",
  "maybeLater": "Позже",
  "media": "Медиа",
  "member": "участник",
  "member_0": "участник",
  "member_1": "участника",
  "member_2": "участников",
  // "member_interval": "(2-4){участника};(5-inf){участников};",
  "membersColon": "Участники:",
  "mentionsMissing": "Не найдено в этой группе",
  "mentionsSearch": "Введите для поиска кого-либо или чего-либо",
  "message": "сообщение",
  "messageAdmin": "Написать администратору",
  "message_0": "сообщение",
  "message_1": "сообщения",
  "message_2": "сообщений",
  "month": "Месяц",
  "more": "Еще",
  "mute": "Без звука",
  "mutualGroups": "Общие группы",
  "name": "Название",
  "needHelp": "Нужна помощь?",
  "new": "новое",
  "newCard": "Новая карта",
  "newChannel": "Новый канал",
  "newChat": "Новый чат",
  "newCommunity": "Новое сообщество",
  "newGroup": "Новая группа",
  "newMessage": "новое сообщение",
  "newMessage_0": "новое сообщение",
  "newMessage_1": "новых сообщений",
  "newMessage_2": "новых сообщений",
  "newOrganization": "Новая организация",
  "newRoom": "Новая комната",
  "next": "Дальше",
  "noContacts": "Пока нет контактов",
  "noFollowers": "Пока нет подписчиков",
  "noFollowing": "Пока нет подписок",
  "noNotifications": "Пока нет уведомлений",
  "noNotificationsDescripiton": "Комментарии в темах, в которых вы участвуете, будут здесь",
  "noUndoneOperation": "Это нельзя будет отменить",
  "nobody": "Никто",
  "nobodyFound": "Никто не найден",
  "noiseDescription": "Используя @All, вы уведомите всех {{chatType}} {{membersType}}, даже если они отключили уведомления от этого чата. Пожалуйста, используйте его только для важных сообщений",
  "noiseTitle": "Уведомить всех {{membersType}}?",
  "none": "Никто",
  "notPaired": "Не добавлено",
  "nothingFound": "Ничего не найдено",
  "notifications": "Уведомления",
  "notificationsBadgeCounter": "Счётчик сообщений",
  "notificationsBadgeCounterDescription": "Настройки Push-уведомлений применяются ко всем вашим мобильным устройствам и не влияют на версию для ПК. Настройки счетчика сообщений влияют на все устройства",
  "notificationsChannels": "Каналы",
  "notificationsComments": "Новые комментарии",
  "notificationsCommunityGroups": "Сообщения групп сообщества",
  "notificationsCountChats": "Считать количество непрочитанных чатов вместо сообщений",
  "notificationsDay": "Раз в день",
  "notificationsEmail": "Настройки электронной почты",
  "notificationsEmailDescription": "Когда вы заняты или не в сети, Openland может отправлять вам на почту уведомления о новых сообщениях. Мы будем использовать {{email}} для уведомлений",
  "notificationsHour": "Раз в чат",
  "notificationsIncludeMuted": "Учитывать чаты с режиме \"Без звука\"",
  "notificationsMessages": "Уведомления о сообщениях",
  "notificationsMin15": "Каждые 15 минут",
  "notificationsMute": "Отключить уведомления",
  "notificationsNameAndText": "Показывать название чата и текст сообщения",
  "notificationsNameOnly": "Показывать только название чата",
  "notificationsNever": "Никогда",
  "notificationsPreview": "Предварительный просмотр уведомлений",
  "notificationsSecretGroups": "Сообщения из секретных групп",
  "notificationsShow": "Показывать уведомления",
  "notificationsUnmute": "Включить уведомления",
  "notificationsWeek": "Раз в неделю",
  "off": "Выключить",
  "on": "Включить",
  "online": "в сети",
  "open": "Открыть",
  "openWallet": "Открыть кошелёк",
  "openland": "Openland",
  "openlandApps": "Приложения Openland",
  "organization": "Организация",
  "organizationDescription": "Опишите эту организацию",
  "organizationShortname": "Люди смогут найти вашу организацию по этому короткому имени",
  "organizationWithMember": "Организация   ·  {{count}} $t(member)",
  "organizationWithMember_0": "Организация   ·  {{count}} $t(member_0)",
  "organizationWithMember_1": "Организация   ·  {{count}} $t(member_1)",
  "organizationWithMember_2": "Организация   ·  {{count}} $t(member_2)",
  "other": "Другое",
  "pairAccountPhone": "Вы можете связать свою учетную запись с любым номером телефона и использовать его для входа",
  "pairAccountEmail": "Вы можете связать своб учетную запись с любым адресом электронной почты и использовать его для входа",
  "payChoosePaymentMethod": "Выберите правильный способ оплаты или добавьте новый для завершения транзакции",
  "payCompleteTransaction": "Завершить транзакцию",
  "payment": "Оплата",
  "paymentMethod": "Способ оплаты",
  "paymentMethodUpdate": "Измените способ оплаты",
  "paymentMethodUpdateDescription": "Обновите способ оплаты, чтобы завершить ранее неудачные транзакции и совершить новые покупки",
  "paymentMethods": "Способы оплаты",
  "payments": "Оплата",
  "paymentsFaq": "FAQ по оплате",
  "paymentsHelp": "Помощь с оплатой",
  "pending": "Ожидание",
  "period": "Период",
  "periodLongPerMonth": "в месяц",
  "periodLongPerWeek": "в неделю",
  "periodShortMonth": "мес",
  "periodShortWeek": "нед",
  "permissionCameraAndroid": "Разрешить Openland делать фото и записывать видео?",
  "permissionCameraIOS": "Разрешить Openland доступ к камере",
  "permissionCameraInstructionsAndroid": "Чтобы загрузить фото или видео, разрешите Openland доступ к вашей Камере и Хранилищу. Откройте Настройки > Приложения и уведомления > Openland > Разрешения, предоставьте доступ к Камере и Хранилищу.",
  "permissionCameraInstructionsIOS": "Откройте настройки на вашем устройстве, выберите Openland и предоставьте доступ к Камере",
  "permissionContactsAndroid": "Разрешить Openland доступ к вашему списку контактов?",
  "permissionContactsIOS": "Разрешить Openland доступ к вашим контактам",
  "permissionContactsInstructionsAndroid": "Чтобы поделиться контактами, разрешите Openland доступ к вашим Контактам. Откройте Настройки > Приложения и уведомления > Openland > Разрешения, предоставьте доступ к Контактам",
  "permissionContactsInstructionsIOS": "Откройте Настройки на вашем устройстве, выберите Openland и предоставьте доступ к Контактам",
  "permissionGalleryAndroid": "Разрешить Openland доступ к хранилищу телефона?",
  "permissionGalleryIOS": "Разрешить Openland доступ к вашим фото",
  "permissionGalleryInstructionsAndroid": "Чтобы поделиться фото, разрешите Openland доступ к вашей Библиотеке. Откройте Настройки > Приложения и уведомления > Openland > Разрешения, предоставьте доступ к Хранилищу.",
  "permissionGalleryInstructionsIOS": "Откройте Настройки на вашем устройстве, выберите Openland и предоставьте доступ к Фото",
  "permissionMicrophoneAndroid": "Разрешить Openland доступ к вашему микрофону?",
  "permissionMicrophoneIOS": "Разрешить Openland доступ к вашему микрофону",
  "permissionMicrophoneInstructionsAndroid": "Чтобы разрешить Openland доступ к вашему Микрофону, откройте Настройки > Приложения и уведомления > Openland > Разрешения, предоставьте доступ к Микрофону.",
  "permissionMicrophoneInstructionsIOS": "Откройте Настройки на вашем устройстве, выберите Openland и предоставьте доступ к Микрофону",
  "permissionStorageAndroid": "Разрешить Openland доступ к хранилищу телефона?",
  "permissionStorageInstructionsAndroid": "Чтобы поделиться документами, разрешите Openland доступ к вашему Хранилищу. Откройте Настройки > Приложения и уведомления > Openland > Разрешения, предоставьте доступ к Хранилищу.",
  "phone": "Телефон",
  "phoneNumber": "Номер телефона",
  "pickMembers": "Выбрать участников",
  "pin": "Закрепить",
  "pinned": "Закреплено",
  "pinnedMessage": "Закрепленное сообщение",
  "preferences": "Предпочтения",
  "premiumReactionDonate": "Пожертвовать $1",
  "premiumReactionDonated": "Вы пожертвовали $1",
  "price": "Цена",
  "primary": "Основной",
  "privacy": "Конфиденциальность",
  "privacyAddToGroups": "Кто может добавлять меня в группы",
  "privacyAdminsRight": "Администраторы могут видеть мои контакты",
  "privacyEmail": "Кто может видеть email",
  "privacyPhone": "Кто может видеть мой номер телефона",
  "privacyPolicy": "Политика конфиденциальности",
  "privacyStatement": "Создавая учетную запись, вы принимаете наши <TermsLink>Условия использования</TermsLink> и <PrivacyLink>Политику конфиденциальности</PrivacyLink>",
  "private": "Частный", // Частное, частная - окончание зависит от контекста
  "privateCommunityDescription": "Вход в это сообщество только по приглашению",
  "privateOrganizationDescription": "Вход в эту организацию только по приглашению",
  "profile": "профиль",
  "public": "Публичный", // Публичное - окончание зависит от контекста
  "raiseHand": "Поднять руку",
  "raiseHandQuesitonDescription": "Администраторы комнаты увидят, что вы желаете взять слово",
  "raiseHandQuestion": "Поднять руку?",
  "raisedHands": "Поднятые руки",
  "raisedHandsEmpty": "Всё тихо",
  "raisedHandsEmptyDescription": "Никто не поднял руку",
  "rateApp": "Оцените приложение",
  "rateAppDescription": "Оценить приложение в {{store}}",
  "rateAppTitle": "Нравится Openland?",
  "rateNow": "Сейчас",
  "recent": "Недавно",
  "remove": "Удалить",
  "removeAdmin": "Убрать администратора",
  "removeAdminQuestion": "Убрать {{name}} с поста администратора?",
  "removeFromChannel": "Удалить из канала",
  "removeFromGroup": "Удалить из группы",
  "reply": "Ответить",
  "replyMessages": "Ответ на сообщение",
  "report": "Пожаловаться",
  "reportSent": "Жалоба отправлена",
  "reportSpam": "Пожаловаться на спам",
  "reportSpamTitle": "Жалоба на спам",
  "reportsClone": "Копия моего профиля",
  "reportsHarmful": "Вредный контент",
  "reportsOffensive": "Оскорбительное поведение",
  "reportsOther": "Другое",
  "reportsSpam": "Спам",
  "resend": "Отправить заново",
  "revokeLink": "Обновить ссылку",
  "room": "Комната",
  "roomCreateDescription": "Расскажите всем о теме разговора",
  "roomName": "Название комнаты",
  "rooms": "Комнаты",
  "roomsAdminLeft": "Последний администратор покинул комнату, сейчас она закроется",
  "roomsFeedEmpty": "Обсудите что-нибудь!",
  "roomsFeedEmptyDescription": "Создать новую комнату и пригласить друзей!",
  "sad": "Грустный",
  "save": "Сохранить",
  "savePhotoDefault": "Сохранить в галерею",
  "savePhotoIOS": "Сохранить в фотопоток",
  "saved": "Сохранено",
  "savedMessages": "Сохраненные сообщения",
  "search": "Поиск",
  "searchDefault": "Группы, люди, и т.д.",
  "searchDialogs": "Чаты, сообщения и т.д.",
  "searchDiscover": "Группы, сообщества и т.д.",
  "searchEmpty": "Начните вводить текст сообщения, которое вы ищете",
  "searchMembers": "Искать по участникам",
  "searchMessages": "Искать по сообщениям",
  "secretLabel": "Это секретная {{entity}}", // секретное в контексте сообщества
  "seeAll": "Просмотреть все",
  "select": "Выбрать",
  "selectCountry": "Выбрать страну",
  "selectMonth": "Пожалуйста, выберите месяц",
  "selectedMessage": "сообщение выбрано",
  "selectedMessageDefault": "Выбрать сообщения",
  "selectedMessage_0": "Сообщение выбрано",
  "selectedMessage_1": "Сообщения выбраны",
  "selectedMessage_2": "Сообщений выбрано",
  "send": "Отправить",
  "sendMessage": "Отправить сообщение",
  "sender": "Отправитель",
  "serviceMessages": "Сервисное сообщение",
  "serviceMessagesDescription": "Выберите, какие сообщения получать",
  "serviceMessagesJoins": "Новый участник присоединился",
  "serviceMessagesLeaves": "Участник вышел",
  "settings": "Настройки",
  "share": "Поделиться",
  "shareChallenges": "Выбрать чат и поделиться вашим челленджем",
  "shareLink": "Поделиться ссылкой",
  "shareNothing": "Нечем поделиться {{emoji}}",
  "sharePhoto": "Поделиться фото",
  "shareWith": "Поделиться с",
  "shareWithQuestion": "Поделиться с {{title}}?",
  "shared": "Отправлено",
  "sharedMediaEmpty": "Пока нет {{mediaType}}",
  "sharedMediaEmptyDescription": "{{mediaType}}, которые вы будете отправлять и получать в этом чате, появится здесь", // которое, который, которая - зависит от mediaType
  "sharedMediaTitle": "Медиа, файлы, ссылки",
  "shortThousand": "Т",
  "shortname": "Которое имя",
  "shortnameDescription": "Только a-z, 0-9 и подчеркивания, не менее 3 символов",
  "shortnameUserDescription": "Вы можете выбрать имя пользователя в Openland.\nДругие люди смогут найти вас по этому имени и упомянуть вас в группах.\n\nВы можете использовать a-z, 0-9 и подчеркивания.\nМинимальная длина составляет {{minLength}} символов.\n\n{{username}}",
  "showMore": "Показать больше",
  "signOut": "Выйти",
  "signOutDescription": "Вы уверены, что хотите выйти?",
  "signOutFromApp": "Выйти из приложения",
  "signinMethods": "Способы входа",
  "signupSubtitle": "Помогите другим узнать вас",
  "signupTitle": "Расскажите о себе",
  "skip": "Пропустить",
  "socialSharingImage": "Изображение для социальных сетей",
  "socialSharingImageDescription": "Выберите изображение группы для обмена в социальных сетях",
  "someone": "кто-нибудь",
  "sound": "Звук",
  "speaker": "Спикер",
  "standard": "Standard",
  "start": "Начать",
  "startRoom": "Запустить комнату",
  "status": "Статус",
  "sticker": "стикер",
  "stickerAdd": "Добавить $t(sticker)",
  "stickerAdd_0": "Добавить $t(sticker_0)",
  "stickerAdd_1": "Добавить $t(sticker_1)",
  "stickerAdd_2": "Добавить $t(sticker_2)",
  "stickerDelete": "Удалить $t(sticker)",
  "stickerDelete_0": "Удалить $t(sticker_0)",
  "stickerDelete_1": "Удалить $t(sticker_1)",
  "stickerDelete_2": "Удалить $t(sticker_2)",
  "stickerPackDelete": "Удалить {{title}} стикерпак?",
  "stickerPackPrivate": "Этот секретный стикерпак",
  "stickerPackRemoved": "Стикерпак удален или временно недоступен",
  "stickerPackUnavailable": "Стикерпак недоступен",
  "sticker_0": "стикер",
  "sticker_1": "стикера",
  "sticker_2": "стикеров",
  "stickersClearRecent": "Очистить недавние стикеры?",
  "stickersDeletePack": "Удалить {{title}} стикеры?",
  "stickersDiscover": "Найти стикеры",
  "stickersDiscoverDescription": "Ваши стикеры будут отображаться здесь",
  "submitCodeNotReceived": "Не пришел код?",
  "submitCodeSent": "Мы только что отправили {{receiver}}.",
  "submitCodeWait": "Подождите {{seconds}} секунд", // секуду - зависит от seconds
  "subscriptionCancel": "Отменить подписку",
  "subscriptionCancelDescription": "Если вы отмените подписку сейчас, вы останетесь\nв группе до {{expireDate}}",
  "subscriptions": "Подписки",
  "subscriptionsEmpty": "У вас еще нет подписок",
  "subscriptionsEmptyDescription": "Присоединяйтесь к премиум-группам, и они появятся здесь",
  "subscriptionsStarted": "Следующий платёж в {{date}}",
  "subscriptionsPaymentFailed": "Оплата не удалась",
  "subscriptionsCanceled": "Истекает {{date}}",
  "subscriptionsExpired": "Истекла {{date}}",
  "subscriptionsPeriod": "период",
  "suggestedChats": "Вот несколько чатов, которые могут быть вам интересны",
  "superEdit": "Супер редактирование",
  "superadminSettings": "Настройки суперадмина",
  "termsOfService": "Условия использования",
  "theme": "Тема",
  "themeAccent": "Основной цвет",
  "themeDark": "Темная",
  "themeFeaturedMark": "Знак рекомендованного контента",
  "themeLargeEmoji": "Эмоджи в большом размере",
  "themeLight": "Светлая",
  "themePreviewAnswer": "Хорошо. Спасибо!",
  "themePreviewQuestion": "Привет! Как дела?",
  "themeSystem": "Системная",
  "themeTrueDark": "Черная",
  "threadFollow": "Подписаться на обсуждения",
  "threadUnfollow": "Отписаться от обсуждений",
  "thumbsUp": "Лайк",
  "totalAmount": "Общая сумма",
  "transacitonFailed": "Транзакция не удалась",
  "transactions": "Транзакции",
  "tryAgain": "Попробовать снова",
  "type": "Введите",
  "typing": "печатает",
  "typingFile": "отправляет файл",
  "typingPhoto": "отправляет фото",
  "typingSticker": "прикрепляет стикер",
  "typingVideo": "загружает видео",
  "unblockPerson": "Разблокировать пользователя",
  "unfollow": "Отписаться",
  "unfollowed": "Отписан",
  "unmute": "Отключить звук",
  "unmuteShort": "Звук",
  "unpin": "Открепить",
  "unpinned": "Откреплено",
  "unsupportedMessage": "Сообщение не поддерживается в вашей версии Openland.\nПожалуйста, обновите приложение, чтобы просмотреть его.",
  "updateAppDescription": "Обновите свое приложение, чтобы получить новые замечательные функции",
  "updateAppTitle": "Доступно обновление",
  "updateNow": "Обновить",
  "upload": "Загрузить",
  "uploadPhoto": "Загрузить фото",
  "userGuide": "Руководство пользователя",
  "username": "Имя пользователя",
  "validationAmountMax": "${{amount}} максимум",
  "validationAmountMin": "${{amount}} минимум",
  "validationDate": "Пожалуйста, введите корректные данные",
  "validationDescriptionMaxChars": "Ваше описание должно быть меньше, чем {{num}} символов", // символа - зависит от допустимого кол-ва символов
  "validationEnterName": "Пожалуйста, введите имя",
  "validationEnterPrice": "Пожалуйста, введите корректную цену",
  "validationLink": "Введите корректную ссылку",
  "validationMaxChars": "Должно быть не более {{num}} символов", // символа - зависит от допустимого кол-ва символов
  "validationMinChars": "Должно быть как минимум {{num}} символов", // символа - зависит от допустимого кол-ва символов
  "validationNumbersOnly": "Можно использовать только цифры",
  "validationProfileName": "Пожалуйста, напишите свое имя. Эта информация является частью вашего публичного профиля.",
  "validationShortname": "Можно использовать только a-z, 0-9, и подчеркивания",
  "version": "Версия",
  "video": "Видео",
  "viewChannel": "Просмотреть канал",
  "viewGroup": "Просмотреть группу",
  "viewMessages": "Просмотреть сообщения",
  "viewProfile": "Просмотреть профиль",
  "visibility": "Видимость",
  "visibilityPublic": "Публичная", // публичное в контексте сообщества
  "visibilityPublicDescription": "Видимый в поиске по группам", // видимая (группа, организация), видимое (сообщество)
  "visibilitySecret": "Секретная", // секретное в контексте сообщества
  "visibilitySecretDescription": "Только по приглашению",
  "waitingForNetwork": "Ожидание сети...",
  "wallet": "Оплаты",
  "walletEmpty": "На ваш счет пока не поступали средства",
  "walletBasic": "Основной",
  "walletDeposit": "Депозит",
  "walletDonation": "Пожертвование",
  "walletIncome": "Доход",
  "walletPayment": "Платеж",
  "walletPremiumReaction": "Премиальная реакция",
  "walletSubscription": "Подписка",
  "walletTopUpBalance": "Пополнить баланс",
  "walletTransaction": "Транзакция",
  "walletTransfer": "Перевод",
  "warningAddMembers": "Знаете ли вы людей, которых добавляете?",
  "warningAddMembersDescription": "Пожалуйста, добавляйте только тех людей, которым будет интересна ваша группа",
  "warningPremiumReaction": "Премиум реакция",
  "warningPremiumReactionDescription": "Поддержите автора, сделав пожертвование",
  "website": "Сайт",
  "week": "Неделя",
  "welcomeMessage": "Приветственное сообщение",
  "welcomeMessageAllow": "Разрешить приветсвенные сообщения",
  "welcomeMessageDescription": "Отправляйте автоматически личное приветственное сообщение каждому новому члену группы",
  "whatToJoin": "What to join",
  "withdraw": "Вывести",
  "withdrawFunds": "Вывести средства",
  "withdrawFundsDescription": "Чтобы запросить вывод сдедств от $50, обратитесь в поддержку Openland для дальнейших инструкций",
  "wow": "Вау",
  "year": "Год",
  "yesSure": "Да, я уверен",
  "you": "Вы",
  "yourBalance": "Ваш баланс",
  "yourEmail": "Ваш email",
  "yourMessaage": "Ваше сообщение",
  "yourPhone": "Ваш номер телефона",
  "dateTime": {
    "today": "Сегодня",
    "yesterday": "Вчера",
    "now": "сейчас",
    "at": "в",
    "shortMinute": "м",
    "shortHour": "ч",
    "shortDay": "д",
    "justNow": "прямо сейчас",
    "lastSeenYesterday": "последний раз был(а) в сети вчера",
    "lastSeenTwoDays": "последний раз был(а) в сети два дня назад",
    "lastSeenLongTime": "нет в сети",
    "lastSeenDefault": "был(а) в сети",
    "yearsOldShort": "лет"
  }
};
