fastlane_version '2.53.1'

#
# Configure
#

lane :configure do
end

#
# Build
#

lane :build_android do
    gradle(task: 'clean', project_dir: 'android/', flags: '--info')
    gradle(task: 'bundle', build_type: 'Release', project_dir: 'android/')
end

lane :build_ios do
    get_provisioning_profile(app_identifier: 'com.openland.app')
    get_provisioning_profile(app_identifier: 'com.openland.app.openland-share-ex')
    build_app(
        scheme: 'Production', 
        clean: true,
        workspace: './ios/openland.xcworkspace',
        output_directory: './fastlane/build',
        output_name: 'Openland.ipa'
    )
end

lane :build do
    build_android
    build_ios
end

#
# Upload
#

lane :upload_ios do
    upload_to_testflight(ipa: './fastlane/build/Openland.ipa', skip_waiting_for_build_processing: true)
end

lane :upload_android do
   upload_to_play_store(aab: './android/app/build/outputs/bundle/release/app-release.aab', track: 'internal')
end

lane :upload do
    upload_android
    upload_ios
end

#
# Release
#

lane :release do
    build
    upload
end