# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Build Production App"
  lane :build do
    build_app(workspace: "openland.xcworkspace", scheme: "Production", output_directory: "build", output_name: "Openland.ipa")
  end
  lane :deploy do
    upload_to_testflight(skip_waiting_for_build_processing: true)
  end
end
