# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Build Production App"
  lane :build do
    increment_build_number(build_number: ENV["BUILD_NUMBER"],xcodeproj: "openland.xcodeproj")
    build_app(workspace: "openland.xcworkspace", scheme: "Production")
  end
end
