/* tslint:disable */
//  This file was automatically generated and should not be edited.

export enum PermitStatus {
  FILING = "FILING",
  FILED = "FILED",
  ISSUED = "ISSUED",
  COMPLETED = "COMPLETED",
  EXPIRED = "EXPIRED",
  CANCELLED = "CANCELLED",
  DISAPPROVED = "DISAPPROVED",
  APPROVED = "APPROVED",
  ISSUING = "ISSUING",
  REVOKED = "REVOKED",
  WITHDRAWN = "WITHDRAWN",
  PLANCHECK = "PLANCHECK",
  SUSPENDED = "SUSPENDED",
  REINSTATED = "REINSTATED",
  INSPECTING = "INSPECTING",
  UPHELD = "UPHELD",
  INCOMPLETE = "INCOMPLETE",
  GRANTED = "GRANTED",
  APPEAL = "APPEAL",
}


export enum PermitType {
  NEW_CONSTRUCTION = "NEW_CONSTRUCTION",
  ADDITIONS_ALTERATIONS_REPARE = "ADDITIONS_ALTERATIONS_REPARE",
  OTC_ADDITIONS = "OTC_ADDITIONS",
  WALL_OR_PAINTED_SIGN = "WALL_OR_PAINTED_SIGN",
  SIGN_ERRECT = "SIGN_ERRECT",
  DEMOLITIONS = "DEMOLITIONS",
  GRADE_QUARRY_FILL_EXCAVATE = "GRADE_QUARRY_FILL_EXCAVATE",
}


export enum PermitSorting {
  STATUS_CHANGE_TIME = "STATUS_CHANGE_TIME",
  CREATE_TIME = "CREATE_TIME",
  COMPLETE_TIME = "COMPLETE_TIME",
  ISSUED_TIME = "ISSUED_TIME",
  APPROVAL_TIME_ASC = "APPROVAL_TIME_ASC",
  APPROVAL_TIME_DESC = "APPROVAL_TIME_DESC",
}


export interface PermitQueryVariables {
  permitId: string,
};

export interface PermitQuery {
  permit:  {
    __typename: "Permit",
    id: string,
    issuedAt: string | null,
    createdAt: string | null,
    startedAt: string | null,
    expiresAt: string | null,
    expiredAt: string | null,
    completedAt: string | null,
    filedAt: string | null,
    status: PermitStatus | null,
    statusUpdatedAt: string | null,
    type: PermitType | null,
    typeWood: boolean | null,
    existingStories: number | null,
    proposedStories: number | null,
    existingUnits: number | null,
    proposedUnits: number | null,
    existingAffordableUnits: number | null,
    proposedAffordableUnits: number | null,
    proposedUse: string | null,
    description: string | null,
    governmentalUrl: string,
    approvalTime: number | null,
    streetNumbers:  Array< {
      __typename: "StreetNumber",
      streetId: string,
      streetName: string,
      streetNameSuffix: string | null,
      streetNumber: number,
      streetNumberSuffix: string | null,
    } >,
    events:  Array<( {
        __typename: "PermitEventStatus",
        oldStatus: PermitStatus | null,
        newStatus: PermitStatus | null,
        date: string | null,
      } | {
        __typename: "PermitEventFieldChanged",
        fieldName: string,
        oldValue: string | null,
        newValue: string | null,
        date: string | null,
      }
    ) >,
    relatedPermits:  Array< {
      __typename: "Permit",
      id: string,
      createdAt: string | null,
      status: PermitStatus | null,
      type: PermitType | null,
      typeWood: boolean | null,
      description: string | null,
      approvalTime: number | null,
      existingUnits: number | null,
      proposedUnits: number | null,
      statusUpdatedAt: string | null,
      filedAt: string | null,
      streetNumbers:  Array< {
        __typename: "StreetNumber",
        streetId: string,
        streetName: string,
        streetNameSuffix: string | null,
        streetNumber: number,
        streetNumberSuffix: string | null,
      } >,
    } >,
  } | null,
};

export interface PermitsConnectionQueryVariables {
  cursor?: string | null,
  filter?: string | null,
  page?: number | null,
  type?: PermitType | null,
  sort?: PermitSorting | null,
  minUnits?: number | null,
  issuedYear?: string | null,
  fromPipeline?: boolean | null,
};

export interface PermitsConnectionQuery {
  items:  {
    __typename: "PermitsConnection",
    edges:  Array< {
      __typename: "PermitEdge",
      node:  {
        __typename: "Permit",
        id: string,
        createdAt: string | null,
        status: PermitStatus | null,
        statusUpdatedAt: string | null,
        type: PermitType | null,
        typeWood: boolean | null,
        description: string | null,
        approvalTime: number | null,
        proposedUnits: number | null,
        existingUnits: number | null,
        streetNumbers:  Array< {
          __typename: "StreetNumber",
          streetId: string,
          streetName: string,
          streetNameSuffix: string | null,
          streetNumber: number,
          streetNumberSuffix: string | null,
        } >,
      },
      cursor: string,
    } >,
    pageInfo:  {
      __typename: "PageInfo",
      hasNextPage: boolean,
      hasPreviousPage: boolean,
      itemsCount: number,
      currentPage: number,
      pagesCount: number,
      openEnded: boolean,
    },
  } | null,
};

export interface ProjectQueryVariables {
  areaId: string,
  projectId: string,
};

export interface ProjectQuery {
  project:  {
    __typename: "BuildingProject",
    id: string,
    slug: string,
    name: string,
    description: string | null,
    status: string | null,
    startedAt: string | null,
    completedAt: string | null,
    expectedCompletedAt: string | null,
    verified: boolean,
    existingUnits: number | null,
    proposedUnits: number | null,
    existingAffordableUnits: number | null,
    proposedAffordableUnits: number | null,
    preview:  {
      __typename: "Picture",
      url: string,
      retina: string,
    } | null,
    extrasDeveloper: string | null,
    extrasGeneralConstructor: string | null,
    extrasYearEnd: string | null,
    extrasAddress: string | null,
    extrasAddressSecondary: string | null,
    extrasPermit: string | null,
    extrasComment: string | null,
    extrasUrl: string | null,
    extrasLocation:  {
      __typename: "Geo",
      latitude: number,
      longitude: number,
    } | null,
    developers:  Array< {
      __typename: "Organization",
      id: string,
      slug: string,
      title: string,
      logo: string | null,
      isDeveloper: boolean,
      isConstructor: boolean,
    } >,
    constructors:  Array< {
      __typename: "Organization",
      id: string,
      slug: string,
      title: string,
      logo: string | null,
      isDeveloper: boolean,
      isConstructor: boolean,
    } >,
    permits:  Array< {
      __typename: "Permit",
      id: string,
      createdAt: string | null,
      status: PermitStatus | null,
      statusUpdatedAt: string | null,
      type: PermitType | null,
      typeWood: boolean | null,
      description: string | null,
      approvalTime: number | null,
      proposedUnits: number | null,
      existingUnits: number | null,
      streetNumbers:  Array< {
        __typename: "StreetNumber",
        streetId: string,
        streetName: string,
        streetNameSuffix: string | null,
        streetNumber: number,
        streetNumberSuffix: string | null,
      } >,
    } >,
  },
};

export interface ProjectsConnectionQueryVariables {
  areaId: string,
  cursor?: string | null,
  minUnits?: number | null,
  year?: string | null,
  filter?: string | null,
};

export interface ProjectsConnectionQuery {
  items:  {
    __typename: "BuildingProjectConnection",
    edges:  Array< {
      __typename: "BuildingProjectEdge",
      node:  {
        __typename: "BuildingProject",
        id: string,
        slug: string,
        name: string,
        description: string | null,
        status: string | null,
        extrasYearEnd: string | null,
        extrasAddress: string | null,
        extrasAddressSecondary: string | null,
        existingUnits: number | null,
        proposedUnits: number | null,
        verified: boolean,
        extrasUrl: string | null,
        preview:  {
          __typename: "Picture",
          url: string,
          retina: string,
        } | null,
      },
      cursor: string,
    } >,
    pageInfo:  {
      __typename: "PageInfo",
      hasNextPage: boolean,
      hasPreviousPage: boolean,
      itemsCount: number,
      currentPage: number,
      pagesCount: number,
      openEnded: boolean,
    },
    stats:  {
      __typename: "BuildingProjectConnectionStats",
      newUnits: number,
      newUnitsVerified: number,
      totalProjects: number,
      totalProjectsVerified: number,
    },
  },
};

export interface PermitShortFragment {
  __typename: "Permit",
  id: string,
  createdAt: string | null,
  status: PermitStatus | null,
  statusUpdatedAt: string | null,
  type: PermitType | null,
  typeWood: boolean | null,
  description: string | null,
  approvalTime: number | null,
  proposedUnits: number | null,
  existingUnits: number | null,
  streetNumbers:  Array< {
    __typename: string,
    streetId: string,
    streetName: string,
    streetNameSuffix: string | null,
    streetNumber: number,
    streetNumberSuffix: string | null,
  } >,
};

export interface PermitFullFragment {
  __typename: "Permit",
  id: string,
  issuedAt: string | null,
  createdAt: string | null,
  startedAt: string | null,
  expiresAt: string | null,
  expiredAt: string | null,
  completedAt: string | null,
  filedAt: string | null,
  status: PermitStatus | null,
  statusUpdatedAt: string | null,
  type: PermitType | null,
  typeWood: boolean | null,
  existingStories: number | null,
  proposedStories: number | null,
  existingUnits: number | null,
  proposedUnits: number | null,
  existingAffordableUnits: number | null,
  proposedAffordableUnits: number | null,
  proposedUse: string | null,
  description: string | null,
  governmentalUrl: string,
  approvalTime: number | null,
  streetNumbers:  Array< {
    __typename: string,
    streetId: string,
    streetName: string,
    streetNameSuffix: string | null,
    streetNumber: number,
    streetNumberSuffix: string | null,
  } >,
  events:  Array<( {
      __typename: "PermitEventStatus",
      oldStatus: PermitStatus | null,
      newStatus: PermitStatus | null,
      date: string | null,
    } | {
      __typename: "PermitEventFieldChanged",
      fieldName: string,
      oldValue: string | null,
      newValue: string | null,
      date: string | null,
    }
  ) >,
  relatedPermits:  Array< {
    __typename: string,
    id: string,
    createdAt: string | null,
    status: PermitStatus | null,
    type: PermitType | null,
    typeWood: boolean | null,
    description: string | null,
    approvalTime: number | null,
    existingUnits: number | null,
    proposedUnits: number | null,
    statusUpdatedAt: string | null,
    filedAt: string | null,
    streetNumbers:  Array< {
      __typename: string,
      streetId: string,
      streetName: string,
      streetNameSuffix: string | null,
      streetNumber: number,
      streetNumberSuffix: string | null,
    } >,
  } >,
};

export interface ProjectShortFragment {
  __typename: "BuildingProject",
  id: string,
  slug: string,
  name: string,
  description: string | null,
  status: string | null,
  extrasYearEnd: string | null,
  extrasAddress: string | null,
  extrasAddressSecondary: string | null,
  existingUnits: number | null,
  proposedUnits: number | null,
  verified: boolean,
  extrasUrl: string | null,
  preview:  {
    __typename: string,
    url: string,
    retina: string,
  } | null,
};

export interface ProjectFullFragment {
  __typename: "BuildingProject",
  id: string,
  slug: string,
  name: string,
  description: string | null,
  status: string | null,
  startedAt: string | null,
  completedAt: string | null,
  expectedCompletedAt: string | null,
  verified: boolean,
  existingUnits: number | null,
  proposedUnits: number | null,
  existingAffordableUnits: number | null,
  proposedAffordableUnits: number | null,
  preview:  {
    __typename: string,
    url: string,
    retina: string,
  } | null,
  extrasDeveloper: string | null,
  extrasGeneralConstructor: string | null,
  extrasYearEnd: string | null,
  extrasAddress: string | null,
  extrasAddressSecondary: string | null,
  extrasPermit: string | null,
  extrasComment: string | null,
  extrasUrl: string | null,
  extrasLocation:  {
    __typename: string,
    latitude: number,
    longitude: number,
  } | null,
  developers:  Array< {
    __typename: string,
    id: string,
    slug: string,
    title: string,
    logo: string | null,
    isDeveloper: boolean,
    isConstructor: boolean,
  } >,
  constructors:  Array< {
    __typename: string,
    id: string,
    slug: string,
    title: string,
    logo: string | null,
    isDeveloper: boolean,
    isConstructor: boolean,
  } >,
  permits:  Array< {
    __typename: string,
    id: string,
    createdAt: string | null,
    status: PermitStatus | null,
    statusUpdatedAt: string | null,
    type: PermitType | null,
    typeWood: boolean | null,
    description: string | null,
    approvalTime: number | null,
    proposedUnits: number | null,
    existingUnits: number | null,
    streetNumbers:  Array< {
      __typename: string,
      streetId: string,
      streetName: string,
      streetNameSuffix: string | null,
      streetNumber: number,
      streetNumberSuffix: string | null,
    } >,
  } >,
};
