
// Objective-C API for talking to the following Go packages
//
//	github.com/openland/soyuz/mobile
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Soyuz_FRAMEWORK_H__
#define __Soyuz_FRAMEWORK_H__

#include "SZSoyuz.objc.h"
#include "Universe.objc.h"

#endif
