// WARNING! THIS IS AUTOGENERATED FILE. DO NOT EDIT!

import { typedMutation } from 'openland-x-graphql/typed';
import { typedQuery } from 'openland-x-graphql/typed';
import * as Raw from './Account';
import * as Types from '../Types';

export const AccountQuery = typedQuery<Types.AccountQuery, {}>(Raw.AccountQuery);
export const CreateOrganizationMutation = typedMutation<Types.CreateOrganizationMutation, Types.CreateOrganizationMutationVariables>(Raw.CreateOrganizationMutation);
export const AccountInviteInfoQuery = typedQuery<Types.AccountInviteInfoQuery, Types.AccountInviteInfoQueryVariables>(Raw.AccountInviteInfoQuery);
export const AccountInviteJoinMutation = typedMutation<Types.AccountInviteJoinMutation, Types.AccountInviteJoinMutationVariables>(Raw.AccountInviteJoinMutation);
export const AccountInvitesQuery = typedQuery<Types.AccountInvitesQuery, {}>(Raw.AccountInvitesQuery);
export const AccountCreateInviteMutation = typedMutation<Types.AccountCreateInviteMutation, {}>(Raw.AccountCreateInviteMutation);
export const AccountDestroyInviteMutation = typedMutation<Types.AccountDestroyInviteMutation, Types.AccountDestroyInviteMutationVariables>(Raw.AccountDestroyInviteMutation);
export const ProfilePrefillQuery = typedQuery<Types.ProfilePrefillQuery, {}>(Raw.ProfilePrefillQuery);