// WARNING! THIS IS AUTOGENERATED FILE. DO NOT EDIT!

import { typedQuery } from 'openland-x-graphql/typed';
import * as Raw from './Addressing';
import * as Types from '../Types';

export const StateQuery = typedQuery<Types.StateQuery, {}>(Raw.StateQuery);
export const CountyQuery = typedQuery<Types.CountyQuery, Types.CountyQueryVariables>(Raw.CountyQuery);