// WARNING! THIS IS AUTOGENERATED FILE. DO NOT EDIT!

import { typedQuery } from 'openland-x-graphql/typed';
import * as Raw from './Debug';
import * as Types from '../Types';

export const DebugReadedStatesQuery = typedQuery<Types.DebugReadedStatesQuery, {}>(Raw.DebugReadedStatesQuery);