// WARNING! THIS IS AUTOGENERATED FILE. DO NOT EDIT!

import { typedMutation } from 'openland-x-graphql/typed';
import { typedQuery } from 'openland-x-graphql/typed';
import * as Raw from './Organization';
import * as Types from '../Types';

export const MyOrganizationQuery = typedQuery<Types.MyOrganizationQuery, {}>(Raw.MyOrganizationQuery);
export const MyOrganizationProfileQuery = typedQuery<Types.MyOrganizationProfileQuery, {}>(Raw.MyOrganizationProfileQuery);
export const MyOrganizationsQuery = typedQuery<Types.MyOrganizationsQuery, {}>(Raw.MyOrganizationsQuery);
export const UpdateOrganizationMutation = typedMutation<Types.UpdateOrganizationMutation, Types.UpdateOrganizationMutationVariables>(Raw.UpdateOrganizationMutation);
export const OrganizationQuery = typedQuery<Types.OrganizationQuery, Types.OrganizationQueryVariables>(Raw.OrganizationQuery);
export const FollowOrganizationMutation = typedMutation<Types.FollowOrganizationMutation, Types.FollowOrganizationMutationVariables>(Raw.FollowOrganizationMutation);
export const CreateListingMutation = typedMutation<Types.CreateListingMutation, Types.CreateListingMutationVariables>(Raw.CreateListingMutation);
export const EditListingMutation = typedMutation<Types.EditListingMutation, Types.EditListingMutationVariables>(Raw.EditListingMutation);
export const DeleteListingMutation = typedMutation<Types.DeleteListingMutation, Types.DeleteListingMutationVariables>(Raw.DeleteListingMutation);