// WARNING! THIS IS AUTOGENERATED FILE. DO NOT EDIT!

import { typedQuery } from 'openland-x-graphql/typed';
import * as Raw from './Permits';
import * as Types from '../Types';

export const PermitQuery = typedQuery<Types.PermitQuery, Types.PermitQueryVariables>(Raw.PermitQuery);
export const PermitsConnectionQuery = typedQuery<Types.PermitsConnectionQuery, Types.PermitsConnectionQueryVariables>(Raw.PermitsConnectionQuery);