// WARNING! THIS IS AUTOGENERATED FILE. DO NOT EDIT!

import { typedQuery } from 'openland-x-graphql/typed';
import * as Raw from './Search';
import * as Types from '../Types';

export const SearchQuery = typedQuery<Types.SearchQuery, Types.SearchQueryVariables>(Raw.SearchQuery);