// WARNING! THIS IS AUTOGENERATED FILE. DO NOT EDIT!

import { typedMutation } from 'openland-x-graphql/typed';
import { typedQuery } from 'openland-x-graphql/typed';
import * as Raw from './Settings';
import * as Types from '../Types';

export const ProfileQuery = typedQuery<Types.ProfileQuery, {}>(Raw.ProfileQuery);
export const ProfileUpdateMutation = typedMutation<Types.ProfileUpdateMutation, Types.ProfileUpdateMutationVariables>(Raw.ProfileUpdateMutation);
export const ProfileCreateMutation = typedMutation<Types.ProfileCreateMutation, Types.ProfileCreateMutationVariables>(Raw.ProfileCreateMutation);