// WARNING! THIS IS AUTOGENERATED FILE. DO NOT EDIT!

import { typedQuery } from 'openland-x-graphql/typed';
import * as Raw from './SuperCity';
import * as Types from '../Types';

export const SuperCitiesQuery = typedQuery<Types.SuperCitiesQuery, {}>(Raw.SuperCitiesQuery);