// WARNING! THIS IS AUTOGENERATED FILE. DO NOT EDIT!

import { typedMutation } from 'openland-x-graphql/typed';
import { typedQuery } from 'openland-x-graphql/typed';
import * as Raw from './Tasks';
import * as Types from '../Types';

export const RefreshTaskQuery = typedQuery<Types.RefreshTaskQuery, Types.RefreshTaskQueryVariables>(Raw.RefreshTaskQuery);
export const SampleTaskMutation = typedMutation<Types.SampleTaskMutation, Types.SampleTaskMutationVariables>(Raw.SampleTaskMutation);
export const FolderExportTaskMutation = typedMutation<Types.FolderExportTaskMutation, Types.FolderExportTaskMutationVariables>(Raw.FolderExportTaskMutation);