// WARNING! THIS IS AUTOGENERATED FILE. DO NOT EDIT!

import { typedQuery } from 'openland-x-graphql/typed';
import * as Raw from './User';
import * as Types from '../Types';

export const UsersQuery = typedQuery<Types.UsersQuery, Types.UsersQueryVariables>(Raw.UsersQuery);