import { generate } from 'graphql-code-generator';
import * as fs from 'fs';
import * as path from 'path';

// let documents = fs.readFileSync(__dirname + '/documents.handlebars', 'utf-8');

function prepareTemplate(file: string) {
    fs.writeFileSync(
        __dirname + '/_tmp.js',
        `
        var c = require("graphql-codegen-core");
        var fs = require("fs");
        let documents = fs.readFileSync(__dirname + '/documents.handlebars', 'utf-8');
        var config = {
            inputType: c.EInputType.SINGLE_FILE,
            flattenTypes: true,
            templates: {
                index: documents
            },
            primitives: {
                String: 'string',
                Int: 'number',
                Float: 'number',
                Boolean: 'boolean',
                ID: 'string'
            },
            customHelpers: {
                ifEq: function(v1, v2, options) {
                    if(v1 === v2) {
                      return options.fn(this);
                    }
                    return options.inverse(this);
                }
            },
            outFile: '${file}.tmp'
        };
        exports["default"] = config;
        `,
        'utf-8');
    //     "use strict";
    // exports.__esModule = true;
    // var graphql_codegen_core_1 = require("graphql-codegen-core");
    // var fs = require("fs");
    // var documents = fs.readFileSync(__dirname + '/documents.handlebars', 'utf-8');
    // var config = {
    //     inputType: graphql_codegen_core_1.EInputType.PROJECT,
    //     flattenTypes: true,
    //     templates: {
    //         index: documents
    //     },
    //     primitives: {
    //         String: 'string',
    //         Int: 'number',
    //         Float: 'number',
    //         Boolean: 'boolean',
    //         ID: 'string'
    //     },
    //     filesExtension: '.types.ts'
    //     // outFile: './out.ts'
    // };
    // exports["default"] = config;
}

function postProcess(file: string) {
    let contents = fs.readFileSync(file + '.tmp', 'utf-8');
    contents = contents.trim();
    let fn = path.parse(file);
    contents = 'import * as Raw from \'./' + fn.name + '\';\n' + contents;
    if (contents.indexOf('typedQuery') >= 0) {
        contents = 'import { typedQuery } from \'openland-x-graphql/typed\';\n' + contents;
    }
    if (contents.indexOf('typedMutation') >= 0) {
        contents = 'import { typedMutation } from \'openland-x-graphql/typed\';\n' + contents;
    }
    contents = '// WARNING! THIS IS AUTOGENERATED FILE. DO NOT EDIT!\n\n' + contents;
    fs.writeFileSync(fn.dir + '/' + fn.name + '.types.ts', contents);
    fs.unlinkSync(file + '.tmp');
}

async function doIteration(file: string) {
    console.warn('Processing ' + path.parse(file).base);
    prepareTemplate(file);
    delete require.cache[require.resolve('./_tmp.js')];  
    let genres = generate(
        {
            overwrite: true,
            template: path.resolve(__dirname + '/_tmp.js'),
            schema: path.resolve(__dirname + '/../../schema.json'),
            args: [file]
        },
        true);
    genres.then((v) => console.warn('post2'));
    await genres;
    await new Promise<string>((r) => {
        setTimeout(() => { r(''); }, 100);
    });
    fs.unlinkSync(__dirname + '/_tmp.js');
    postProcess(file);
}

async function doConvert() {
    // process.env.DEBUG = 'true';
    let root = path.resolve(__dirname + '/../openland-api/queries/');
    let res = fs.readdirSync(root);
    res = res.filter((v) => {
        // Special Case for Tasks
        if (v === 'Tasks.ts') {
            return false;
        }
        let parts = v.split('.');
        return parts.length === 2 && parts[1] === 'ts';
    });
    for (let r of res) {
        await doIteration(root + '/' + r);
    }
}

doConvert();
// let res = doConvert();
